### ISSUE TITLE
BSoD after Sleep/Wakeup on Win7 with Npcap-0.9988

### ISSUE THREAD

**Issue by v74863** [nmap/nmap#1975] opened 2020-03-18 18:33 UTC
Blue Screen of Death (BSoD) after Sleep/Wakeup on Win7 (Service Pack 1, 64-bit).
Has tested on two different PCs, default installation (WinPcap compatible mode).
Npcap-0.9988 on Win8.1 works Ok.
Npcap-0.9987 on Win7 works Ok.
Please see attached minidump and diagreport.

P.S. Uninstalling doesn't remove Npcap directory completely, for some reason.
Still need manually delete Npcap directory (with install.txt and NPFInstall.txt) in C:\Program Files

P.S. Broken link of Nmap Project's Issues tracker, right under Reporting Bugs line
https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues

P.S. it seems, Npcap isn't 100%-compatible to Winpcap.
Please see https://github.com/GNS3/gns3-gui/issues/2936
With Winpcap it is possible to ping Microsoft Loopback, with Npcap it isn't.
However, may be this is problem of GNS3 itself?
![BSoD](https://user-images.githubusercontent.com/61684281/76994544-99b7f180-695f-11ea-8219-f8c58cabe779.PNG)
[DiagReport-20200318-200240.txt](https://github.com/nmap/nmap/files/4350681/DiagReport-20200318-200240.txt)
[minidump.zip](https://github.com/nmap/nmap/files/4350690/minidump.zip)

**Comment by dmiller-nmap** [comment] 2020-03-19 17:13
Thanks for reporting this! There are several issues here, most of which are known already:

* BSoD in Npcap 0.9988: duplicate of #1964, fixed in Npcap 0.9989
* Uninstalling does not remove Npcap directory: Sorry about that; code to fix this is already in our build system, but did not make it into Npcap 0.9989. We do properly remove all of WinPcap now, so that's a step in the right direction. Next release will resolve this.
* HTTP links to issues.nmap.org were broken: Just fixed this this morning. An unfortunate side-effect of upgrading to HTTPS for issues.nmap.org.
* Npcap injected packets don't loop back: Known issue #1343, we are evaluating the patch at nmap/npcap#23 for the next release.

Closing this. Feel free to open a new issue if you have issues with Npcap 0.9989, released today!

**Closed by dmiller-nmap** 2020-03-19 17:13 UTC
