### ISSUE TITLE
nmap - zenmap broken on windows

### ISSUE THREAD

**Issue by KamenkoTV** [nmap/nmap#2145] opened 2020-10-08 16:15 UTC
`Starting Nmap 7.90 ( https://nmap.org ) at 2020-10-08 18:14 Central Europe Daylight Time

NSE: Failed to load C:\Program Files (x86)\Nmap/scripts\afp-serverinfo.nse:

C:\Program Files (x86)\Nmap/nselib/afp.lua:353: time result cannot be represented in this installation

stack traceback:

	[C]: in function 'os.time'

	C:\Program Files (x86)\Nmap/nselib/afp.lua:353: in main chunk

	[C]: in function 'require'

	C:\Program Files (x86)\Nmap/scripts\afp-serverinfo.nse:1: in function <C:\Program Files (x86)\Nmap/scripts\afp-serverinfo.nse:1>

NSE: failed to initialize the script engine:

C:\Program Files (x86)\Nmap/nse_main.lua:614: could not load script

stack traceback:

	[C]: in function 'error'

	C:\Program Files (x86)\Nmap/nse_main.lua:614: in field 'new'

	C:\Program Files (x86)\Nmap/nse_main.lua:791: in global 'Entry'

	C:\Program Files (x86)\Nmap/scripts\script.db:6: in local 'db_closure'

	C:\Program Files (x86)\Nmap/nse_main.lua:804: in local 'get_chosen_scripts'

	C:\Program Files (x86)\Nmap/nse_main.lua:1312: in main chunk

	[C]: in ?

QUITTING!

`

i get this error when i try to scan ip.

**Comment by nnposter** [comment] 2020-10-08 17:06
Duplicate of #2136

**Closed by nnposter** 2020-10-08 17:06 UTC
Labels: NSE, bug, duplicate

**Comment by fyodor** [comment] 2020-10-14 21:03
Update: this is now fixed in [Nmap 7.91](https://seclists.org/nmap-announce/2020/2)

**Comment by goarblt** [comment] 2022-04-11 15:15
hello
https://www.evil.com/
