### ISSUE TITLE
Windows 10 storms of DHCP errors on NPCAP adapter

### ISSUE THREAD

**Issue by LorenAmelang** [nmap/nmap#1583] opened 2019-05-02 21:07 UTC
This is not a serious problem, as far as I know, but it certainly clutters my Windows logs! 

Digging for an unrelated problem, I noticed hundreds of these errors in my Win 10 "Administrative Events" log - Event ID 1001:

Your computer was not assigned an address from the network (by the DHCP Server) for the Network Card with network address 0x02004C4F4F50.  The following error occurred: 0x79. Your computer will continue to try and obtain an address on its own from the network address (DHCP) server.

That's the NPCAP address:

> Ethernet adapter Ethernet 3:
> 
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Npcap Loopback Adapter
>    Physical Address. . . . . . . . . : 02-00-4C-4F-4F-50
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::6052:76af:c8fe:3fff%25(Preferred)
>    Autoconfiguration IPv4 Address. . : 169.254.63.255(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.0.0
>    Default Gateway . . . . . . . . . :
>    DHCPv6 IAID . . . . . . . . . . . : 318898252
>    DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-FA-8F-D5-B4-AE-2B-D1-66-5E
>    DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
>                                        fec0:0:0:ffff::2%1
>                                        fec0:0:0:ffff::3%1
>    NetBIOS over Tcpip. . . . . . . . : Enabled
> 
> Ethernet adapter Ethernet 4:
> 
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Npcap Loopback Adapter
>    Physical Address. . . . . . . . . : 02-00-4C-4F-4F-50
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::8c92:25db:8d70:38da%17(Preferred)
>    Autoconfiguration IPv4 Address. . : 169.254.56.218(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.0.0
>    Default Gateway . . . . . . . . . :
>    DHCPv6 IAID . . . . . . . . . . . : 503447628
>    DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-FA-8F-D5-B4-AE-2B-D1-66-5E
>    DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
>                                        fec0:0:0:ffff::2%1
>                                        fec0:0:0:ffff::3%1
>    NetBIOS over Tcpip. . . . . . . . : Enabled
> 

Why does it appear twice? I do have GlassWire as well as Wireshark and (Ze)Nmap installed...  

Why would a loopback adapter be requesting DHCP? 

Windows is continually creating more things like:
    Wireless LAN adapter Local Area Connection* 6:
And shows the above "Ethernet 4" in my system tray list of Wi-Fi APs...  ???

There is no hardware connection on a Surface Book, only the one Wi-Fi adapter. Maybe all those other things are stubs in case somebody plugs in the USB to Ethernet dock? Which I've never had...  

If I disable or uninstall them, it eventually puts them back...  

The DHCP error storms began 14Feb19 13:57
Seem to repeat once or twice on hibernate or wake
Bursts like to appear around 2PM, sometimes 1 or 3 or 4 PM, but can happen any time. Yesterday they spanned the afternoon, pairs of errors at ~2 minute intervals, then ~5, ~10, ~30 minutes...  The ~2 minute intervals began again on every wake from hibernation. But some days I only see the hibernate / wake instances...  

That Feb 14 origin was just after installing Microsoft update KB4023057, a day after KB4487017...
"This update may try to reset network settings if problems are detected, and it will clean up registry keys that may be preventing updates from being installed successfully."
"To help free up disk space, this update may compress files in your user profile directory so that Windows Update can install important updates. When files or folders are compressed, they appear as having two blue arrows overlaid on the icon. 
After you install the update, your files are restored to their original state, and the blue arrows disappear from the file icons in File Explorer. At any point during the update process, you should be able to access your files."

It compressed most of my user files, and has not uncompressed them, even though I have 14.8 GB of free space...  

Probably unrelated, but I first noticed NPCAP storms Jan 29 when I installed a new Wireshark and npcap-0.99-r9.exe and logged over 700 of these in about an hour:

The Npcap Packet Driver (NPCAP) service failed to start due to the following error: 
The system cannot find the file specified.

After a restart that went away and hasn't returned. 

Your NPCAP install log now shows
\NpcapInst" "DisplayName"="Npcap 0.992"
beyond that Jan 29 version, but I have no idea when that happened, and can't find any dates in the file!

**Comment by dmiller-nmap** [comment] 2019-09-04 22:42
Thanks for the report! The Npcap Loopback Adapter was known to cause problems with some software, so we removed the need for it in Npcap 0.9983, released today. Be sure to deselect (un-check) the "Legacy loopback support" to get the new loopback capture support without cluttering up the list of real network adapters. Let us know how it works for you.

**Comment by LorenAmelang** [comment] 2019-09-07 01:11
Finally got a chance to install 0.9983. Did uncheck the legacy adapter option. Wireshark sees it, and shows the "Adapter for loopback traffic capture", but it still shows the random collection of "Local Area Connection* 3-14" interfaces. Are they supposed to be gone now? I could disable them, but Windows will just make more...  Maybe there is some trick to force Wireshark to forget them and not find more? 

I don't see NPCAP loopback in my Device Manager or ipconfig any more. 

And I don't see any loopback DHCP errors in the logs. There are a bunch of these since the install reboot:
-----
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user DESKTOP-OMMHHCL\loren SID (S-1-5-21-2642381790-255542418-257213659-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
-----
No idea what that is...  


About Wireshark:
Version 3.0.3 (v3.0.3-0-g6130b92b0ec6) 

Compiled (64-bit) with Qt 5.12.4, with WinPcap SDK (WpdPack) 4.1.2, with GLib 2.52.2, with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.14.0, with Lua 5.2.4, with GnuTLS 3.6.3 and PKCS #11 support, with Gcrypt 1.8.3, with MIT Kerberos, with MaxMind DB resolver, with nghttp2 1.14.0, with LZ4, with Snappy, with libxml2 2.9.9, with QtMultimedia, with AirPcap, with SBC, with SpanDSP, with bcg729. 

Running on 64-bit Windows 10 (1803), build 17134, with Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (with SSE4.2), with 8117 MB of physical memory, with locale English_United States.1252, with Npcap version 0.9983, based on libpcap version 1.9.1-PRE-GIT, with GnuTLS 3.6.3, with Gcrypt 1.8.3, without AirPcap, binary plugins supported (14 loaded). Built using Microsoft Visual Studio 2017 (VC++ 14.16, build 27030).

**Comment by HelderMagalhaes** [comment] 2019-10-02 19:30
> >  [...] COM Server application with CLSID {D63B10C5-BB46-4990-A94F-E40B9D520160}
>
> No idea what that is...

[According to the registry](https://superuser.com/questions/657511/where-to-get-software-name-of-clsid), _that_ is `RuntimeBroker.exe`.

I believe it's _not_ related to the issue and is likely related to some Windows 10 update, or it was already there before but previous errors were too many and were obscuring it. In my machine I regularly get these events when simply opening the Start menu (via mouse or <kbd>Win</kbd> key).

That said, given the rest of the positive comment by @LorenAmelang, I'd say this issue is closed - likely as a duplicate of the "Legacy loopback support" removal.

**Comment by LorenAmelang** [comment] 2019-10-02 20:08
Sounds right to me! But I'll let somebody else actually push the close button...

**Comment by dmiller-nmap** [comment] 2019-10-03 05:01
Great, glad to hear this is working for you. We do have an issue to track removal of extraneous leftover Npcap Loopback Adapter devices at #1634. There is a manual removal procedure in the description for that issue. Closing this one.

**Closed by dmiller-nmap** 2019-10-03 05:01 UTC
