### ISSUE TITLE
Logic mistake in SMB.lua

### ISSUE THREAD

**Issue by bpdevries1** [nmap/nmap#1405] opened 2018-12-05 15:03 UTC
It always picks the netbios domain and not the domain in  --script-args=smbdomain=<domain>

at line 1404 in smb.lua
if ( smb['domain'] or smb['server'] and ( not(domain) or #domain == 0 ) ) then

Should prolly be:

if ( (smb['domain'] or smb['server']) and ( not(domain) or #domain == 0 ) ) then

**Comment by nnposter** [comment] 2019-09-08 02:11
This appears to be a duplicate of #1544. Fixed in 0855eb4c0c38b6e9a455a005faad7bf197315362.

**Closed by nnposter** 2019-09-08 02:11 UTC
