### ISSUE TITLE
[npcap] - wireshark stopped see adapters after windows 10 updated to "annivarsary edition"

### ISSUE THREAD

**Issue by zdm** [nmap/nmap#492] opened 2016-08-07 19:11 UTC
Hi.
Today windows 10 was updated and wireshark don't see network adapters any more.
I am tried to reinstall npcap and wireshark - this wasn't helpful.
Npcap installed in winpcap compat. mode and wireshark detected npcap during install process.

**Comment by zdm** [comment] 2016-08-07 20:00
Winpcap works.
Npcap - not.

**Comment by hsluoyz** [comment] 2016-08-08 00:42
Hi @zdm ,

Is your OS x86 or x64? Which Npcap version and Wireshark version did you use? Thanks.

**Comment by zdm** [comment] 2016-08-08 04:58
Windows 10 x64

Wireshark 2.0.5 x 64

I tried following npcap versions:
0.08-r2
0.08
0.07-r17

**Comment by hsluoyz** [comment] 2016-08-08 05:10
I tried your environment and didn't encounter that issue. What error message did you actually see?

**Comment by zdm** [comment] 2016-08-08 05:12
Wireshark doesn't show any errors, just shows no adapters.

**Comment by hsluoyz** [comment] 2016-08-08 05:14
1. Install Npcap with default options.
2. Reboot after intall.
3. try ``nmap --iflist" and paste the output here.

**Comment by zdm** [comment] 2016-08-08 05:39
I have removed winpcap and installed npcap-v0.08-r2 with default options.

In not elevated cmd nmap return nothing:
![screenshot 2016-08-08 08 36 38](https://cloud.githubusercontent.com/assets/1025608/17470255/87f469fa-5d43-11e6-9fe1-1430ada66e07.png)

But in elevated I got error:
![screenshot 2016-08-08 08 36 48](https://cloud.githubusercontent.com/assets/1025608/17470266/9afa977c-5d43-11e6-852f-8e5b4b96b761.png)

**Comment by hsluoyz** [comment] 2016-08-08 05:41
Oh, I forgot to see. Please install Nmap's dev version: https://nmap.org/dist/nmap-7.25BETA1-setup.exe

**Comment by zdm** [comment] 2016-08-08 05:44
With nmap-7.25-beta1 results are the same.

**Comment by hsluoyz** [comment] 2016-08-08 06:05
1. See if the ``C:\Windows\System32\Npcap`` folder contains these two files: ``wpcap.dll, Packet.dll``
2. In Administrator CMD, enter ``sc query npcap`` and paste the result here.

**Comment by zdm** [comment] 2016-08-08 06:08
1. Files are present;
2. Service is stopped
```
SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 31  (0x1f)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by hsluoyz** [comment] 2016-08-08 06:13
In Administrator CMD, enter ``net start npcap`` and paste the result here.

**Comment by zdm** [comment] 2016-08-08 06:15
Problem with signature
```
d:\downloads\111>net start npcap
System error 577 has occurred.

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```

**Comment by hsluoyz** [comment] 2016-08-08 06:29
1. Unzip the attached ``signtool.zip``, put ``signtool.exe`` to somewhere your CMD can find (e.g. . ``C:\Program Files\Npcap``)
2. In CMD, cd into the ``C:\Program Files\Npcap`` path, enter ``signtool verify /kp /c npcap.cat npcap.sys`` and paste the result here.

[signtool.zip](https://github.com/nmap/nmap/files/406188/signtool.zip)

**Comment by zdm** [comment] 2016-08-08 06:32
0      sha256     RFC3161
Successfully verified: npcap.sys

**Comment by hsluoyz** [comment] 2016-08-08 06:54
1. Restore the OS to the un-updated state.
2. Uninstall Npcap.
3. OS Update.
4. Install Npcap.

**Comment by zdm** [comment] 2016-08-08 06:57
I made clean os install a day ago.

**Comment by hsluoyz** [comment] 2016-08-08 07:01
I have no idea what happened.. Can I get a remote access?

**Comment by zdm** [comment] 2016-08-08 07:11
yes, do you have teamviewer?

**Comment by hsluoyz** [comment] 2016-08-08 07:15
Yes. You can email me the password:) hsluoyz@gmail.com

**Comment by hsluoyz** [comment] 2016-08-08 07:48
The network connectivity is so bad. I can't even move the mouse in the remote window.

**Comment by zdm** [comment] 2016-08-08 07:51
I don't know why, I have 100 Mb channel.

I need to go to the office now, and will be available in several hours.

So, the problem in the driver signature.

I will try to find the solution too, I  already check, that your
certificate is stored as trusted.

**Comment by zdm** [comment] 2016-08-08 16:50
I found the article, that describes drivers signing changes in windows
10 anniversary edition.

http://www.thewindowsclub.com/driver-signing-changes-windows-10

Maybe this will helpful to solve the problem.

**Comment by zdm** [comment] 2016-08-08 16:52
I think, that this requirement should be met:

"The latest version of Windows 10 will load only Kernel mode drivers
signed digitally by the Dev Portal. However, the changes will affect
only the new installations of the operating system with Secure Boot
<http://www.thewindowsclub.com/understanding-measured-boot-secure-boot-work-windows-8>
on. The non-upgraded fresh installations would require drivers signed by
Microsoft."

**Comment by hsluoyz** [comment] 2016-08-09 14:39
Thanks! This should be the reason.

1. PCs upgraded to Windows 10 Build 1607 from a previous version of Windows (for instance Windows 10 version 1511) are not affected by the change.
2. PCs without Secure Boot functionality, or Secure Boot off, are not affected either.
3. All drivers signed with cross-signing certificates that were issued prior to July 29, 2015, will continue to work.
4. Boot drivers won’t be blocked to prevent systems from failing to boot. They will be removed by the Program Compatibility Assistant, however.
5. The change affects only Windows 10 Version 1607. All previous versions of Windows are not affected.

But it's a little weird. Even the latest Npcap 0.08 r3's driver files were signed in July, 24. So according to the condition 3., Npcap driver should work without signature issues. I don't know why you encounter this issue.

Moreover, I have tried to reproduce this issue. I have installed a fresh Win10 1607 x64 in my VMware Workstation 12, but Npcap 0.08 r3 installs successfully. I can see the driver is running using ``sc query npcap``. It should have two possible reasons. One is the condition 3. I have mentioned above. The other is the condition 2. I don't know if the VM has the secure boot feature? I went into the BIOS of the VM, but didn't find the secure boot option. So I think it's a None? My host has this feature enabled if I remembered it right. But will this feature pass on to the VMs? I'm not familiar with this virtualization details. I don't have another physical machine for me to install Win 10 1607, so I have to use a VM here.

**Comment by hsluoyz** [comment] 2016-08-09 15:18
A useful Q&A with Microsoft:
https://www.osr.com/blog/2015/07/24/questions-answers-windows-10-driver-signing/

Sysdev portal account sign up:
https://sysdev.microsoft.com/en-us/hardware/signup/

**Comment by zdm** [comment] 2016-08-09 16:25
I my case everything happens, like it described in the article.
I have clean windows installed and npcap driver is not loading.

**Comment by hsluoyz** [comment] 2016-08-09 16:29
@fyodor @bonsaiviking , does anyone have an available physical machine to install Win10 1607 to check this issue?

And @fyodor , can you register an account here: https://sysdev.microsoft.com/en-us/hardware/signup/ ? So we can log in to see what's going on there.

**Comment by marlop352** [comment] 2016-09-07 08:59
Any updates about the signing problem?

**Comment by hsluoyz** [comment] 2016-09-07 09:27
@marlop352 , not much progress, since this seems to require an EV certificate which is much more expensive than the one we have. For now, I suggest you turn off ``Secure Boot`` in your BIOS to workaround this issue.

**Comment by mhoes** [comment] 2016-09-24 11:49
For what it's worth: I had the same behavior (but perhaps not the exact same bug) as originally reported here: after a Windows 10 Home 64-bit update (from version 1511) to the 'Anniversary Update' (version 1607 [OS Build 14393.187]), Wireshark is no longer able to identify any interfaces. But I can't tell from the previous posts here if my issue was identical to the one reported here originally. I'm running Wireshark 2.2.0, and was running Npcap 0.09-r13 when I first ran into the issue. Npcap is installed in winpcap compatibility mode. 

The following resolved the issue for me:

1.) Go to the directory where npcap is installed, and uninstall by double clicking 'uninstall.exe'.
2.) Download and install npcap-0.10-r2 as usual.

**Comment by sanitybit** [comment] 2016-10-02 20:34
@hsluoyz If you have no intention of properly signing the drivers for current builds of Windows, you shouldn't include npcap as the default in stable nmap installers for Windows.

**Comment by hsluoyz** [comment] 2016-10-03 02:32
@sanitybit , besides the price, there's another difficulty. As you know, Npcap is open-sourced and developped in a distributed manner. But EV code signing only has one hardware key. It's hard for multiple developers at different places to do the signing concurrently.

Do you know any way to achieve EV code signing concurrently for multiple developers, like a remote signing or multiple identical hardware keys?

**Comment by BavoB** [comment] 2016-10-03 22:03
I have the same problem, no interfaces in Wireshark + Zenmap errors out with:

"Starting Nmap 7.30 ( https://nmap.org ) at 2016-10-03 23:56 Romance Daylight Time
NSE: Loaded 142 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 23:56
Completed NSE at 23:56, 0.00s elapsed
Initiating NSE at 23:56
Completed NSE at 23:56, 0.00s elapsed
Initiating ARP Ping Scan at 23:56
dnet: Failed to open device eth0
QUITTING!"

System: Windows 10 x64 1607 with Secure Boot on
Nmap: 7.30 release with Npcap 0.10 r5 (compatibility mode)
[DiagReport-20161003-235502.txt](https://github.com/nmap/nmap/files/507262/DiagReport-20161003-235502.txt)

Is this a signature problem? I noticed that when installing the latest Intel network driver, Windows complained about an unsigned driver, which was new to me. Do kernel drivers really need to be signed by an EV certificate in this version?

Thanks for any useful info.

**Comment by hsluoyz** [comment] 2016-10-04 03:49
@BavoB , did you install Win10 x64 1607 in a brand-new system or update to it? If brand-new, then it should be the signing issue. 

@fyodor @bonsaiviking , it seems that more users are complaining about this issue now..

**Comment by BavoB** [comment] 2016-10-06 14:12
This was a clean install on a new system.

**Comment by hsluoyz** [comment] 2016-10-06 14:14
Thanks for the feedback. We are already trying to solve this signing issue. For now, my suggestion would be turning off Secure Boot in the BIOS to bypass this check.

**Comment by dmiller-nmap** [comment] 2016-12-09 23:51
@BavoB @mhoes @marlop352 @zdm @sanitybit,

We have obtained an EV code signing certificate and are in the process of figuring out how to best accomplish the Dev Portal signing in such a way that it supports all versions of Windows from 7 through 10. Since you have each experienced problems with the driver signing issue, we are asking you to help us test a couple candidate builds of the latest Npcap 0.78 r2:

First, we have built [an installer with drivers signed directly by our EV cert](https://nmap.org/tmp/c/npcap-0.78-r2-ev.exe). This works on earlier versions of Windows, but we have not tested yet whether it works on Windows 10 1607, which is of course the primary problem. If this works for you on the Anniversary Update, we can begin shipping installers with this configuration right away.

If that should fail, we have [an installer with Microsoft Attestation-signed drivers](https://nmap.org/tmp/c/npcap-0.78-r2-attestation.exe). The drivers were cross-signed by Microsoft through the Dev Portal after we signed them with our EV cert, and will most likely work with Windows 10, any release. Unfortunately, the do NOT work with previous versions.

If the first installer (EV-only) works for Win10 1607, then we can be done. If only the second one (attestation signed) works, then we will have to multiply again the drivers we ship: SHA-1-signed for Win7, EV-signed for Win8, and attestation-signed for Win10.

Please let us know at your earliest convenience which of these installers works for you, if any.

**Comment by zdm** [comment] 2016-12-09 23:53
I am ready for testing.

**Comment by BavoB** [comment] 2016-12-10 01:10
Only the second one (attestation signed) works!

Thank you very much,
Bavo

**Comment by zdm** [comment] 2016-12-10 08:26
Win10 with secure boot enabled:
- npcap-0.78-r2-attestation.exe - works;
- npcap-0.78-r2-ev.exe - not installed, failed to create service during installation;

**Comment by mhoes** [comment] 2016-12-10 10:11
Hi,


With the installer with drivers signed directly by your EV cert
(npcap-0.78-r2-ev.exe), I got the following error twice during
installation: "Failed to install the npcap service". The installer did
march onwards to the end though, as if nothing bad had happened.

The installer with Microsoft Attestation-signed drivers
(npcap-0.78-r2-attestation.exe) works, and afterwards capture with
wireshark is possible.

Small note: During the uninstall of both of the above, the npcap loopback
adapter remained installed, leaving me after installing/uninstalling both
with two remaining npcap loopback adapters I had to uninstall manually
through windows device manager. Both that's probably for another day and
bug report.

**Comment by zdm** [comment] 2016-12-10 10:13
Yes, I can confirm, that Npcap loopback adapters are not uninstalled and
can be removed only from devices manager.

**Comment by hsluoyz** [comment] 2016-12-10 17:07
@mhoes @zdm , I have fixed this ``Npcap loopback adapters are not uninstalled`` issue in latest Npcap 0.78 r4. 

Please try the installer at: https://github.com/nmap/npcap/releases

**Comment by marlop352** [comment] 2016-12-10 18:32
0.78 r2-ev does not work(fails to create services)

0.78 r2-atestation works

with 0.78 r4 windows gives an error after installation saying that it blocked the installation of a driver not digitally signed

**Comment by hsluoyz** [comment] 2016-12-11 02:28
@marlop352 , Npcap 0.78 r4 still doesn't support Win10 1607 with Secure Boot on. Only the Microsoft Attestation-signed version Npcap released by Dan supports it. You can wait for Dan to release a 0.78 r4 version.

**Comment by marlop352** [comment] 2016-12-11 02:36
@hsluoyz thought so, reported it because the error was different from what I remember happening when using the normal installer

I don't know how you generate the installer of how this specific one works, but can't it have the two types of binaries(normal and attestation) and choose which to use by detecting what system it's been run from?

**Comment by BavoB** [comment] 2016-12-11 21:33
Hallo,

OK to recap: with secure boot on a fresh install of Win10 x64 v1607: only driver’s signed by EV cert of software vendor (you guys) + cross-signed by MS (attestation) will work. For kernel drivers this will probably always be the case going forward.

As I think running Win10 without secure boot is pointless, even more so in the near future (a lot of features seem to build on it), please make it straightforward to download the version we need + also when integrated into Nmap.
Probably for Nmap distribution it only makes sense to include the ‘attested’ version, as that would work on all systems, also downlevel (win8.1-win7): am I correct?

Finally another (small) related problem which I will mention for completeness sake: I also run Hyper-V (not sure if this fact is related, probably not) but if I install a new NPCAP version over the previous one - I never bother to uninstall manually - then each install adds a new LAN adapter: they are called Ethernet2, 3, 4 etc, but in the details tab of the properties “NPCAP Loopback Adapter” is mentioned in the description field.  This is probably the same (or very related) problem, in that the installer doesn’t do a cleanup as part of the new install, or else there is an uninstall routine included but it did not work. So the old adapters are renamed to Ethernet2, 3 etc, to make room for the ‘new’ one…

Best,
Bavo

**Comment by BavoB** [comment] 2016-12-11 21:41
1. FINAL REMARK: the adapters are called Ethernet2, 3, 4 in the ‘Network & sharing Center’ and ‘Network connections’ windows.
In device manager they are however all called identically “NPCAP Loopback Adapter” ==> they also have the same driver version 10.0.14393.0 ; so I don’t really know which one I can safely uninstall.
2. I’m getting marked as spam  by GitHub for some reason, but I’m legit (I swear ;-)
Best,
Bavo

===========================
Hallo,

OK to recap: with secure boot on a fresh install of Win10 x64 v1607: only driver’s signed by EV cert of software vendor (you guys) + cross-signed by MS (attestation) will work. For kernel drivers this will probably always be the case going forward.

As I think running Win10 without secure boot is pointless, even more so in the near future (a lot of features seem to build on it), please make it straightforward to download the version we need + also when integrated into Nmap.
Probably for Nmap distribution it only makes sense to include the ‘attested’ version, as that would work on all systems, also downlevel (win8.1-win7): am I correct?

Finally another (small) related problem which I will mention for completeness sake: I also run Hyper-V (not sure if this fact is related, probably not) but if I install a new NPCAP version over the previous one - I never bother to uninstall manually - then each install adds a new LAN adapter: they are called Ethernet2, 3, 4 etc, but in the details tab of the properties “NPCAP Loopback Adapter” is mentioned in the description field.  This is probably the same (or very related) problem, in that the installer doesn’t do a cleanup as part of the new install, or else there is an uninstall routine included but it did not work. So the old adapters are renamed to Ethernet2, 3 etc, to make room for the ‘new’ one…

Best,
Bavo

**Comment by dmiller-nmap** [comment] 2016-12-11 23:57
Everyone,

Sorry for the confusion. I had a misconfiguration that caused our EV-signed drivers to not validate, so they were not working on any system. Now they work on Windows 8 at least, and I would appreciate a test with Windows 10 1607. [Here is the download link for Npcap 0.78 r4, EV cert](https://nmap.org/tmp/c/npcap-0.78-r4-ev.exe).

**Comment by mhoes** [comment] 2016-12-12 08:13
Hi,


I can install npcap-0.78-r4-ev.exe without errors, and can capture traffic
after installation with Wireshark. I do get a Windows Security pop-up
though, asking me 'Would you like to install this device software ?", with
an option to 'Always trust software from Insecure.Com LLC". Also, the npcap
loopback adapter now does get removed when uninstalling npcap.

Running Windows Home 64-bit Version 1607 (OS Build 14393.479), secure boot
enabled in my UEFI firmware, and I did an upgrade from Windows 7 to Windows
10, not a clean install.

**Comment by BavoB** [comment] 2016-12-13 13:21
@ mhoes: which probably proves the point. For Win10 1607 with secure boot enabled (freshly installed, but as your experience shows even for upgrades depending on who knows what) you need attestation, no way around it.

**Comment by BavoB** [comment] 2016-12-13 13:31
![npcap 0 78 r4 beta ev version](https://cloud.githubusercontent.com/assets/3685233/21141912/f277ca8c-c13f-11e6-9a68-0d526363ee89.png)
For completeness sake: this is the EV version installed on Windows 2012 R2 (server) - UEFI with secure boot. So AFAIK the attestation is also needed here or else there is still something else wrong.
I got the Windows Security pop-up 'Would you like to install this device software ?", to which I answered 'no' (do not always trust Insecure LLC).

**Comment by mhoes** [comment] 2016-12-13 14:52
@BavoB: Perhaps I understand you incorrectly (or you incorrectly understood
me), but I said that I *can* install pcap-0.78-r4-ev.exe (I thought that
this was a EV-signed driver, and not the attestation-signed drivers)
without errors; in other words, that it *does* work for me.

**Comment by BavoB** [comment] 2016-12-13 15:48
Oops sorry my bad.

**Comment by hsluoyz** [comment] 2016-12-13 15:53
@BavoB 

> I got the Windows Security pop-up 'Would you like to install this device software ?", to which I answered 'no' 

If you choose ``no`` here, then you will always fail the driver install no matter how our driver is signed. So please choose ``yes``.

**Comment by BavoB** [comment] 2016-12-13 15:57
OK, although (our) best practices state the opposite ;-).

**Comment by mhoes** [comment] 2016-12-13 16:31
It appears to me as if two things are getting mixed up here, but I may be wrong ? (I made a screenshot of the pop-up I get, yours may be different). In the pop-up, there are actually two related, but different, things. First of all, there is a 'checkbox' that you can check if you *always* want to trust drivers singed by "Insecure.Com LLC". You don't have to check that box, but you can. I'm guessing that if you do check the box to always trust the signer that you will never get this pop-up again, and that you will get the pop-up again if you don't.

Then there are the 'install' and 'dont install' buttons. If you want to install the driver (and I'm guessing that you want to) then you *must* click the button that says 'install'. If you haven't checked the checkbox in combination with clicking on 'install', you will only trust the signer *once*, for this install only, instead of always.

![pop-up](https://cloud.githubusercontent.com/assets/14194483/21148856/e33a415c-c159-11e6-94aa-1b8e1749d6fd.jpg)

**Comment by marlop352** [comment] 2016-12-13 21:25
> **0.78 r2-ev** does not work(fails to create services)
> **0.78 r2-atestation** works
> with **0.78 r4** windows gives an error after installation saying that it blocked the installation of a driver not digitally signed

**0.78 r4-ev** still gives me the same error as **0.78 r4** even if I mark the always trust box(witch does not appear on **0.78 r4**) (checking that box should have made it accept the driver I think)

Windows 10 1607 (it's a clean install, not an update from a previous version) with secure boot enabled

**Comment by dmiller-nmap** [comment] 2016-12-15 18:05
Ok, all: I just published [Npcap 0.78 r5](https://github.com/nmap/npcap/releases/tag/v0.78-r5), which has attestation-signed drivers for Win10 users, dual-signed SHA1/SHA256 drivers with MS Cross-Certs for Windows 8 and earlier. We are back in business! Do let us know if you still experience these problems.

**Comment by BavoB** [comment] 2016-12-15 22:16
Hi,

Everything seems to work as expected (Win10 x64 1607 fresh install with secure boot on).

Thanks,
Bavo

**Comment by mhoes** [comment] 2016-12-16 17:29
Hi,


WORKSFORME: Win10 x64 1607, upgrade from Win7, secure boot on. No pup-ups
during installation asking for permission. Wireshark able to capture
packets as expected. Note: Npcap loopback adapter doesn't get uninstalled
upon npcap uninstall.

**Comment by BavoB** [comment] 2016-12-20 12:21
OK, I had a chance to uninstall 0.78 r4 on a Window Win2012 R2 server + install 0.78 r5 (system with secure boot enabled). My findings, some of which have been reported before:
- uninstalling took very long and didn't remove the adapters (which I removed manually), but eventually it did uninstall - it seemed to be stuck on the 'stopping npcap driver' stage
- installing 0.78 r5 worked, but I did get the 'failed to create service' error: however after installing it seemed to work ==> i did not have winpcap installed on this system, I installed npcap in winpcap api compatible mode and the programs relying on winpcap seemed to be working normally

So I guess there is some progress ;-)

Questions:
1. what services are crated, what is their name? (I'd like to check in services msc to see if it is running)
2. are the uninstall problems also related to the (kernel) driver signing requirements/problems ==> although here I'm not running on Win10 based system
3. what is the current status of npcap compared to winpcap: can this be run safely with a program like Wireshark (without Winpcap)?

**Comment by mhoes** [comment] 2016-12-20 17:40
Hrm.

On Tue, Dec 20, 2016 at 1:21 PM, BavoB <notifications@github.com> wrote:

> installing 0.78 r5 worked, but I did get the 'failed to create service'
> error

If you got a pop-up (not sure), did you remember to click on the 'install'
button this time instead of 'dont install' like you did last time ?

**Comment by dmiller-nmap** [comment] 2017-01-19 14:39
Looks like we handled the core issue reported here. If you continue to have problems with uninstalling, please open a new issue so we can track and fix it. Thanks!

**Closed by dmiller-nmap** 2017-01-19 14:39 UTC
Labels: bug, Npcap
