### ISSUE TITLE
I would like to know how to uninstall this malware WITHOUT A BSOD

### ISSUE THREAD

**Issue by CoolStuff08** [nmap/nmap#1636] opened 2019-06-14 19:06 UTC
It seems like you ass developers made npcap 0.995 as unstable as you possibly could. You probably did this just to affect every wireshark user out there. NOW ANSWER MY QUESTION IN THE TITLE WITHOUT GIVING A BULLSHIT RESPONSE. And don’t just say “well stop the driver with sc.exe” well fuck you if you do, it just spits out the sc help instead of disabling anything. And dont say nobody else has this either. If you check the closed issues many people have this, and they also get bullshit responses.

**Comment by bzeitlin** [comment] 2019-06-14 19:14
I had the same issue, had to boot in diagnostics mode and troubleshoot. I tried to reinstall wireshark and had the same issue. Same solution, boot to diagnostics mode, troubleshoot, and it gave me an option to revert to a previous image. 

I had the exact same issue, trying to disable or uninstall the issue gave me BSOD.

**Comment by dmiller-nmap** [comment] 2019-06-15 19:26
This issue has been previously reported, and is resolved in Npcap 0.996, released today. https://npcap.org/#download

Because Npcap 0.995 consistently crashes some systems, the Npcap 0.996 installer will offer to disable the `npcap` driver service on the next boot so that the installation can be reattempted. You can also manually disable it by running (as administrator) `sc.exe config npcap start= disabled`. There may be one more crash when trying to restart, unfortunately, but it will be the last one.

**Comment by dmiller-nmap** [comment] 2019-06-15 19:28
Duplicate of #1626

**Closed by dmiller-nmap** 2019-06-15 19:28 UTC
Labels: Npcap, bug, duplicate
