### ISSUE TITLE
Always getting a zsh: segmentation fault when running nmap

### ISSUE THREAD

**Issue by hadaoud** [nmap/nmap#2518] opened 2022-09-05 00:33 UTC
before the problem was that every time i run nmap it either don't find any open ports , or it gives me filtered port (i know they are open) with a `zsh: segmentation fault <ip> `
so i reinstall it now it works yet still giving me segfault whenever i run it with most flags , some flags don't give me the segfault
os : Kali GNU/Linux Rolling x86_64

**Comment by byinarie** [comment] 2022-09-06 04:08
I am also having this error.

```
┌──(root㉿kali)-[~]
└─# uname -a
Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
```

Syslog output:

```
┌──(root㉿kali)-[~]
└─# cat /var/log/syslog |grep nmap
Sep  6 00:04:39 kali kernel: [15878.371923] nmap[68894]: segfault at 18 ip 00007f59e748d390 sp 00007fff54c648d8 error 4 in libc.so.6[7f59e7428000+16e000]
****
```

**Comment by byinarie** [comment] 2022-09-06 04:11
This might be a zsh issue within Kali not an nmap issue, switching to /bin/bash it no longer throws a seg fault.

```
┌──(root㉿kali)-[~]
└─# /bin/bash
┌──(root㉿kali)-[~]
└─# nmap 10.129.53.x
Starting Nmap 7.92 ( https://nmap.org ) at 2022-09-06 00:10 EDT
Nmap scan report for 10.129.53.x
Host is up (0.032s latency).
Not shown: 998 closed tcp ports (reset)
PORT   STATE SERVICE
22/tcp open  ssh
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 0.75 seconds
```

No error in syslog either.

**Comment by hadaoud** [comment] 2022-09-06 15:35
> This might be a zsh issue within Kali not an nmap issue, switching to /bin/bash it no longer throws a seg fault.
> 
> ```
> ┌──(root㉿kali)-[~]
> └─# /bin/bash
> ┌──(root㉿kali)-[~]
> └─# nmap 10.129.53.x
> Starting Nmap 7.92 ( https://nmap.org ) at 2022-09-06 00:10 EDT
> Nmap scan report for 10.129.53.x
> Host is up (0.032s latency).
> Not shown: 998 closed tcp ports (reset)
> PORT   STATE SERVICE
> 22/tcp open  ssh
> 80/tcp open  http
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.75 seconds
> ```
> 
> No error in syslog either.

still getting it even with bash 
![image](https://user-images.githubusercontent.com/94515356/188676577-4749f4cc-809d-4d34-9ae1-d58e0082ac48.png)
yet with zsh it gave me all ports as filtered again until i used bash

**Comment by dmiller-nmap** [comment] 2022-09-06 17:08
Maybe related to #2482. Please include output of `nmap --version` and try Nmap 7.93.

**Comment by pizzarabe** [comment] 2022-09-15 13:30
Have the same Problem with the current Kali release 
`
Linux kali 5.18.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1kali1 (2022-08-31) x86_64 GNU/Linux`

It seems to be related to the use of NSE scripts.

```
nmap -Pn --script smb-brute.nse -p445 127.0.0.1 
Starting Nmap 7.92 ( https://nmap.org ) at 2022-09-15 15:28 CEST
[...]
PORT    STATE  SERVICE
445/tcp closed microsoft-ds

Nmap done: 1 IP address (1 host up) scanned in 0.20 seconds
zsh: segmentation fault  nmap -Pn --script smb-brute.nse -p445 127.0.0.1
```

```
nmap -Pn -p445 127.0.0.1 
Starting Nmap 7.92 ( https://nmap.org ) at 2022-09-15 15:28 CEST
[...]

PORT    STATE  SERVICE
445/tcp closed microsoft-ds

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
```

A new compiled 7.93 does not have this problem.

**Comment by RyenNelsen** [comment] 2022-09-19 15:43
Same results as @pizzarabe. It only segfaults when NSE is enabled. The issue does not occur when building from source using version `7.93`. 
```
Linux kali 5.18.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1kali1 (2022-08-31) x86_64 GNU/Linux
```
```
nmap -A -T4 -p- 127.0.0.1
Starting Nmap 7.92 ( https://nmap.org ) at 2022-09-19 08:31 PDT
[...]

Nmap done: 1 IP address (1 host up) scanned in 56.71 seconds
zsh: segmentation fault  /usr/bin/nmap -A -T4 -p- 127.0.0.1
```

```
nmap -A -T4 -p- 127.0.0.1
Starting Nmap 7.93SVN ( https://nmap.org ) at 2022-09-19 08:21 PDT
[...]

Nmap done: 1 IP address (1 host up) scanned in 57.12 seconds
```

**Comment by dmiller-nmap** [comment] 2022-09-23 17:53
This is a duplicate of #2482.

**Closed by dmiller-nmap** 2022-09-23 17:53 UTC
Labels: Nmap

**Comment by Jamesmarino1** [comment] 2022-09-24 14:08
i have the same problem!! i can't run nmap on my own pc whatsoever, i can with ctfs but when it comes to my pc i get no results on any ports or any information at all.

**Comment by PiezPiedPy** [comment] 2022-09-29 00:12
Version 7.93 fixed it for me

**Comment by zoutre** [comment] 2022-09-29 16:09
How to get version 7.93 ? 
Running 'apt-get update' && 'apt-get install -y nmap' on Kali does not update to this version.

**Comment by swetangkrishna** [comment] 2022-10-10 01:48
> before the problem was that every time i run nmap it either don't find any open ports , or it gives me filtered port (i know they are open) with a `zsh: segmentation fault <ip> ` so i reinstall it now it works yet still giving me segfault whenever i run it with most flags , some flags don't give me the segfault os : Kali GNU/Linux Rolling x86_64


hi i am facing the same issue, could you please let me know the solution to this problem.

**Comment by sgiruyarsb** [comment] 2022-10-18 09:57
> This is a duplicate of #2482.

i have some problem. I installed lastest new version, but i can't use nmap.
I run any nmap command and return the following"

Nmap version 7.93 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.5 libssh2-1.10.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Comment by sgiruyarsb** [comment] 2022-10-19 06:54
> > This is a duplicate of #2482.
> 
> i have some problem. I installed lastest new version, but i can't use nmap. I run kali-linux on my VMware I run any nmap command and return the following:
> 
> Nmap version 7.93 ( https://nmap.org ) Platform: x86_64-pc-linux-gnu Compiled with: liblua-5.3.6 openssl-3.0.5 libssh2-1.10.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6 Compiled without: Available nsock engines: epoll poll select

yah, i solved my issue. The way to solve it lies in the exact command.
I use V uppercase, not working. But i use v normal, it works
