### ISSUE TITLE
"Npcap Loopback Adapter doesn't have a valid IP configuration" Disabled WiFi

### ISSUE THREAD

**Issue by CoriDavis** [nmap/nmap#592] opened 2016-11-19 03:01 UTC
I believe I downloaded Npcap alongside GNS3 or Wireshark. A few days after downloading, Npcap has suddenly taken over my WiFi adapter and I am no longer able to connect through WiFi.

**More details are listed here, as I was forwarded here from another forum:**
http://www.techsupportforum.com/forums/f31/npcap-loopback-adapter-doesnt-have-a-valid-ip-configuration-wireless-out-1167745.html

**Logs from Windows' network troubleshooter:**

> "Npcap Loopback Adapter" doesn't have a valid IP configuration - Not Fixed 
> Investigate router or broadband modem issues - Failed 
> Reset the "Npcap Loopback Adapter" adapter - Completed 
> 
> 
> Network adapter Npcap Loopback Adapter driver information:
> 
> Description . . . . . . . . . . : Microsoft KM-TEST Loopback Adapter
> Manufacturer . . . . . . . . . : Microsoft
> Provider . . . . . . . . . . . : Microsoft
> Version . . . . . . . . . . . : 10.0.14393.0
> Inf File Name . . . . . . . . . : C:\WINDOWS\INF\netloop.inf
> Inf File Date . . . . . . . . . : Saturday, July 16, 2016 11:41:53 AM
> Section Name . . . . . . . . . : kmloop.ndi
> Hardware ID . . . . . . . . . . : *msloop
> Instance Status Flags . . . . . : 0x180200b
> Device Manager Status Code . . : 0
> IfType . . . . . . . . . . . . : 6
> Physical Media Type . . . . . . : 0

**Results of "ipconfig /all":**

> C:\Users\Cori>ipconfig /all
> 
> Windows IP Configuration
> 
> Host Name . . . . . . . . . . . . : Cori
> Primary Dns Suffix . . . . . . . :
> Node Type . . . . . . . . . . . . : Hybrid
> IP Routing Enabled. . . . . . . . : No
> WINS Proxy Enabled. . . . . . . . : No
> 
> Ethernet adapter Npcap Loopback Adapter:
> 
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : Npcap Loopback Adapter
> Physical Address. . . . . . . . . : 02-00-4C-4F-4F-50
> DHCP Enabled. . . . . . . . . . . : Yes
> Autoconfiguration Enabled . . . . : Yes
> Link-local IPv6 Address . . . . . : fe80::edfe:832d:1971:9744%17(Preferred)
> Autoconfiguration IPv4 Address. . : 169.254.151.68(Preferred)
> Subnet Mask . . . . . . . . . . . : 255.255.0.0
> Default Gateway . . . . . . . . . :
> DHCPv6 IAID . . . . . . . . . . . : 637665356
> DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-88-F8-CB-5C-B9-01-7E-55-B1
> DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
> fec0:0:0:ffff::2%1
> fec0:0:0:ffff::3%1
> NetBIOS over Tcpip. . . . . . . . : Enabled
> 
> Wireless LAN adapter Local Area Connection* 3:
> 
> Media State . . . . . . . . . . . : Media disconnected
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
> Physical Address. . . . . . . . . : AE-D1-B8-3F-7B-3E
> DHCP Enabled. . . . . . . . . . . : Yes
> Autoconfiguration Enabled . . . . : Yes
> 
> Ethernet adapter Ethernet:
> 
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : Realtek PCIe FE Family Controller
> Physical Address. . . . . . . . . : 5C-B9-01-7E-55-B1
> DHCP Enabled. . . . . . . . . . . : Yes
> Autoconfiguration Enabled . . . . : Yes
> Link-local IPv6 Address . . . . . : fe80::c90:55bb:d20d:567b%23(Preferred)
> IPv4 Address. . . . . . . . . . . : 192.168.1.8(Preferred)
> Subnet Mask . . . . . . . . . . . : 255.255.255.0
> Lease Obtained. . . . . . . . . . : Thursday, November 17, 2016 5:02:34 PM
> Lease Expires . . . . . . . . . . : Friday, November 18, 2016 5:11:50 PM
> Default Gateway . . . . . . . . . : 192.168.1.1
> DHCP Server . . . . . . . . . . . : 192.168.1.1
> DHCPv6 IAID . . . . . . . . . . . : 56408321
> DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-88-F8-CB-5C-B9-01-7E-55-B1
> DNS Servers . . . . . . . . . . . : 192.168.1.1
> NetBIOS over Tcpip. . . . . . . . : Enabled
> 
> Ethernet adapter Ethernet 3:
> 
> Media State . . . . . . . . . . . : Media disconnected
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : TAP-Windows Adapter V9
> Physical Address. . . . . . . . . : 00-FF-25-A6-EC-B5
> DHCP Enabled. . . . . . . . . . . : Yes
> Autoconfiguration Enabled . . . . : Yes
> 
> Wireless LAN adapter Wi-Fi:
> 
> Media State . . . . . . . . . . . : Media disconnected
> Connection-specific DNS Suffix . : hh.nku.edu
> Description . . . . . . . . . . . : Realtek RTL8188EE 802.11 b/g/n Wi-Fi Adapter
> Physical Address. . . . . . . . . : AC-D1-B8-3F-7B-3E
> DHCP Enabled. . . . . . . . . . . : Yes
> Autoconfiguration Enabled . . . . : Yes
> 
> Tunnel adapter isatap.{92DDA6C4-89CA-43B1-AB38-22077539E233}:
> 
> Media State . . . . . . . . . . . : Media disconnected
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : Microsoft ISATAP Adapter #2
> Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
> DHCP Enabled. . . . . . . . . . . : No
> Autoconfiguration Enabled . . . . : Yes
> 
> Tunnel adapter isatap.{F5E2FA16-FC72-4FC0-A826-8CE343059E90}:
> 
> Media State . . . . . . . . . . . : Media disconnected
> Connection-specific DNS Suffix . :
> Description . . . . . . . . . . . : Microsoft ISATAP Adapter #4
> Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
> DHCP Enabled. . . . . . . . . . . : No
> Autoconfiguration Enabled . . . . : Yes

![image](https://cloud.githubusercontent.com/assets/23565956/20452552/6d98fe44-adda-11e6-8d54-e7a39b36d410.png)

**Comment by hsluoyz** [comment] 2016-11-19 03:07
Hi @CoriDavis  , please provide 3 files based on [docs here](https://github.com/nmap/npcap#bug-report):
1. Diagnostic report (DiagReport)
2. install.log
3. NPFInstall.log

You can upload them to this GitHub conversation.

**Comment by CoriDavis** [comment] 2016-11-19 03:37
I checked my C:\Program Files\Npcap folder, and I don't see any of those files, or the DiagReport.bat. Hidden items are visible.

![image](https://cloud.githubusercontent.com/assets/23565956/20452746/5b6938c4-addf-11e6-9322-7a63d13533d6.png)

I was able to solve the problem by disabling the Npcap Loopback Adapter shown in my Active Networks. My WiFi was available again after restarting my computer.

**Comment by hsluoyz** [comment] 2016-11-19 03:50
@CoriDavis , so you are using a very old Npcap version, which probably has bugs that causes your issue.

Please install the latest Npcap 0.10 r18 version here: https://github.com/nmap/npcap/releases to see if the issue is fixed.

**Comment by CoriDavis** [comment] 2016-11-19 03:56
Oh wow, yep I sure was. It seems what I had was 0.07 (beta).

The class I'm taking that requires GNS and Wireshark is a class I had taken last year and failed. I never did update Wireshark, so that probably explains why Npcap was never updated either.

**Comment by hsluoyz** [comment] 2016-11-19 04:06
> Oh wow, yep I sure was. It seems what I had was 0.07 (beta).

So did latest version Npcap solve your issue?

> The class I'm taking that requires GNS and Wireshark is a class I had taken last year and failed. I never did update Wireshark, so that probably explains why Npcap was never updated either.

Actually, Wireshark doesn't carry a Npcap installer, it only detects whether there's a Npcap already installed. GNS3 carries a old version Npcap. So the best way to use latest Npcap is to download it from our [official Release page](https://github.com/nmap/npcap/releases).

**Comment by hsluoyz** [comment] 2016-11-19 08:00
I assume this issue has been fixed, and will close it for now.

**Comment by dmiller-nmap** [comment] 2016-11-21 14:12
@CoriDavis Since you didn't have those files, you probably have an older version of Npcap installed. We have solved a similar problem to yours at #373, so upgrading to the latest Npcap will probably solve your problem without the need to disable the Npcap Loopback Adapter.

**Comment by McGuywer** [comment] 2016-11-22 12:34
Good Day,

I have the same issue using Npcap 0.11 (https://github.com/nmap/npcap/releases/download/v0.11/npcap-0.11.exe)

It is only the wireless adapter that is affected.

[DiagReport-20161122-143252.txt](https://github.com/nmap/nmap/files/606325/DiagReport-20161122-143252.txt)


When uploading the *.log files, I get an error:
"We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by McGuywer** [comment] 2016-11-22 12:35
Here are the files attached as .txt files.

[install.txt](https://github.com/nmap/nmap/files/606328/install.txt)
[NPFInstall.txt](https://github.com/nmap/nmap/files/606329/NPFInstall.txt)

**Comment by hsluoyz** [comment] 2016-11-22 13:35
Hi @McGuywer ,

I noticed that you have installed VirtualBox. Somebody has reported the similar problem that ``fail to get IP address via DHCP`` here: https://github.com/nmap/nmap/issues/584#issuecomment-261773029. 

He disabled the VirtualBox driver and fixed it. Can you try his method?

**Comment by hsluoyz** [comment] 2016-11-22 13:37
Hi @dmiller-nmap , I don't think his issue is related to #373. #373 tries to solve the no connectivity issue. However, this one is about no IP under DHCP.

**Comment by CoriDavis** [comment] 2016-11-22 14:34
Update:

I restarted my computer today. Even though I have the latest version now, the problem has returned. Now that I have the files, here they are:

[DiagReport-20161122-093102.txt](https://github.com/nmap/nmap/files/606639/DiagReport-20161122-093102.txt)
[install-log.txt](https://github.com/nmap/nmap/files/606649/install-log.txt)
[NPFInstall-log.txt](https://github.com/nmap/nmap/files/606650/NPFInstall-log.txt)

**Comment by hsluoyz** [comment] 2016-11-22 16:43
@CoriDavis , it's weird that your Wi-Fi connection would be affected by ``Npcap Loopback Adapter``, which is another network adapter. I never see this condition before.

I noticed that you have installed a possible conflicting software: ``Cisco AnyConnect VPN`` (see [here](https://rawgit.com/nmap/npcap/master/docs/npcap-guide-wrapper.html#npcap-incompatible) for details). And you seem to have also installed ``WinPcap``. Could you uninstall them and try to install Npcap again to see if the issue is fixed?

If this doesn't help you, you can just install Npcap without selecting the 2nd option: ``Support loopback traffic ("Npcap Loopback Adapter" will be created)``. So ``Npcap Loopback Adapter`` will not be installed.

**Comment by McGuywer** [comment] 2016-11-23 10:39
Will install without 
> Support loopback traffic ("Npcap Loopback Adapter" will be created)
Will let you know how it goes.

**Comment by temp-defualt** [comment] 2016-11-25 00:12
I have many systems installed with npcap and im getting feed back that on WIN 7 (mostly pro 64 bit) after installation the wifi does not work 
so this happens and quiet frequently can I do something (already have the latest version) ?

tnx

**Comment by hsluoyz** [comment] 2016-12-10 17:09
Since there's no feedback for more than two weeks. I assume this issue has been fixed, and will close it for now.

**Closed by hsluoyz** 2016-12-10 17:09 UTC
Labels: bug, Npcap

**Comment by tonytranupc** [comment] 2017-04-24 10:13
Have you guys tried this one?

[Fix Ethernet Doesn't Have A Valid IP Configuration Error In Windows](https://usefulpcguide.com/18773/fix-ethernet-doesnt-have-a-valid-ip-configuration-error-in-windows/)

**Comment by McGuywer** [comment] 2017-04-24 12:23
Hi Tony,

Thank you for the suggestion, it did not work.
I have tried all the steps except manually configuring the IP address.

I am going to uninstall nmap again.


Regards,
Hannes Jooste
082 303 2694

**Comment by SiAlBe** [comment] 2017-11-25 21:39
hello i had the same probleme so i went and unchecked this

![capture](https://user-images.githubusercontent.com/33990199/33235043-e6d02c80-d230-11e7-9547-fdef9ef563e4.PNG)

then i unchecked these and confirmed, after that i checked them again.
![capture1](https://user-images.githubusercontent.com/33990199/33235080-61632c86-d231-11e7-8d23-20a071547a0c.PNG)
 now it works just fine for me.
i hope this was helpful good luck

**Comment by Lrapava** [comment] 2019-04-19 19:09
I believe I have the latest version of Npcap, but I can't connect to wifi. Please help me. I found the only way connecting to internet: I took my phone, enabled "Personal Hotspot" and then connected the phone with USB cable to my pc. It works, but... I want to be able to connect to wifi.

**Comment by dmiller-nmap** [comment] 2019-04-22 20:10
This issue is long out-of-date and closed. If you are experiencing problems with the latest version of Npcap, please open a new issue or comment on an existing open issue that exactly describes your problem.
