### ISSUE TITLE
ncat infinite loop on verify self signed certificate

### ISSUE THREAD

**Issue by slavkoja** [nmap/nmap#1704] opened 2019-08-21 09:37 UTC
Hi

On playing with ncat's ``--ssl-verify`` i found a problem with self-signed certificate verification -- the verification fails with message about self signed cert, but ``ncat`` itself doesn't exits and continue with connection attempts in infinite loop (i killed it in finited time, of course).

To demonstrate the problem i setup openssl's test TLS server with Debian's snake oil certificate:
``` 
openssl s_server -accept 666 -cert /etc/ssl/certs/ssl-cert-snakeoil.pem -key /etc/ssl/privat
e/ssl-cert-snakeoil.key
Using default temp DH parameters
ACCEPT
```
And then i try to connect to it with ``ncat`` with certificate verification enabled (i use short excerpt for demonstration):
```
ncat -vz --ssl-verify servac.slavino.sk 666
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Subject: CN=servac
Ncat: Issuer: CN=servac
Ncat: SHA-1 fingerprint: 5A4C 6610 0639 96B0 E7E4 8257 8864 EE1C 72EA 3173
Ncat: Certificate verification failed (self signed certificate).
Ncat: Subject: CN=servac
Ncat: Issuer: CN=servac
Ncat: SHA-1 fingerprint: 5A4C 6610 0639 96B0 E7E4 8257 8864 EE1C 72EA 3173
Ncat: Certificate verification failed (self signed certificate).
Ncat: Subject: CN=servac
Ncat: Issuer: CN=servac
Ncat: SHA-1 fingerprint: 5A4C 6610 0639 96B0 E7E4 8257 8864 EE1C 72EA 3173
Ncat: Certificate verification failed (self signed certificate).
...etc
```
Result is the same with or without ``-z`` option. I would expect, that ``ncat`` exits after first failed attempt.

regards

**Comment by nnposter** [comment] 2020-07-22 03:50
This issue appears to be a duplicate of #1488, which has been resolved in r37860 (b1d39d00d4ca3ae102cfe92f30a51e78bbaac7d7)

I have not been able to recreate the issue with Ncat compiled fresh from the source code so I am tentatively closing the issue. Please reopen if the issue persists.

**Closed by nnposter** 2020-07-22 03:50 UTC
Labels: Nsock, bug, duplicate
