### ISSUE TITLE
Error While scanning

### ISSUE THREAD

**Issue by MrDoel** [nmap/nmap#160] opened 2015-06-15 02:51 UTC
When i try to random scanning, I got this error : 
nmap: scan_engine_raw.cc:206: u16 UltraProbe::icmpid() const: Assertion `mypspec.proto == IPPROTO_ICMP || mypspec.proto == IPPROTO_ICMPV6' failed.

**Comment by dmiller-nmap** [comment] 2015-06-15 03:33
Duplicate of #154

**Closed by dmiller-nmap** 2015-06-15 03:33 UTC
Labels: duplicate
