### ISSUE TITLE
Npcap 0.99-r8 BSoD sendcap.c

### ISSUE THREAD

**Issue by PiAil** [nmap/nmap#1440] opened 2019-01-22 08:34 UTC
I was trying the Npcap SDK (last version) and got a BSoD with the `pcap_sendqueue_transmit` function.
I packaged the `sendcap.c` main provided in `Examples-remote` as a dll, and used it with `ctypes` in a Python loop. 
I tried with different `pcap` filesize (1 Mo, 10 Mo, 100 Mo) and it seems that the biggest the file is, the fastest the BSoD appears. With small filesize, it seems that there is no problem, and I can see my packets on the network.

Some `minidumps` : 
[012119-11203-01.zip](https://github.com/nmap/nmap/files/2781872/012119-11203-01.zip)
[012119-11218-01.zip](https://github.com/nmap/nmap/files/2781873/012119-11218-01.zip)
[012119-11281-01.zip](https://github.com/nmap/nmap/files/2781874/012119-11281-01.zip)
[012119-11390-01.zip](https://github.com/nmap/nmap/files/2781875/012119-11390-01.zip)

I don't know what additional information is needed, but feel free to ask any.

Edit: Oups I haven't done my homework, didn't see the issue #1398 that looks like the same.

**Comment by dmiller-nmap** [comment] 2019-01-22 15:14
Thanks for the valuable info! Yes, this seems to be a duplicate of #1398, so I'm closing as such. But your dump files will be very helpful in getting this fixed. Thanks!

**Closed by dmiller-nmap** 2019-01-22 15:14 UTC
