### ISSUE TITLE
nPcap.9991 BROKEN

### ISSUE THREAD

**Issue by andrewturnbull2** [nmap/nmap#2045] opened 2020-05-13 13:11 UTC
Hi,

I have an app that runs in winPcap compatability mode. With version .9990 it works perfectly. With .9991 pcap_next_ex seems to always return 1 and an empty packet which looks to be full of zeros.

I call pcap_open with a timeout of 15ms, then pcap_compile_nopcap to compile the filter followed by pcap_setfilter then pcap_freecode

I then call pcap_setbuff to set the buffer 32meg then pcap_setmintocopy with a value of 50.

In pcap_setfilter I also set snapLen to 50

I then enter a never ending loop calling pcap_next_ex

No errors are ever returned just a flood of empty packets. As I said older versions work perfectly.

**Comment by dmiller-nmap** [comment] 2020-05-13 16:51
This is a duplicate of #2037. Please try the workarounds in this comment: https://github.com/nmap/nmap/issues/2037#issuecomment-627712455

**Closed by dmiller-nmap** 2020-05-13 16:51 UTC

**Comment by dmiller-nmap** [comment] 2020-05-13 19:52
In your case, reorder the calls to pcap_setbuff and pcap_setfilter.

**Comment by goarblt** [comment] 2022-04-11 15:12
hello
https://www.evil.com/
