### ISSUE TITLE
Nmap 7.70: NSE Output incorrect when scanning virtual hosts

### ISSUE THREAD

**Issue by vogan** [nmap/nmap#1219] opened 2018-05-18 09:54 UTC
When I use Nmap 7.70 to scan multiple virtual hosts on the same machine (e.g. `www.example.org` and `example.org`, both resolving to the same IP address), the NSE output is assigned to the last target with the same IP address instead of the individual target scanned using its domain name.

The problem can be triggered using the command `nmap -p 443 --script ssl-enum-ciphers vhost1.example.org vhost2.example.org`, if both names resolve to the same IP address. Please see the attached file as a reference: Issuing the command on **Nmap 7.70** shows the output of `ssl-enum-ciphers` for both hosts in result section of the last target, so twice in this case. No output is displayed for the first target. Using **Nmap 7.60**, however, the result is as expected. The output of `ssl-enum-ciphers` is shown in each target result section.

[nmap_script_bug.txt](https://github.com/nmap/nmap/files/2016322/nmap_script_bug.txt)

Note: output is truncated, Nmap 7.70 has been started with `-sV`. This doesn't make a difference regarding the NSE output.

**Comment by dmiller-nmap** [comment] 2018-05-29 00:30
Duplicate of #581. Thanks for reporting!

**Closed by dmiller-nmap** 2018-05-29 00:30 UTC
Labels: duplicate

**Comment by vogan** [comment] 2018-06-05 11:55
I'm not really sure if this is an exact duplicate of #581. That bug has the same domain/ip in the targets list multiple times. In this case, we have different virtual hosts, however, on the same IP. While portscan results should be identical, results captured via NSE scripts using SNI might be different. In given example above, ssl-enum-ciphers outputs the same ciphers. My problem is, in a case where outputs are different (e.g. different certificates, different cipher suites,...), how should I find which output belongs to which vhost, when all results are being dumped in the same section? Currently, my only solution is to start nmap multiple times in order to get accurate results.
