### ISSUE TITLE
Copy and Paste with Zenmap

### ISSUE THREAD

**Issue by mtbike61384** [nmap/nmap#1268] opened 2018-07-10 18:01 UTC
You are not able to copy and paste outside of Zenmap when trying to copy IP addresses and or Service or Version information. Issue is with Zenmap 7.6 and 7.7 on Windows 10 and Windows 2008.

**Comment by dmiller-nmap** [comment] 2018-07-11 21:28
Thanks for the report! This has happened before due to an incorrect version of pygtk on our build system (#293), but I was not aware that any such problem had occurred again. I can't reproduce it here with Zenmap 7.70 on Windows 10. Please answer a few questions so we can better diagnose what is wrong:

1. Can you copy from the output window and paste into the Target or Command box?
2. Can you copy from Notepad and paste into Zenmap (either in the Target or Command box)?
3. Do you have a copy of GTK installed apart from installing Zenmap?

Thanks!

**Comment by mtbike61384** [comment] 2018-07-12 20:05
Thanks for the reply. Zenmap 7.6 on Windows 10 build 1709.
1. No. Highlighting anything in the hosts or output window and ctrl-c then ctrl-p into the Target and or command window fails. Right click in the output or hosts area does not bring up copy like it does in the target or command field. 
2. Yes
3. Not anything that I have installed intentionally. But we are on corporate boxes so they may have put something on it.

**Comment by mtbike61384** [comment] 2018-08-20 20:14
Hello. Any update on this bug or are you able to duplicate?

**Comment by mtbike61384** [comment] 2018-10-12 18:59
To further test I also used Zenmap 7.70 installed on Kali and you also cannot copy IP addresses and or Service or Version information. Asked around and I have not found anyone that can copy those items. Only items like the Target, Profile, and Command allow copy.

**Comment by dmiller-nmap** [comment] 2019-01-24 19:21
Not related to #293. Need to see whether these elements can be modified to support clipboard operations.

**Comment by mtbike61384** [comment] 2019-01-24 19:30
Sweet! Thanks for the reply. I hope that will be the case. A bunch of of us use it at work and all would very much appreciate that feature!

**Comment by dmiller-nmap** [comment] 2019-01-24 20:42
Ok, I think the problem here is that the data you want is in a `gtk.TreeView` (in this case, tabular data), and not editable. Because it's not editable, it doesn't get the standard hooks for Ctrl+C/copy and can't set data into the clipboard. I'm still researching to see if there's an easy way to do it. [Here's an example](https://www.kksou.com/php-gtk2/sample-codes/copy-row-data-from-GtkTreeView-using-GtkClipboard-Part-2-copy-multiple-rows.php) where someone created their own "stuff text into the clipboard" function and made a button on the interface labeled "Copy." This doesn't really solve the keyboard binding thing, but it's a possibility. Even if we made it a context (right-click) menu option, that could work. But maybe there is a more natural option out there.

**Comment by mtbike61384** [comment] 2019-01-24 20:46
I see that makes sense. The primary use case is with tons of targets you want to quickly pop a host ip into something else to test. So whatever form or method that could take would still be better then no option to do that.

**Comment by dmiller-nmap** [comment] 2019-01-28 18:08
I've opened a new issue for an enhancement to support exporting data from Zenmap's views, which I think better describes your use case. Please comment on #1447 if you have further clarification of your needs.

Since this is not really a bug per se, I am closing this issue to avoid confusion. Non-editable display objects do not naturally support copy-to-clipboard. Thanks for bringing this up!

**Closed by dmiller-nmap** 2019-01-28 18:08 UTC
Labels: Windows, Zenmap, bug
