### ISSUE TITLE
Segmentation fault in --top-ports param

### ISSUE THREAD

**Issue by captain-woof** [nmap/nmap#2725] opened 2023-10-17 19:29 UTC
**Describe the bug**
Passing `4261` or higher in `--top-ports` parameter gives this error:
```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-10-18 00:53 IST
zsh: segmentation fault  sudo nmap -Pn -sS -oN nmap-basic.txt --top-ports 4261 -v HOST
```

**To Reproduce**
Run nmap with:
```
sudo nmap -Pn -sS -oN nmap-basic.txt --top-ports 4261 -v HOST
```

**Expected behavior**
The scan should start as usual, doing a simple port scan of the first few thousand ports.

**Version info (please complete the following information):**
 - OS: Kali GNU/Linux 2023.3
 - Output of `nmap --version`:
   ```
   Nmap version 7.94 ( https://nmap.org )
   Platform: x86_64-pc-linux-gnu
   Compiled with: liblua-5.4.4 openssl-3.0.10 libssh2-1.10.0 libz-1.2.13 libpcre-8.39 libpcap-1.10.4 nmap-libdnet-1.12 
   ipv6
   Compiled without:
   Available nsock engines: epoll poll select
   ```

**Comment by nazrinemin01** [comment] 2023-10-25 17:21
hello

**Comment by jatrindo** [comment] 2023-10-29 15:41
I think this is a duplicate of https://github.com/nmap/nmap/issues/2679, which mentions it's been [fixed](https://github.com/nmap/nmap/issues/2679#issuecomment-1644222299)

**Comment by dmiller-nmap** [comment] 2023-10-30 20:12
Closing as duplicate of #2679

**Closed by dmiller-nmap** 2023-10-30 20:12 UTC
Labels: Nmap
