### ISSUE TITLE
Packets injected with send_packet() cannot be received by sockets in the same computer

### ISSUE THREAD

**Issue by tlammi** [nmap/nmap#1603] opened 2019-05-22 07:26 UTC
# Environment
- Win 10 64-bit
- Npcap 0.995

# Description
Packets injected to Microsoft Loopback Adapter with `send_packet()` are not received by sockets listening the interface in the same machine. When listening to the interface with Wireshark the packets appear in the log.

The issue can be fixed by installing WinPcap instead of Npcap.

So in short:
- application X sends packet (UDP/IP) via a socket to microsoft loopback adapter
- packet is captured by Npcap
- Packet is forwarded to another interface
- Response packet is received
- The response is injected to microsoft loopback adapter
- The response packet appears in Wireshark log but is never received by the application X listening to response

When WinPcap is used instead of Npcap everything works fine.

**Comment by dmiller-nmap** [comment] 2020-05-06 04:35
This is a duplicate of #1929, which is solved in Npcap 0.9990 and later.

**Closed by dmiller-nmap** 2020-05-06 04:35 UTC
