### ISSUE TITLE
  Nmap 7.8 Assertion failed: htn.toclock_running == true

### ISSUE THREAD

**Issue by lpesyna** [nmap/nmap#1764] opened 2019-09-27 19:24 UTC
I am now getting this error when I attempt to do a full discovery sweep on our Class C systems.  Using a local Windows 7 PC, no router hop, using syn scans as some devices do not respond to ping.  

This is new to us in version 7.8,   We have used these routines in version 7.7, 7.6, 6.x, and prior.

Assertion failed: htn.toclock_running == true, file ..\Target.cc, line 503

The command for a specific instance is as below.

"C:\\Program Files (x86)\\Nmap\\nmap.exe" -v -T2 -p21,23,80 -n -oA c:\\uploads\\local -Pn --exclude 10.11.11.234,10.11.11.254 10.11.11.234/24

By trial an error I have found the threshold for triggering the error is a target range on or around 104 IP addresses.  Setting --max-parallelism to 10 (random choice) prevents the error in the situations I tried. 

Of course, I am unable to reproduce this in our lab environment, it only has occurred in our production subnets,

**Comment by twkrol** [comment] 2019-10-04 08:07
Same on my Windows 10 with freshly instaled nmap 7.8
Setting --max-parallelism to 10 helps.

**Comment by lpesyna** [comment] 2019-10-04 09:26
I have some systems that I am unable to make work regardless of the max-parallelism setting.  I've been forced to revert to 7.7.
On Oct 4, 2019 4:08 AM, Tomasz Król <notifications@github.com> wrote:

Same on my Windows 10 with freshly instaled nmap 7.8
Setting --max-parallelism to 10 helps.

**Comment by davidasailor** [comment] 2019-12-27 16:51
I am having the same problem on my home network, scanning 192.168.1.0/24. Nmap version 7.80 on Fedora 31, run as root.  Was not a problem until I updated to Fedora 31 this week (I presume Fedora 30 had an earlier Nmap version). It seems to be inconsistent, but fails more often than not.  Does not seem to be affected by max-parallelism.

```
# nmap -V
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1c libssh2-1.9.0 libz-1.2.11 libpcre-8.43 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

# nmap -vvv -sn -d --max-parallelism 10 192.168.1.0/24
Starting Nmap 7.80 ( https://nmap.org ) at 2019-12-27 11:45 EST
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 10
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
Initiating ARP Ping Scan at 11:45
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.

```

**Comment by phodina** [comment] 2020-02-05 15:24
Same on my Mac OS (macOS 10.14.6)
```shell
# nmap -sS 192.168.1.1-254
Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-05 16:18 CET
Assertion failed: (htn.toclock_running == true), function stopTimeOutClock, file Target.cc, line 503.
[1]    2485 abort      sudo nmap -sS 192.168.1.1-254
```

**Comment by xyxzxyz** [comment] 2020-03-09 20:38
Same issue here

**Comment by jpluimers** [comment] 2020-03-24 13:22
Could this be related to https://github.com/nmap/nmap/issues/1797 ?

On Windows 10, this simple case already fails (similar to the Mac OS case above) some of the times:

`nmap -sn 192.168.71.0/24`

The suggested workaround to add `--max-parallelism 100` works fine:

`nmap -sn --max-parallelism 100 192.168.71.0/24`

Note that :

- a Physical MacOS 10.13.6 machine on the same network does not exhibit the behaviour.
- Windows 7 Professional and Windows 8.1 Enterprise machines (both VM and Physical) on the same network do not exhibit the behaviour
-

**Comment by dmiller-nmap** [comment] 2020-04-27 17:34
Duplicate of #1764, solved in 33f421f

**Closed by dmiller-nmap** 2020-04-27 17:34 UTC

**Comment by wgaylord** [comment] 2020-07-02 18:36
Will a build with this fix be out soon?

**Comment by marcingryska** [comment] 2020-07-10 06:36
> Will a build with this fix be out soon for windows? Or do we have to build it to get this fix.

Thumbs up for this important question. I also would be like to know when this fix would be available in stable Windows version. We also encouterred such issue.

**Comment by PinkDev1** [comment] 2020-09-01 01:49
@bonsaiviking @dmiller-nmap new release for Windows pls

**Comment by amitai** [comment] 2020-09-08 23:05
> 
> 
> > Will a build with this fix be out soon for windows? Or do we have to build it to get this fix.
> 
> Thumbs up for this important question. I also would like to know when this fix would be available in stable Windows version. We also encouterred such issue.

big same my friends

**Comment by fyodor** [comment] 2020-09-11 22:06
Hi Folks.  Our goal is to have a new Nmap release this month which would include this and all of the other fixes we've made since the last release.  Cheers!

**Comment by sandeep22-v** [comment] 2021-04-29 05:56
Internet might be very slow..That might be the reason

**Comment by leoheck** [comment] 2021-09-21 18:09
Max ``` --max-parallelism 100``` did not work for me.

My command
```nmap -oG - -p 554 --max-parallelism 100 ${network} 2>&1 >> .log```

The output 
```
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
```

My version
```
➜ nmap -v
Starting Nmap 7.80 ( https://nmap.org ) at 2021-09-21 15:04 -03
Read data files from: /usr/bin/../share/nmap
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.03 seconds
```

```
➜ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=22.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=31.0 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=23.6 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=27.6 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=117 time=25.4 ms
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 22.440/25.988/31.022/3.057 ms
```


![Screenshot-20210921150645-1225x947](https://user-images.githubusercontent.com/1277920/134224236-8af514dd-5a1c-4a08-b59f-04c9cc635112.png)

My internet is not that bad, I should not have this problem, I think. It has to be something else.

**Comment by leoheck** [comment] 2021-09-21 18:11
Now, some seconds after making the comment before, it worked. This issue is pretty hard to understand.

**Comment by Martyn575** [comment] 2022-03-31 13:21
After consistently failing, it now consistently works. :)

**Comment by leoheck** [comment] 2022-03-31 13:31
I am still seeing nmap 7.8 as the default version on my pre-released Ubuntu 22.04 OS. Do you guys know when a new version of this tool is going to be spread to the world?

```
➜  ~ nmap --version 
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.0 nmap-libssh2-1.8.2 libz-1.2.11 libpcre-8.39 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy

```

**Comment by nnposter** [comment] 2022-03-31 16:26
As far as I know, it is up to the individual distros to decide what version they are going to ship.
Ubuntu Jammy appears to be shipping some hybrid version: `7.91+dfsg1+really7.80+dfsg1-2build1`

**Comment by dmak** [comment] 2022-04-12 20:53
Same issue with [nmap 7.91+dfsg1+really7.80+dfsg1-2](https://packages.debian.org/bullseye/nmap) from Debian x64 Bullseye:
```
# nmap --version
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1j libssh2-1.9.0 libz-1.2.11 libpcre-8.44 libpcap-1.10.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
Sometimes (about 1 per 5 runs) nmap fails with the following error:
```
nmap --open -p 23,80 192.168.10.0/24
Starting Nmap 7.80 ( https://nmap.org ) at 2022-04-12 21:16 CEST
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
```
Core dump:
```
TIME                            PID   UID   GID SIG COREFILE  EXE
Mon 2022-04-11 10:05:04 CEST 123024     0     0   6 present   /usr/bin/nmap

           PID: 123024 (nmap)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Mon 2022-04-11 10:04:57 CEST
  Command Line: nmap --open -p 23,80 192.168.10.0/24
    Executable: /usr/bin/nmap
       Message: Process 123024 (nmap) of user 0 dumped core.
                
                Stack trace of thread 123024:
                #0  0x00007f043ed6bce1 raise (libc.so.6 + 0x3bce1)
                #1  0x00007f043ed55537 abort (libc.so.6 + 0x25537)
                #2  0x00007f043ed5540f n/a (libc.so.6 + 0x2540f)
                #3  0x00007f043ed64662 __assert_fail (libc.so.6 + 0x34662)
                #4  0x000055f07b1f1da0 _ZN6Target16stopTimeOutClockEPK7timeval (nmap + 0xa4da0)
                #5  0x000055f07b1d7b08 _ZN13UltraScanInfo20removeCompletedHostsEv (nmap + 0x8ab08)
                #6  0x000055f07b1d90d4 _Z10ultra_scanRSt6vectorIP6TargetSaIS1_EEP10scan_lists5stypeP12timeout_info (nmap + 0x8c0d4)
                #7  0x000055f07b1f2b11 n/a (nmap + 0xa5b11)
                #8  0x000055f07b1f380c n/a (nmap + 0xa680c)
                #9  0x000055f07b1f3945 _Z8nexthostP14HostGroupStatePK7addrsetP10scan_listsi (nmap + 0xa6945)
                #10 0x000055f07b1aa5db _Z9nmap_mainiPPc (nmap + 0x5d5db)
                #11 0x000055f07b184028 main (nmap + 0x37028)
                #12 0x00007f043ed56d0a __libc_start_main (libc.so.6 + 0x26d0a)
                #13 0x000055f07b1840ca _start (nmap + 0x370ca)
```
I never faced the issue in Debian Buster (nmap v7.70).

**Comment by codeScriber** [comment] 2022-07-09 16:45
i'm on ubuntu 22.04 and after the last upgrade the issue appeared, if so many ppl complain and i don't see a resolution or a workaround, how come the issue is closed ? it's a show stopper, the program doesn't run

**Comment by nnposter** [comment] 2022-07-11 19:16
@codeScriber 
> if so many ppl complain and i don't see a resolution or a workaround, how come the issue is closed ?

The issue is closed because the originally identified problem is presumed resolved in version 7.90 and no message in this thread indicates otherwise. If you are getting this assertion error in the current version, 7.92, then please open a new issue.

As noted earlier, please note that some distributions are creating their own versions of Nmap, such as [7.91+dfsg1+really7.80+dfsg1-2](https://packages.debian.org/bullseye/nmap), which suggests that this is some kind of a hybrid, over which the Nmap project has no control. It is therefore always more useful if the issue can be demonstrated with a binary package downloaded from [Nmap.org](https://nmap.org/download.html) or compiled from the official source code.

**Comment by codeScriber** [comment] 2022-07-11 21:22
thanks for the clarification.
ubuntu 22.04 apparently still packs the old version 7.80 so probably compiling from source is the only solution, or building a static distribution which is portable...

**Comment by codeScriber** [comment] 2022-07-12 14:01
Actually i ran `nmap  192.168.100.0/24 -p 0-1024 --open`

**Comment by msandy** [comment] 2022-08-03 17:15
> please note that some distributions are creating their own versions of Nmap, such as [7.91+dfsg1+really7.80+dfsg1-2](https://packages.debian.org/bullseye/nmap), which suggests that this is some kind of a hybrid, over which the Nmap project has no control.

According to https://nmap.org/book/inst-linux.html, these packages are managed by a "LaMont Jones". Assuming this is not the basketball player, searching for "lamont jones linux" results in a debian thread titled [LaMont Jones, WTH are you doing?](https://lists.debian.org/debian-project/2013/02/msg00009.html) from 2013 which seems to indicate some long-running controversy over this kind of repackaging of other binaries.

In any case, I'd guess that 99.9% of nmap users acquire the binary through a package manager and will probably end up getting the old version currently. This may not be nmap's "fault" but it's still nmap's problem. Not every package in debian/ubuntu gets repackaged like nmap, so what is it about nmap that requires it, and is preventing the adoption of 7.9 into the default apt sources?

**Comment by kjellarneodegaard** [comment] 2022-10-27 10:01
For anybody else ending up here researching an nmap error message, my solution was to install a new (7.93) nmap version from snap: https://snapcraft.io/nmap

Remember give it access to network-control `sudo snap connect nmap:network-control`

**Comment by mivsvit** [comment] 2023-03-03 13:31
This looks like this may be fixed in Ubuntu. See for example:

 [https://ubuntu.pkgs.org/22.04/ubuntu-updates-universe-amd64/nmap_7.91+dfsg1+really7.80+dfsg1-2ubuntu0.1_amd64.deb.html](https://ubuntu.pkgs.org/22.04/ubuntu-updates-universe-amd64/nmap_7.91+dfsg1+really7.80+dfsg1-2ubuntu0.1_amd64.deb.html)
 and 
 
[https://bugs.launchpad.net/ubuntu/+source/nmap/+bug/1908223](https://bugs.launchpad.net/ubuntu/+source/nmap/+bug/1908223)

> According to https://nmap.org/book/inst-linux.html, these packages are managed by a "LaMont Jones". 

I don't believe that is the case any more. Debian maintainers listed at
[https://packages.debian.org/stable/nmap](https://packages.debian.org/stable/nmap)

As discussed in both the changelog and the Ubuntu bug, there seem to be concerns about the licensing terms for newer versions of nmap.

**Comment by safaATcurrus** [comment] 2023-04-26 22:04
uname -a:
Linux ubuntu 5.10.104-tegra #1 SMP PREEMPT Sun Mar 19 07:55:28 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux


cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


The solutions don't work. I am still getting error when I run nmap 

Starting Nmap 7.80 ( https://nmap.org ) at 2023-04-26 18:00 EDT
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
Aborted

**Comment by rgaufman** [comment] 2023-07-10 10:47
Any solution to this?

**Comment by safaATcurrus** [comment] 2023-07-11 19:37
I dont remember if I fixed this but check if your system's clock is up to date.
________________________________

**Comment by rgaufman** [comment] 2023-07-11 22:50
It is up to date using and using ntp to ensure it stays up to date. Compiling the latest version from source fixes this, but are there any precompiled packages for 20.04?

**Comment by zcattacz** [comment] 2024-07-03 00:35
Last time I didn't realize the rtl8168 driver crashed. And I tried some -PA/PE/sP scan on one LAN with both /24 and `.*` pattern. I was given this same error, meanwhile tcpdump did show some rare ARP replies from that network interface around the moment nmap crashed,  it was a very confusing troubleshoot.
