### ISSUE TITLE
ms-sql-brute script error on 7.93

### ISSUE THREAD

**Issue by rag-altx** [nmap/nmap#2535] opened 2022-10-04 11:42 UTC
`-d3 -p 1433 -T4 -v -Pn --script ms-sql-brute --script-args "mssql.instance-port=1433,userdb=C:\\Users\\rag\\Downloads\\u.txt,passdb=C:\\Users\\rag\\Downloads\\p.txt" localhost --disable-arp-ping -sT`

Files u.txt and p.txt contain only one right login/password. In 7.93 version i have this error:

`|_ms-sql-brute: ERROR: Script execution failed (use -d to debug)`

![7 93](https://user-images.githubusercontent.com/4427551/193809931-ecad4851-2944-437d-8bca-819647c8a6dd.png)
![7 92](https://user-images.githubusercontent.com/4427551/193809936-70c6936f-33f8-4ee7-b188-cfb4341d9107.png)
![7 91](https://user-images.githubusercontent.com/4427551/193809938-34c350f6-e5b3-4f3d-b57c-b3148303e249.png)

**Comment by iasdeoupxe** [comment] 2023-07-09 14:00
While this issue is older it looks like #2622 could be a duplicate and a patch within it is available which should fix this as well.

**Comment by nnposter** [comment] 2024-07-04 20:55
There is not enough detail in this issue to track down the root cause.

A number of bug fixes in the mssql NSE library have now been committed. If possible, please retest and reopen the issue, providing relevant debug output, if the problem persists.

**Closed by nnposter** 2024-07-04 20:55 UTC
Labels: Nmap
