### ISSUE TITLE
can't dump open redis data with redis-info script

### ISSUE THREAD

**Issue by digininja** [nmap/nmap#2475] opened 2022-05-10 09:49 UTC
**Describe the bug**
Running the redis-info script against an open redis server doesn't return any info, Nessus and redis-cli is able to dump data.

**To Reproduce**
```
└─$ nmap -p 1520 -n --script redis-info 1.2.3.4 -d    
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-10 05:44 EDT
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 05:44
Completed NSE at 05:44, 0.00s elapsed
Initiating Ping Scan at 05:44
Scanning 1.2.3.4  [2 ports]
Completed Ping Scan at 05:44, 0.00s elapsed (1 total hosts)
Overall sending rates: 2116.40 packets / s.
Initiating Connect Scan at 05:44
Scanning 1.2.3.4  [1 port]
Discovered open port 1520/tcp on 1.2.3.4 
Completed Connect Scan at 05:44, 0.00s elapsed (1 total ports)
Overall sending rates: 1522.07 packets / s.
NSE: Script scanning 1.2.3.4 .
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 05:44
NSE: Starting redis-info against 1.2.3.4 :1520.
NSE: redis-info against 1.2.3.4 :1520 threw an error!
/usr/bin/../share/nmap/scripts/redis-info.nse:139: table index is nil
stack traceback:
        /usr/bin/../share/nmap/scripts/redis-info.nse:139: in local 'process'
        /usr/bin/../share/nmap/scripts/redis-info.nse:250: in function </usr/bin/../share/nmap/scripts/redis-info.nse:181>
        (...tail calls...)

Completed NSE at 05:44, 0.00s elapsed
Nmap scan report for 1.2.3.4 
Host is up, received syn-ack (0.00051s latency).
Scanned at 2022-05-10 05:44:02 EDT for 0s

PORT     STATE SERVICE        REASON
1520/tcp open  atm-zip-office syn-ack
Final times for host: srtt: 513 rttvar: 3798  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 05:44
Completed NSE at 05:44, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 0.27 seconds
```

**Expected behavior**
redis-cli can dump the info:

```
└─$ redis-cli -h 1.2.3.4 -p 1520 INFO 
# Server
redis_version:3.0.503
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d14575c6134f877
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:5728
run_id:a8d31d0524023c7db81c6755d9956ade1f040092
tcp_port:1520
uptime_in_seconds:9078461
uptime_in_days:105
hz:10
lru_clock:8008793
config_file:C:\Program Files\blah\Redis.conf

# Clients
connected_clients:13
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
```

Don't know if this is related to it being on a non-standard port.

**Version info (please complete the following information):**
 - OS: Kali
 - Output of `nmap --version`:
```
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-1.1.1l libssh2-1.10.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

**Additional context**
I've got access to this box will Friday 13th so happy to debug up till then.

**Comment by nnposter** [comment] 2022-05-10 16:29
Thank you for the report. This appears to be a duplicate of #2296, fixed in r38378 (a5d57b3280869675bb2a93c4f4c2e58cebc72906).

Could you please update  the script from [SVN](https://svn.nmap.org/nmap/scripts/redis-info.nse) or [GitHub](https://raw.githubusercontent.com/nmap/nmap/master/scripts/redis-info.nse) and retest?

**Comment by digininja** [comment] 2022-05-10 16:32
It looks like I can just grab that script and try that, would that work?

**Comment by nnposter** [comment] 2022-05-10 16:38
It should

**Comment by nnposter** [comment] 2022-05-11 22:17
I have pushed another update. This one fixes processing of cluster nodes, so a less frequent crash. (The error you experienced was in processing of client connections.)

**Comment by digininja** [comment] 2022-05-12 08:25
The new version didn't crash but didn't dump any data:

```
└─$ nmap 1.2.3.4 -Pn -n -p 1520 --script ./redis-info-new.nse -d
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-12 04:14 EDT
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:14
Completed NSE at 04:14, 0.00s elapsed
Initiating Connect Scan at 04:14
Scanning 1.2.3.4 [1 port]
Discovered open port 1520/tcp on 1.2.3.4
Completed Connect Scan at 04:14, 0.00s elapsed (1 total ports)
Overall sending rates: 1002.00 packets / s.
NSE: Script scanning 1.2.3.4.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:14
Completed NSE at 04:14, 0.00s elapsed
Nmap scan report for 1.2.3.4
Host is up, received user-set (0.00040s latency).
Scanned at 2022-05-12 04:14:44 EDT for 0s

PORT     STATE SERVICE        REASON
1520/tcp open  atm-zip-office syn-ack
Final times for host: srtt: 401 rttvar: 5000  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:14
Completed NSE at 04:14, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 0.25 seconds
```

As this is running on a non-standard port, I modified line 50 to look for the port it is on rather than the default:

```
portrule = shortport.port_or_service(1520, "redis")
```

Ran it again and ...

```
└─$ nmap 1.2.3.4 -Pn -n -p 1520 --script ./redis-info-new.nse -d
Starting Nmap 7.92 ( https://nmap.org ) at 2022-05-12 04:20 EDT
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI:
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:20
Completed NSE at 04:20, 0.00s elapsed
Initiating Connect Scan at 04:20
Scanning 1.2.3.4 [1 port]
Discovered open port 1520/tcp on 1.2.3.4
Completed Connect Scan at 04:20, 0.00s elapsed (1 total ports)
Overall sending rates: 1113.59 packets / s.
NSE: Script scanning 1.2.3.4.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:20
NSE: Starting redis-info-new against 1.2.3.4:1520.
NSE: Finished redis-info-new against 1.2.3.4:1520.
Completed NSE at 04:20, 0.00s elapsed
Nmap scan report for 1.2.3.4
Host is up, received user-set (0.00081s latency).
Scanned at 2022-05-12 04:20:55 EDT for 0s

PORT     STATE SERVICE        REASON
1520/tcp open  atm-zip-office syn-ack
| redis-info-new:
|   Version: 3.0.503
|   Operating System: Windows
|   Architecture: 64 bits
|   Process ID: 20704
|   Used CPU (sys): 0.19
|   Used CPU (user): 0.38
|   Connected clients: 14
|   Connected slaves: 0
|   Used memory: 941.83K
|   Role: master
|   Bind addresses:
|     0.0.0.0
|   Active channels:
|     __Booksleeve_MasterChanged
|   Client connections:
|     1.2.3.4
|_    127.0.0.1
Final times for host: srtt: 808 rttvar: 5000  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 04:20
Completed NSE at 04:20, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 0.26 seconds
```

So the bug is fixed, it just doesn't like the non-standard port. A quick google and I learnt about putting a `+` in front of a script to force it to run, and all is good.

And, this may be a zsh thing, I got the latest version from GitHub and tried to use it like this `--script ./redis-info.nse` so that it would use the local copy rather than the installed one but it still used the one from `/usr/share...`. I ended up renaming the script  to force it to use this new version.

**Comment by nnposter** [comment] 2022-05-12 13:29
The fact that the script did not originally run is not surprising. The scripts are generally set to run when either of the following conditions is true:

* The port is a default/expected port for the given application (6379 for Redis)
* Nmap determined through `-sV` version scanning that the given application is in fact on the port
* Nmap is forced to use the script, via the `+` prefix

In your case, using `+` was probably the right choice, since you already new Redis was on that port, but you do not want to overuse it because the script will then force-run no matter what, which is not what you want if you do general recon. Version scanning `-sV` would be likely more suitable then.

Please close the issue if you believe it has been resolved to your satisfaction.

**Closed** 2022-05-12 13:38 UTC
Labels: bug, duplicate, NSE script
