### ISSUE TITLE
Assertion failed?

### ISSUE THREAD

**Issue by djhalnon** [nmap/nmap#2466] opened 2022-04-14 00:01 UTC
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
Starting Nmap 7.80 ( https://nmap.org ) at 2022-04-13 19:51 EDT
Assertion failed: (res > 7), function sock library initialize, file nsock pool.c, line 307.

**To Reproduce**
Open Zenmap, then start a scan. 

**Expected behavior**
What I expected was for it to scan ports on an IP address I'd entered. Silly me, obviously. 

**Version info (please complete the following information):**
OS: Mac OS 12.3.1
 - Output of `nmap --version`:
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-apple-darwin17.7.0
Compiled with: nmap-liblua-5.3.5 openssl-1.0.2s nmap-libssh2-1.8.2 libz-1.2.11 nmap-libpcre-7.6 nmap-libpcap-1.9.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select
- Output of `nmap --iflist`
Starting Nmap 7.80 ( https://nmap.org ) at 2022-04-13 19:59 EDT
************************INTERFACES************************
DEV     (SHORT)   IP/MASK                       TYPE        UP   MTU   MAC
lo0     (lo0)     127.0.0.1/8                   loopback    up   16384
lo0     (lo0)     ::1/128                       loopback    up   16384
lo0     (lo0)     fe80::1/128                   loopback    up   16384
gif0    (gif0)    (none)/0                      point2point down 1280
stf0    (stf0)    (none)/0                      other       down 1280
en0     (en0)     192.168.1.29/24               ethernet    up   1500  A8:60:B6:0E:6D:74
en0     (en0)     fe80::10df:7601:c810:d948/128 ethernet    up   1500  A8:60:B6:0E:6D:74
en1     (en1)     (none)/0                      ethernet    up   1500  28:F0:76:61:1F:DC
en2     (en2)     (none)/0                      ethernet    up   1500  82:19:09:CD:74:C0
en3     (en3)     (none)/0                      ethernet    up   1500  82:19:09:CD:74:C1
bridge0 (bridge0) (none)/0                      ethernet    up   1500  82:19:09:CD:74:C0
p2p0    (p2p0)    (none)/0                      ethernet    up   2304  0A:F0:76:61:1F:DC
awdl0   (awdl0)   (none)/0                      ethernet    up   1484  8A:62:02:AA:DE:D4
llw0    (llw0)    (none)/0                      ethernet    down 1500  8A:62:02:AA:DE:D4
utun0   (utun0)   (none)/0                      point2point up   1380
utun0   (utun0)   fe80::4fed:b77f:a711:ae1e/128 point2point up   1380
utun1   (utun1)   (none)/0                      point2point up   2000
utun1   (utun1)   fe80::64ef:ba24:5795:1726/128 point2point up   2000
utun2   (utun2)   (none)/0                      point2point up   1000
utun2   (utun2)   fe80::ce81:b1c:bd2c:69e/128   point2point up   1000

**************************ROUTES**************************
DST/MASK                        DEV   METRIC GATEWAY
140.82.112.26/32                en0   0      192.168.1.1
151.101.131.10/32               en0   0      192.168.1.1
3.237.55.202/32                 en0   0      192.168.1.1
157.55.109.224/32               en0   0      192.168.1.1
13.89.179.10/32                 en0   0      192.168.1.1
157.55.109.232/32               en0   0      192.168.1.1
13.105.74.50/32                 en0   0      192.168.1.1
162.125.4.13/32                 en0   0      192.168.1.1
17.248.175.174/32               en0   0      192.168.1.1
17.248.175.180/32               en0   0      192.168.1.1
17.248.175.198/32               en0   0      192.168.1.1
17.248.175.213/32               en0   0      192.168.1.1
17.248.175.238/32               en0   0      192.168.1.1
17.248.186.140/32               en0   0      192.168.1.1
17.253.21.203/32                en0   0      192.168.1.1
18.214.111.36/32                en0   0      192.168.1.1
20.189.173.7/32                 en0   0      192.168.1.1
23.22.254.206/32                en0   0      192.168.1.1
40.70.161.102/32                en0   0      192.168.1.1
40.79.207.80/32                 en0   0      192.168.1.1
40.90.130.194/32                en0   0      192.168.1.1
40.90.130.197/32                en0   0      192.168.1.1
40.90.130.199/32                en0   0      192.168.1.1
40.90.133.99/32                 en0   0      192.168.1.1
40.90.133.112/32                en0   0      192.168.1.1
40.90.136.20/32                 en0   0      192.168.1.1
40.90.136.163/32                en0   0      192.168.1.1
44.195.64.169/32                en0   0      192.168.1.1
44.199.137.111/32               en0   0      192.168.1.1
47.43.18.12/32                  en0   0      192.168.1.1
52.2.161.197/32                 en0   0      192.168.1.1
52.86.88.22/32                  en0   0      192.168.1.1
52.96.32.2/32                   en0   0      192.168.1.1
52.96.33.82/32                  en0   0      192.168.1.1
52.96.88.18/32                  en0   0      192.168.1.1
52.96.109.242/32                en0   0      192.168.1.1
52.108.79.27/32                 en0   0      192.168.1.1
52.178.17.2/32                  en0   0      192.168.1.1
52.182.143.210/32               en0   0      192.168.1.1
52.226.139.121/32               en0   0      192.168.1.1
54.227.95.54/32                 en0   0      192.168.1.1
54.227.187.23/32                en0   0      192.168.1.1
54.227.199.9/32                 en0   0      192.168.1.1
67.195.205.49/32                en0   0      192.168.1.1
69.147.92.12/32                 en0   0      192.168.1.1
72.21.91.29/32                  en0   0      192.168.1.1
74.6.106.26/32                  en0   0      192.168.1.1
74.6.141.28/32                  en0   0      192.168.1.1
104.244.42.1/32                 en0   0      192.168.1.1
104.244.42.194/32               en0   0      192.168.1.1
104.244.43.131/32               en0   0      192.168.1.1
127.0.0.1/32                    lo0   0      127.0.0.1
130.211.16.53/32                en0   0      192.168.1.1
131.253.14.227/32               en0   0      192.168.1.1
142.250.31.188/32               en0   0      192.168.1.1
146.75.28.159/32                en0   0      192.168.1.1
5.188.124.23/32                 en0   0      192.168.1.1
13.105.28.16/32                 en0   0      192.168.1.1
13.248.151.210/32               en0   0      192.168.1.1
17.57.144.11/32                 en0   0      192.168.1.1
162.125.6.20/32                 en0   0      192.168.1.1
162.125.19.130/32               en0   0      192.168.1.1
162.125.19.131/32               en0   0      192.168.1.1
162.241.252.80/32               en0   0      192.168.1.1
162.241.253.231/32              en0   0      192.168.1.1
172.217.0.42/32                 en0   0      192.168.1.1
172.253.63.100/32               en0   0      192.168.1.1
172.253.63.108/32               en0   0      192.168.1.1
172.253.115.109/32              en0   0      192.168.1.1
172.253.122.109/32              en0   0      192.168.1.1
185.70.42.25/32                 en0   0      192.168.1.1
185.199.108.133/32              en0   0      192.168.1.1
185.199.109.154/32              en0   0      192.168.1.1
192.168.1.1/32                  en0   0
192.168.1.21/32                 en0   0
192.168.1.29/32                 en0   0
192.241.190.108/32              en0   0      192.168.1.1
255.255.255.255/32              en0   0
192.168.1.0/24                  en0   0
169.254.0.0/16                  en0   0
127.0.0.0/8                     lo0   0      127.0.0.1
224.0.0.0/4                     en0   0
0.0.0.0/0                       en0   0      192.168.1.1
::1/128                         lo0   0      ::1
fe80:1::1/128                   lo0   0
fe80:c::4fed:b77f:a711:ae1e/128 lo0   0
fe80:d::64ef:ba24:5795:1726/128 lo0   0
fe80:e::ce81:b1c:bd2c:69e/128   lo0   0
fe80:1::/64                     lo0   0      fe80:1::1
fe80:4::/64                     en0   0
fe80:c::/64                     utun0 0      fe80:c::4fed:b77f:a711:ae1e
fe80:d::/64                     utun1 0      fe80:d::64ef:ba24:5795:1726
fe80:e::/64                     utun2 0      fe80:e::ce81:b1c:bd2c:69e
ff01:1::/32                     lo0   0      ::1
ff01:4::/32                     en0   0
ff01:c::/32                     utun0 0      fe80:c::4fed:b77f:a711:ae1e
ff01:d::/32                     utun1 0      fe80:d::64ef:ba24:5795:1726
ff01:e::/32                     utun2 0      fe80:e::ce81:b1c:bd2c:69e
ff02:1::/32                     lo0   0      ::1
ff02:4::/32                     en0   0
ff02:c::/32                     utun0 0      fe80:c::4fed:b77f:a711:ae1e
ff02:d::/32                     utun1 0      fe80:d::64ef:ba24:5795:1726
ff02:e::/32                     utun2 0      fe80:e::ce81:b1c:bd2c:69e
ff00::/8                        lo0   0      ::1
ff00::/8                        en0   0
ff00::/8                        utun0 0      fe80:c::4fed:b77f:a711:ae1e
ff00::/8                        utun1 0      fe80:d::64ef:ba24:5795:1726
ff00::/8                        utun2 0      fe80:e::ce81:b1c:bd2c:69e
::/0                            utun0 0      fe80:c::
::/0                            utun1 0      fe80:d::
::/0                            utun2 0      fe80:e::

**Additional context**
Nothing special.

**Comment by dmiller-nmap** [comment] 2022-06-27 17:53
This was fixed in Nmap 7.91. Duplicate of #2079

**Closed by dmiller-nmap** 2022-06-27 17:53 UTC
Labels: Nmap
