### ISSUE TITLE
npcap v0.78r5 - Network limited or no connectivity.

### ISSUE THREAD

**Issue by afallenhope** [nmap/nmap#610] opened 2016-12-16 04:16 UTC
After installing the latest version of nmap I noticed I was experiencing issues with npcap. I did at one point in time check all options.  Once I discovered the "Releases" I've always stayed up to date and been reading the issues with drivers. 

After installing the latest (0.78r5), I rebooted my computer and I wasn't able to get an IP. I've uninstalled the loopback adapter with NPFInstall.exe -ul and I've also uninstalled the wifi NPFInstall.exe -u2 and still had issues. I completely uninstalled and my wifi has returned to me.

I've tried stopping npcap and npf and both seem to have little to no effect on the issue. Only way I can get my network is by uninstalling npcap. 

I've created a batch file that I run when I run into IP issues.

```
@echo off
echo Releasing IP address
ipconfig /release >nul
echo Test to see if things work.
echo.
echo Press any key if it didn't
pause>nul
echo Resetting ARP cache
netsh int ip delete arpcache
echo.
echo Press any key if it didn't fix it
pause>nul
echo Extreme moment here, resetting interface.
netsh int ip reset
echo.
echo If nothing fixed it... Contact support.
```

**Comment by afallenhope** [comment] 2016-12-16 04:45
Resolved the issue by disabling my Vbox Networking Adapter.

**Comment by dmiller-nmap** [comment] 2016-12-16 05:22
This issue needs to be addressed, still. @afallenhope mentioned an interesting notion on IRC: Npcap may be doing something to the wrong interface based on its ordinal position in some listing:

>seems like (I recalled reading it on seclist) it grabs the first adapter it can find..... That adapter is Vbox's virtual adapter. Which...doesn't have network (one of my packet sniffers I wrote had the same issue, and Dns.GetHostEntry(Dns.GetHostName()); caused the same issue. So I disabled VirtualBox's adapter.
>re-enabled my vbox bridge adapter.. still have internet. So...... I think it's a vbox adapter taking precedent

I believe that NPFInstall.exe is taking some sort of action on adapters that do not support it: the Vbox adapter in this case, but also possibly VPN adapters and other software we have previously reported as conflicting. I am keeping this open until I finish investigating.

**Comment by taismi** [comment] 2016-12-20 14:57
I have this same problem.

Installation did not give me any error. Wireshark did not saw my wireless adapter. I tried this.
_C:\Program Files\Npcap>NPFInstall.exe -i2
Npcap LWF driver (with Wi-Fi support) has failed to be installed._

I changed HKEY_LOCAL_MACHIN/ESYSTEM/CurrentControlSet/Control/NetworkMaxNumFilters from 8 to 9. Then I installed Npcap but after reboot my wired Ethernet connection was gone.

I have FreedomeVPNConnection and VirtualBox Host-Only Network adapters installed.

**Comment by Varunram** [comment] 2016-12-28 14:19
@dmiller-nmap I think this might be caused by an else statement in netcfgapi.cpp 
```
 				{
					TRACE_PRINT1("HrInstallComponent: error, szComponentId = %s.", NDISLWF_SERVICE_PNP_DEVICE_ID_WIFI);
					// at least install the first service
					hr = pnc->Apply();
					if (hr != S_OK)
					{
						TRACE_PRINT1("INetCfg::Apply: error, errCode = 0x%08x.", hr);
					}
				}
```
The error might occur due to it installing (or trying to install) the first service.

**Comment by kalav** [comment] 2016-12-31 02:30
This is a problem that had me and my Windows admins scratching our heads for quite some time. Why is the adapter being given a link local address? Are DHCP services being blocked. 

The inability for my Windows 7 FP1 Toshiba Tecra A40-C's wireless adapter to get an outside IP address occurs with the npcap version bundled with the current nmap download, as well as the latest version of npcap, as of 30 Dec. 2016. 

The only workaround I've found, short of uninstalling npcap, is to turn off - in the wireless adapter's Network Connection Properties - Npcap Packet Driver (NPCAP). After doing this, the adapter immediately gets an outside IP address.

This workaround is okay for me, since I use nmap for local VMs, but this obviously not a use case for everyone. My own personal machine, a Windows 10 desktop, does not exhibit this behavior.

**Comment by dmiller-nmap** [comment] 2017-01-19 14:34
Investigating this as an instance of #373. Not closing this yet because there's useful info here.

**Comment by xtipacko** [comment] 2017-01-21 19:47
I've hit the same problem. It happens when a load my operations system (win7). For some reason, when I run nmap -sn 10.10.10.0/24 (my local network) it enables network connectivity, but only until next reboot.

**Comment by zandr14** [comment] 2017-02-08 16:39
0.80: https://github.com/nmap/nmap/issues/373#issuecomment-278381694

**Comment by everiknow** [comment] 2017-04-05 08:38
hey everyone
im still having the same issue even after installing the latest version of npcap-0.84
after rebboting my computer i can't connect to my WIFI
im using GNS3 1.5.2 with GNS3 VM 1.5.2

**Comment by Varunram** [comment] 2017-04-05 09:59
@everiknow What were the options with which you installed?

**Comment by everiknow** [comment] 2017-04-07 08:39
i used the default option but i just found a solution, under my WIFI card
properties i dis checked NPCAP driver PAcket option. now when i reboot my
computer i can access WIFI internet with no pronlem.


2017-04-05 11:59 GMT+02:00 Varunram Ganesh <notifications@github.com>:

**Comment by dmiller-nmap** [comment] 2017-05-26 22:30
Please try Npcap 0.90 and report if it fixes this issue. Thanks!

**Comment by dmiller-nmap** [comment] 2018-07-03 16:23
Provisionally closing this issue because we have done lots of changes and improvements related to OID requests and WiFi connectivity. Please make a new issue if you are experiencing similar symptoms with Npcap 0.99-r6 or later and reference this issue if they involve complete loss of connectivity with VirtualBox or a VPN network adapter.

**Closed by dmiller-nmap** 2018-07-03 16:23 UTC
Labels: Npcap, bug

**Comment by bijoy26** [comment] 2020-11-22 08:41
**OS:** Win 10 64 bit
**Nmap:** v7.91
**Npcap:** v1.00
**Installation Method:** nmap zip binaries for windows

Everything works fine after installing, except for rebooting my machine makes my _ethernet adapter_ confused.
It seems to obtain a different IP than usual, and the default gateway can't be accessed (which is my router providing DHCP) and so there's no internet.

Disabling and re-enabling the adapter from _Network Connection_ takes everything back to normal.
I guess it's coming from my additional **VBox adapter** mentioned on this issue.
