### ISSUE TITLE
NMAP smb-os-discovery script doesn't work with SMB2 and later

### ISSUE THREAD

**Issue by Alvin822** [nmap/nmap#2549] opened 2022-10-19 14:25 UTC
smb-os-discovery script doesn't work with smb2 and later versions

**Example 1 (with SMBv1):**
_nmap --script smb-enum-processes.nse -Pn -p445 XXX_
Host is up (0.0010s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds

Host script results:
| smb-protocols:
|   dialects:
|     NT LM 0.12 (SMBv1) [dangerous, but default]
|     2.0.2
|     2.1
|     3.0
|     3.0.2
|_    3.1.1

_nmap --script smb-os-discovery.nse -Pn -p445 XXX_
PORT    STATE SERVICE
445/tcp open  microsoft-ds

Host script results:
| smb-os-discovery:
|   OS: Windows 10 Enterprise 19044 (Windows 10 Enterprise 6.3)
|   OS CPE: cpe:/o:microsoft:windows_10::-
|   Computer name: XXX
|   NetBIOS computer name: XXX\x00
|   Domain name: XXX
|   Forest name: XXXX
|   FQDN: XXX
|_  System time: 2022-10-19T16:20:07+02:00

Nmap done: 1 IP address (1 host up) scanned in 1.03 seconds

**Example 1 (without SMBv1):**
_nmap --script smb-enum-processes.nse -Pn -p445 XXX_
Host is up (0.029s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds

Host script results:
| smb-protocols:
|   dialects:
|     2.0.2
|     2.1
|     3.0
|     3.0.2
|_    3.1.1

_nmap --script smb-os-discovery.nse -Pn -p445 XXX_
Host is up (0.029s latency).

PORT    STATE SERVICE
445/tcp open  microsoft-ds

Is there a way to obtain OS version from an host if it doesn't support SMBv1?

**Comment by fyodor** [comment] 2023-01-09 19:44
Thanks folks!  I'm closing this as a duplicate of #901 so we can focus the discussion and attention there.

**Comment by fyodor** [comment] 2023-01-09 19:45
Duplicate of #901

**Closed by fyodor** 2023-01-09 19:45 UTC
Labels: Nmap
