### ISSUE TITLE
Please publish tags for releases

### ISSUE THREAD

**Issue by samueloph** [nmap/nmap#2684] opened 2023-07-22 17:14 UTC
I'm currently debugging an issue reported on Debian for ncat (I didn't confirm the bug yet):
https://bugs.debian.org/1039613

I'm now using `git bisect` on a clone of this repo to try to identify which commit triggers the issue.
It turns out this would be easier to debug if there were git tags pointing to which commits are the HEAD of a release (eg.: which is the latest commit from the 7.93 release?).

Publishing tags also give you some extra GitHub features for users like being able to get notified on new releases and easily getting a diff of commits between any two releases.

**Comment by fyodor** [comment] 2023-07-22 17:28
Thanks @samueloph.  That is something we want to do once we migrate to a git-primary model for Nmap.  Right now Github is a read-only mirror of our Subversion repository, and our release branches are not mirrored. We do already have open Issue #412 for this goal, so I'm closing this issue as a duplicate.

**Comment by fyodor** [comment] 2023-07-22 17:28
Duplicate of #412

**Closed by fyodor** 2023-07-22 17:28 UTC
