### ISSUE TITLE
Nmap range scan not working as expected

### ISSUE THREAD

**Issue by neuralstring** [nmap/nmap#2488] opened 2022-06-13 23:11 UTC
Nmap detect some available(up) host as not-available(down) when performing ip range scan, But it can detect them correctly when performing single ip scan(check additional context section for more information).

**Version info (please complete the following information):**
 - OS: Linux arch 5.18.2-arch x86_64
 - Output of `nmap --version`:
```
Nmap version 7.92 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-1.1.1o libssh2-1.9.0 libz-1.2.11 libpcre-8.45 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
 - Output of `nmap --iflist`
```
Starting Nmap 7.92 ( https://nmap.org ) at 2022-06-14 03:25 +0430
************************INTERFACES************************
DEV        (SHORT)      IP/MASK          TYPE     UP MTU   MAC
lo         (lo)         127.0.0.1/8      loopback up 65536
lo         (lo)         ::1/128          loopback up 65536
enp7s0     (enp7s0)     192.168.1.131/24 ethernet up 1500  B4:█:█:█:█:█
virbr0     (virbr0)     192.168.122.1/24 ethernet up 1500  52:█:█:█:█:█
wlp9s0f3u4 (wlp9s0f3u4) (none)/0         ethernet up 1500  12:█:█:█:█:█

**************************ROUTES**************************
DST/MASK         DEV    METRIC GATEWAY
192.168.122.0/24 virbr0 0
192.168.1.0/24   enp7s0 100
0.0.0.0/0        enp7s0 100    192.168.1.1
::1/128          lo     0
::1/128          lo     256
```

**Additional context**

 - Output of `sudo nmap -sn  "192.168.1.138 -vvv"`
```
Initiating ARP Ping Scan at 03:34
Scanning 192.168.1.138 [1 port]
Completed ARP Ping Scan at 03:34, 0.13s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 03:34
Completed Parallel DNS resolution of 1 host. at 03:34, 0.00s elapsed
DNS resolution of 1 IPs took 0.00s. Mode: Async [#: 2, OK: 1, NX: 0, DR: 0, SF: 0, TR: 1, CN: 0]
Nmap scan report for yeelink-light-color2_miapdb5a (192.168.1.138)
Host is up, received arp-response (0.11s latency).
MAC Address: 04:█:█:█:█:█ (Xiaomi Electronics,co.)
Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 0.21 seconds
           Raw packets sent: 1 (28B) | Rcvd: 1 (28B)
```

 - Output of `sudo nmap -sn  "192.168.1.*" -vvv`
```
...
Nmap scan report for 192.168.1.138 [host down, received no-response]
...
```

 - Output of `sudo nmap -A -T4  "192.168.1.*" -vvv`
```
...
Nmap scan report for 192.168.1.138 [host down, received no-response]
...
```

 - Output of `ping -c4 192.168.1.138`
```
PING 192.168.1.138 (192.168.1.138) 56(84) bytes of data.
64 bytes from 192.168.1.138: icmp_seq=1 ttl=255 time=1.96 ms
64 bytes from 192.168.1.138: icmp_seq=2 ttl=255 time=1.66 ms
64 bytes from 192.168.1.138: icmp_seq=3 ttl=255 time=2.01 ms
64 bytes from 192.168.1.138: icmp_seq=4 ttl=255 time=1.70 ms

--- 192.168.1.138 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 1.658/1.830/2.008/0.153 ms

```

**Comment by dmiller-nmap** [comment] 2022-06-29 22:52
Thanks for this report. This is a known issue and we are continuing to make improvements to address it. Closing this issue as a duplicate of #92.

**Closed by dmiller-nmap** 2022-06-29 22:52 UTC
Labels: Nmap
