### ISSUE TITLE
Npcap: Arp packets sent to local machine doesn't send to by upper windows protocol layers.

### ISSUE THREAD

**Issue by rbeex** [nmap/nmap#1548] opened 2019-04-10 15:38 UTC
Hi all.

We have a user mode tcp/ip stack and an virtual network interface implemented as a miniport driver. On the local machine we do a windows command line "ping" to the user mode tcp/ip stack and it replies with wpcap. With npcap the ping doesn´t reply. In wireshark i see the arp request and the arp response send by our user mode tcp/ip stack. But after response the windows arp table didn´t have an entry for the requested ip address. It seems that the injected arp packet doesn´t send to the upper windows protocol layers by npcap. Is my assumption correct?

Thanks in advantage.

**Comment by dmiller-nmap** [comment] 2019-09-04 22:59
Related #1343

**Comment by dmiller-nmap** [comment] 2020-01-09 20:04
Thanks for reporting this. I have written a full description of a feature that can help address this issue in #1343. I will be closing this as a duplicate of that issue.

**Closed by dmiller-nmap** 2020-01-09 20:04 UTC
Labels: Npcap
