### ISSUE TITLE
BSOD Npcap 0.995 WIN/10

### ISSUE THREAD

**Issue by tjtraylor** [nmap/nmap#1675] opened 2019-08-02 17:34 UTC
Installed Npcap with latest Wireshark.  Started BSOD on sleep/shutdown/restart.  Could not do restore point backout.  BSOD on uninstall attempts.  BSOD on attempt to install latest Npcap 0.9982.  How do I remediate this issue?  Any help would be appreciated.

[080219-64140-01.dmp.txt](https://github.com/nmap/nmap/files/3462354/080219-64140-01.dmp.txt)

Terry

**Comment by fyodor** [comment] 2019-08-02 17:53
Hi Terry.  Can you try the 0.9982 install again?  The first time it may crash, but hopefully the second time (after reboot) it will work. If that doesn't work, please try these instructions:

1. In an Administrator command shell, run: sc.exe config npcap start=disabled
2. If Npcap was installed in WinPcap API-compatible mode, also run: sc.exe config npf start= disabled
3. Reboot. There may be one more BSoD crash at this point, but it will be the last one.
4. Run the Npcap installer to upgrade Npcap, or uninstall it via "Add or Remove Programs" control panel. Since the service is disabled, it can safely be removed.

Please add a comment to let us know how this works out.  Thanks!  I'm marking this as closed as a duplicate of #1626 .

**Closed by fyodor** 2019-08-02 17:53 UTC

**Comment by tjtraylor** [comment] 2019-08-02 21:16
That worked.  Thanks a bunch.

**Comment by Lounarok** [comment] 2019-08-06 03:54
I found there is aother case will cause bsod when uninstalled npcap 0.995. Which is caused by avast.
1. Stop npcap services ( npcap & npf )
2. Restart computer ( will cause bsod )
3. Uninstall npcap
4. BSOD will show up while uninstalling

Repeat from 1~3 but I still got bsod.
Untill I uninstall avast, then uninstalling npcap 0.995 is gracefully done.

Leave a comment here in case there if others encounter this situation.
Latest wireshark somehow uses npcap 0.995 as default installing...

**Comment by qai9ar** [comment] 2019-08-14 19:41
As Lounarok said that the problem from avast,
I faced the problem while uninstalling npcap 0.995, Rebooting.
But i followed fyodor instructions then it worked.
Without deleting Avast!

**Comment by StewAlexander-com** [comment] 2020-10-02 14:33
Every time I try to use nmap it creates a BSOD on my WIndows 10 system, looks like it causes the tcp.sys driver to bork

I used chocolatey to install nmap, any ideas?

**Comment by dmiller-nmap** [comment] 2020-10-02 19:24
@StewAlexander-com This thread is for a closed issue. Your issue is being addressed in #2134 .
