### ISSUE TITLE
Not captures packets through the loopback

### ISSUE THREAD

**Issue by duhovich** [nmap/nmap#1205] opened 2018-05-01 17:20 UTC
When I enter the command ping 127.0.0.1, in Wireshark there is no result. When I enter 127.255.255.255 the request is visible.
[DiagReport-20180501-201014.txt](https://github.com/nmap/nmap/files/1964593/DiagReport-20180501-201014.txt)
When I installed npcap, first there was an error "Failed to create the npf service for win7, win8 and win10". Then I started the installer again and everything was install.

**Comment by ulbre** [comment] 2018-06-12 04:42
I am having the same issue, but I don't remember that there was an issue during installation.
[DiagReport-20180612-063421.txt](https://github.com/nmap/nmap/files/2092563/DiagReport-20180612-063421.txt)
[install.log](https://github.com/nmap/nmap/files/2092564/install.log)

**Comment by dmiller-nmap** [comment] 2018-07-04 21:39
Loopback capture is only supported by Npcap in native install mode. Wireshark prefers the WinPcap API mode if it is available, which does not support loopback capture. If you install Npcap **without** the "WinPcap API-compatible mode" box checked, it will work.

Duplicate of #1244

**Closed by dmiller-nmap** 2018-07-04 21:39 UTC
Labels: Npcap, bug
