### ISSUE TITLE
Removed from FreeBSD ports tree, because of python27 dependency which one EOLed

### ISSUE THREAD

**Issue by rosso-** [nmap/nmap#2392] opened 2021-11-08 10:50 UTC
Python27 dependency is deprecated

`cd /usr/ports; make quicksearch name=zenmap`

It should be installable

 - OS: [FreeBSD workstation 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0 releng/13.0-n244760-940681634ee]
 - Zenmap removed on 2020-03-01
 - Output of `nmap --version`:
Nmap version 7.91 ( https://nmap.org )
Platform: amd64-portbld-freebsd13.0
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1k-freebsd nmap-libssh2-1.9.0 libz-1.2.11 libpcre-8.45 nmap-libpcap-1.9.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select

**Comment by fyodor** [comment] 2021-11-08 14:41
Duplicate of #1176 .

**Closed by fyodor** 2021-11-08 14:41 UTC
Labels: Zenmap

**Comment by goarblt** [comment] 2022-04-11 15:22
hello
https://www.evil.com/
