### ISSUE TITLE
Npcap Vn 0.9989 causes NIC General Failure

### ISSUE THREAD

**Issue by Hal2000v3** [nmap/nmap#1998] opened 2020-04-11 13:26 UTC
Build Information:
(This from the previous working version of Wireshark/Npcap)...

Version 3.2.2 (v3.2.2-0-ga3efece3d640) 
Copyright 1998-2020 Gerald Combs <gerald@wireshark.org> and contributors. License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.html> This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
Compiled (64-bit) with Qt 5.12.6, with WinPcap SDK (WpdPack) 4.1.2, with GLib 2.52.3, with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.15.0, with Lua 5.2.4, with GnuTLS 3.6.3 and PKCS #11 support, with Gcrypt 1.8.3, with MIT Kerberos, with MaxMind DB resolver, with nghttp2 1.39.2, with brotli, with LZ4, with Zstandard, with Snappy, with libxml2 2.9.9, with QtMultimedia, with automatic updates using WinSparkle 0.5.7, with AirPcap, with SpeexDSP (using bundled resampler), with SBC, with SpanDSP, with bcg729. 
Running on 64-bit Windows 7 Service Pack 1, build 7601, with Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (with SSE4.2), with 16336 MB of physical memory, with locale English_United Kingdom.1252, with light display mode, without HiDPI, with Npcap version 0.9986, based on libpcap version 1.9.1, with GnuTLS 3.6.3, with Gcrypt 1.8.3, with brotli 1.0.2, without AirPcap, binary plugins supported (19 loaded). Built using Microsoft Visual Studio 2019 (VC++ 14.24, build 28316). 
Wireshark is Open Source Software released under the GNU General Public License. 
______________________________________________________________________
The latest version of Npcap (0.9987(?) bundled with Wireshark Vn 3.2.3) causes a General Failure on my NIC card (Intel 82579V Gigabit Network Connection, Driver 11.13.51.0 built by WinDDK).

Uninstalling Npcap or reverting to this previous version (64-bit Wireshark Vn 3.2.2, Npcap Vn 0.9986) gives me a functioning NIC card - hence I can post this bug report.

**Comment by MrSmite** [comment] 2020-04-12 00:38
Same problem here.

Win 7 had "limited access" on my wireless adapter after reboot. Uninstalling Npcap fixed the problem.

**Comment by RadarNyan** [comment] 2020-04-12 11:57
Same for me, 

Npcap works after installation, but after reboot network is down (General Failure)

Realtek GbE RTL8168 / Windows 7 SP1 64-bit / npcap-0.9990

**Comment by erasmo52** [comment] 2020-04-12 18:37
I had same problem upgrading wireshark from 3.2.2 to 3.2.3. It install npcap 0.989.
Same problem installing npcap 0.990. For both the installation stop with the error:  "A LWF & WFP driver installation tool has stopped working". Installing the npcap 0988 all work fine, it is the last release installing and working fine.
Where is the problem?
Thanks for your attention.

**Comment by doomgod** [comment] 2020-04-16 10:50
Same problem here. Windows 7 SP1 x64, fully updated to april 2020.
IPv4: No network access - after a reboot. The chip is Intel 82579V. CPU: Core i7-4960X
The only option selected was WinPCap compatible mode.

**Comment by samuel-jimenez** [comment] 2020-04-20 11:58
Windows 7 SP1 x64.

Having the Npcap Packet Driver enabled for an ethernet connection prevents it from obtaining an IP address. 

Disabling the driver and performing a release/renew will allow the connection to obtain an IP address, at which point npcap can be re-enabled.

**Comment by Hal2000v3** [comment] 2020-04-20 13:17
Thanks Samuel - do you know if this bug is (going to be) fixed in some future release?  (I notice that Wireshark pushed out another update in the last couple of days, but I haven't tried it yet to see if the included Npcap still has the same problem...)

All the best,  DaveC


At 12:59 20/04/2020, you wrote:

>Windows 7 SP1 x64.
>
>Having the Npcap Packet Driver enabled for an ethernet connection prevents it from obtaining an IP address.
>
>Disabling the driver and performing a release/renew will allow the connection to obtain an IP address, at which point npcap can be re-enabled.
>
>You are receiving this because you authored the thread.
>Reply to this email directly, <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnmap%2Fnmap%2Fissues%2F1998%23issuecomment-616506093&data=02%7C01%7CD.Cannon%40exeter.ac.uk%7C0572149bcec44bc42fde08d7e5224cc0%7C912a5d77fb984eeeaf321334d8f04a53%7C0%7C0%7C637229807807272175&sdata=H6UQcflfjXl1kpULB0JCbIUdMMvUc3zEtCEYtbYj6QQ%3D&reserved=0>view it on GitHub, or <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPEPZTZ6KBXIODY76N6433TRNQ2ILANCNFSM4MF73KDA&data=02%7C01%7CD.Cannon%40exeter.ac.uk%7C0572149bcec44bc42fde08d7e5224cc0%7C912a5d77fb984eeeaf321334d8f04a53%7C0%7C0%7C637229807807282122&sdata=VSvCi2yQJejwuZBBVk6zvoou08slzzwkYCB0ddbNWpo%3D&reserved=0>unsubscribe.


-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dmiller-nmap** [comment] 2020-04-20 16:11
We optimistically removed some do-nothing callback functions that NDIS documentation lists as "optional." This has caused problems on Windows 7 in the past, but we were hopeful that intervening changes would make it possible to remove them. We will restore these in the next release. Please update this issue if updating to a version of Npcap newer than 0.9990 solves this problem.

**Comment by lenlynch** [comment] 2020-04-20 20:07
Just installed 0.9990 win7 x64, if the driver shim is enabled on an interface, it fails operation.  Disabling the shim returns operation.  Just before installing 0.9990, Earlier today, noticed that 0.9989 was causing this same issue, and decided to try 0.9990.  No joy, unfortunately.

**Comment by LurkingKiwi** [comment] 2020-04-29 00:16
Same problem, Win7 x64, 0.9989 and .9990 cause DHCP failure on reboot.

**Comment by guyharris** [comment] 2020-04-29 03:10
> We optimistically removed some do-nothing callback functions that NDIS documentation lists as "optional." This has caused problems on Windows 7 in the past, but we were hopeful that intervening changes would make it possible to remove them. We will restore these in the next release. Please update this issue if updating to a version of Npcap newer than 0.9990 solves this problem.

If this fixes the problem, perhaps you should report a bug in the NDIS documentation.

**Comment by Astrobirder** [comment] 2020-04-29 15:25
Same issue here, Win 7 Pro, Intel i219 card.  and a USB NIC as well.  Workaround that might help until you get a new version, which works for me:

If it helps, you can disable npcap on the interface (i.e. uncheck it, close the options page), do a ping to a device on the net that is affected, and then reopen the interface options page, recheck npcap and it seems to get around the issue.

**Comment by shixudong2020** [comment] 2020-05-01 15:21
> 
> 
> We optimistically removed some do-nothing callback functions that NDIS documentation lists as "optional." This has caused problems on Windows 7 in the past, but we were hopeful that intervening changes would make it possible to remove them. We will restore these in the next release. Please update this issue if updating to a version of Npcap newer than 0.9990 solves this problem.

Contribute a proven idea：
modify duplex  and speed mode from auto-negotiate  to Definite speed also solve the bug

**Comment by dmiller-nmap** [comment] 2020-05-05 15:18
@shixudong2020 Thanks for the idea. It seems very likely that the interruption is due to a mishandling of NDIS status indications related to connection speed, so we will be investigating that separately. See #2034.

**Comment by dmiller-nmap** [comment] 2020-05-05 15:19
Npcap 0.9991, released yesterday, should resolve this issue. Please open a new issue if it recurs.

**Closed by dmiller-nmap** 2020-05-05 15:19 UTC

**Comment by RadarNyan** [comment] 2020-05-06 08:23
I can confirm that npcap 0.9991 solves the problem for me, also it doesn't have the BSOD bug presented in 0.9988. Network & npcap works fine after reboot / wake from sleep.

(Realtek GbE RTL8168 / Windows 7 SP1 64-bit)
