### ISSUE TITLE
vnc.lua / vnc-brute error

### ISSUE THREAD

**Issue by ttillaume** [nmap/nmap#1706] opened 2019-08-23 07:16 UTC
Hi

I tried vnc-brute to my test server but couple of errors appeared like below.
What should I do for this?

=============================================================

wpcap.dll present, library version: Npcap version 0.9982, based on libpcap version 1.9.1-PRE-GIT

Starting Nmap 7.80 ( https://nmap.org ) at 2019-08-23 16:03 ´eCN¹I±¹ C￥AØ½A

--------------- Timing report ---------------

  hostgroups: min 1, max 100000

  rtt-timeouts: init 1000, min 100, max 10000

  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000

  parallelism: min 0, max 0

  max-retries: 10, host-timeout: 0

  min-rate: 0, max-rate: 0

---------------------------------------------

NSE: Using Lua 5.3.

NSE: Arguments from CLI: 

NSE: Loaded 1 scripts for scanning.

NSE: Script Pre-scanning.

NSE: Starting runlevel 1 (of 1) scan.

Initiating NSE at 16:03

Completed NSE at 16:03, 0.00s elapsed

Initiating Ping Scan at 16:03

Scanning 192.168.1.114 [4 ports]

Packet capture filter (device eth0): dst host 10.226.141.90 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 192.168.1.114)))

We got a ping packet back from 192.168.1.114: id = 10890 seq = 0 checksum = 54645

Completed Ping Scan at 16:03, 0.20s elapsed (1 total hosts)

Overall sending rates: 5.10 packets / s, 142.86 bytes / s.

DNS resolution of 1 IPs took 0.02s. Mode: Async [#: 0, OK: 0, NX: 0, DR: 0, SF: 0, TR: 0, CN: 0]

Initiating SYN Stealth Scan at 16:03

Scanning 192.168.1.114 [1 port]

Packet capture filter (device eth0): dst host 10.226.141.90 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 192.168.1.114)))

Discovered open port 5900/tcp on 192.168.1.114

Completed SYN Stealth Scan at 16:03, 0.00s elapsed (1 total ports)

Overall sending rates: 1000.00 packets / s, 44000.00 bytes / s.

NSE: Script scanning 192.168.1.114.

NSE: Starting runlevel 1 (of 1) scan.

Initiating NSE at 16:03

NSE: Starting vnc-brute against 192.168.1.114:5900.

**NSE: vnc-brute against 192.168.1.114:5900 threw an error!

C:\Program Files (x86)\Nmap/nselib/vnc.lua:251: bad argument #2 to 'insert' (position out of bounds)

stack traceback:

	[C]: in function 'table.insert'

	C:\Program Files (x86)\Nmap/nselib/vnc.lua:251: in method 'handshake'

	C:\Program Files (x86)\Nmap/scripts\vnc-brute.nse:114: in method 'check'

	C:\Program Files (x86)\Nmap/nselib/brute.lua:988: in method 'start'

	C:\Program Files (x86)\Nmap/scripts\vnc-brute.nse:149: in function <C:\Program Files (x86)\Nmap/scripts\vnc-brute.nse:140>

	(...tail calls...)**

Completed NSE at 16:03, 0.01s elapsed

Nmap scan report for 192.168.1.114

mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers

Host is up, received echo-reply ttl 126 (0.0010s latency).

Scanned at 2019-08-23 16:03:26 ´eCN¹I±¹ C￥AØ½A for 0s

PORT     STATE SERVICE REASON

5900/tcp open  vnc     syn-ack ttl 126

Final times for host: srtt: 1000 rttvar: 3750  to: 100000

NSE: Script Post-scanning.

NSE: Starting runlevel 1 (of 1) scan.

Initiating NSE at 16:03

Completed NSE at 16:03, 0.00s elapsed

Read from C:\Program Files (x86)\Nmap: nmap-payloads nmap-services.

Nmap done: 1 IP address (1 host up) scanned in 1.71 seconds

           Raw packets sent: 2 (72B) | Rcvd: 2 (72B)

**Comment by ttillaume** [comment] 2019-08-27 05:01
Thank you so much.

**Comment by nnposter** [comment] 2019-09-08 01:09
The issue is definitely **not** related to #1707

**Comment by nnposter** [comment] 2019-09-08 01:27
A fix has been committed as r37734. Please report back if the issue persists.

**Closed** 2019-09-08 02:09 UTC
Labels: NSE, bug
