### ISSUE TITLE
Npcap 0.92 fails to install in WinPcap API Compatible Mode

### ISSUE THREAD

**Issue by davemidd** [nmap/nmap#906] opened 2017-06-13 14:03 UTC
I previously had 0.91 installed (in Winpcap API Compatible Mode).
Windows 10 64 bit.
Installing 0.92 shows the following error on screen - ![image](https://user-images.githubusercontent.com/1181083/27086061-f51878e8-5048-11e7-91c9-7a484a2f0e5b.png)

Install log attached - [NPFInstall.log.txt](https://github.com/nmap/nmap/files/1071637/NPFInstall.log.txt)

If I un-select WinPcap API Compatible Mode then installation does complete ok.

**Comment by davemidd** [comment] 2017-06-13 14:12
I just noticed also that the installer has a message that WinPcap is installed, although it isn't actually installed. Related?

![image](https://user-images.githubusercontent.com/1181083/27086616-9e19cb6c-504a-11e7-975f-765178ef718d.png)

**Comment by dmiller-nmap** [comment] 2017-06-15 16:39
Thanks for the report, we'll start looking at it.

**Comment by BigbyBoss** [comment] 2017-06-26 12:25
Yup, same issue here.

**Comment by dmiller-nmap** [comment] 2017-06-26 20:04
@BigbyBoss Can you also provide NPFInstall.log? Is the error number identical?

**Comment by BigbyBoss** [comment] 2017-06-26 23:52
@dmiller-nmap Added it to my previous comment.

**Comment by dmiller-nmap** [comment] 2017-07-07 22:17
Ok, it looks like the problem is that you have WinPcap (not Npcap) installed in some way that Npcap is unable to clean up. The "WinPcap API-compatible mode" is intended to completely replace WinPcap (instead of installing as Npcap with all Npcap features), so if we can't uninstall WinPcap, we can't safely install in WinPcap API-compatible mode.

Can you provide the output of [DiagReport](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport) that will help us identify why the installer thinks WinPcap is installed? Maybe there is something that must be manually removed.

**Comment by BigbyBoss** [comment] 2017-07-07 22:21
@dmiller-nmap I tried installing again a few days ago, expecting a change. And i actually managed to install it just fine this time. I got no warning stating i have WinPcap installed and the installation itself was successful.

Still, here's my DiagReport if it's of any use now.

[DiagReport-20170708-001913.txt](https://github.com/nmap/nmap/files/1132494/DiagReport-20170708-001913.txt)

**Comment by davemidd** [comment] 2017-07-07 22:24
Thanks @dmiller-nmap 
I don't have WinPcap installed; I removed it when I first installed Npcap a few revisions ago.
It's only this last rev where there's been these problems.
Here's my DiagReport:

[DiagReport-20170707-232033.txt](https://github.com/nmap/nmap/files/1132496/DiagReport-20170707-232033.txt)

David

**Comment by EJMarr** [comment] 2017-07-08 10:59
I too have the same problem after the Creator update, with the installation failing. It complains that winpcap is installed (It is not, I have been using npcap in winpcap compatibility mode), then it halts when failing to uninstall Winpcap. After a clean install without compatibility selected, and an uninstall, it still failed.

Here are the logs, from using DiagReport, and near the end are mentioned four winpcap related files, dating back to when I installed winpcap when I was trying to understand why an application using npcap was not working (that was entirely my fault). Deleting the files from C:Windows\SysWOW64 seems to have cleared the problem. Files were NpcapHelper.exe, Packet.dll, WlanHelper.exe and wpcap.dll.

[DiagReport-20170708-112649.txt](https://github.com/nmap/nmap/files/1132898/DiagReport-20170708-112649.txt)

[install.txt](https://github.com/nmap/nmap/files/1132900/install.txt)

Ed

**Comment by sinfulgurotesque** [comment] 2017-07-13 21:37
I also started having this problem after the Creator Update. It installs fine if I don't try to install in WinPcap API-compatible mode. 

[DiagReport-20170713-162747.txt](https://github.com/nmap/nmap/files/1146714/DiagReport-20170713-162747.txt)

**Comment by EJMarr** [comment] 2017-07-14 07:53
Try uninstalling the standard version of npcap, then look for the files in C:Windows\SysWOW64 (NpcapHelper.exe, Packet.dll, WlanHelper.exe and wpcap.dll.). If they are there delete them, then try installing API-compatible version  (this worked for me).

**Comment by dmiller-nmap** [comment] 2017-07-15 01:03
@EJMarr Thanks especially for the `install.log`, but I don't see there where an error ocurred. Also, this appears to be an install of Npcap 0.86, not 0.92.

@sinfulgurotesque @davemidd @BigbyBoss Do any of you have [an `install.log` file](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-installation-log) from right after the error occurs? We would really like to get to the bottom of this and fix it.

**Comment by sinfulgurotesque** [comment] 2017-07-15 03:08
@EJMarr That worked you wonderful, beautiful bastard.

**Comment by EJMarr** [comment] 2017-07-15 07:32
Here's an install log that I recovered from Deleted Files. I don't have a DiagReport to go with this one, as I first needed a successful install to get the utility available (bit of a bootstrap problem there). It is 0.92, in WinPCap compatible mode, and it did fail.

[install 10-22.log.txt](https://github.com/nmap/nmap/files/1150155/install.10-22.log.txt)

**Comment by dmiller-nmap** [comment] 2017-07-17 17:12
Linking to discussion on the nmap-dev mailing list: http://seclists.org/nmap-dev/2017/q3/44

**Comment by TomSellers** [comment] 2017-07-18 22:15
I can confirm that @EJMarr 's solution worked for me as well.  Windows 10, all latest patches.  While upgrading from Nmap 7.30 to 7.50 the bundled Npcap 0.91 installer failed.  I restarted and removed all traces of Winpcap from Add/Remove Programs, disk, and the registry. No luck.  Tried Npcap 0.92 same issue.
In all cases the installer would indicate that it detected that Winpcap was installed when it wasn't.  I removed the files as @EJMarr  indicated and the installer completed.

Note: I also have Wireshark installed which required Winpcap.

I've verified that both Wireshark and Nmap work after successfully installing Npcap 0.92.

**Comment by dmiller-nmap** [comment] 2017-07-19 02:48
The issue appears to be that the Creators Update "reinstalls" Windows drivers. The diff from DiagReport before and after the install is attached.
[creators-diff.txt](https://github.com/nmap/nmap/files/1157820/creators-diff.txt)

The essential changes are as follows:
* Removed Npcap Loopback Adapter
* Removed all non-standard values from the `HKLM:\SYSTEM\CurrentControlSet\Services\npcap` Registry key.
* Changed the "Start" type for the npcap service to 3 (Manual) from 1 (System)
* Removed the `npcap_wifi`, `npf`, and `npf_wifi` service Registry keys

**Comment by dmiller-nmap** [comment] 2017-07-31 18:16
Everyone who reported this issue: thank you! Please try Npcap 0.93, which
should resolve this issue. Applying it before the Creators Update ought to
prevent the broken installation, and the installer should safely recover
and reinstall if you already are experiencing this issue.

Please let us know how it works for you!

**Comment by TheKevJac** [comment] 2017-08-16 14:44
for me... it dont work

**Comment by ITSecMedia** [comment] 2017-08-24 07:16
Tried to install **npcap-0.93** two times today, after successful uninstall of **npcap-0.83**.

Both times installation failed with error message -> windows restore point gets recovered before installation, but afterwards it was installed ?

I then had to de-install it from windows "Apps & features" too, just to get sure I have no broken/corrupt installation on my machine.

**Comment by dmiller-nmap** [comment] 2018-07-03 18:48
Recommended procedure for this issue:

1. install Npcap in WinPcap API-compatible mode. WinPcap-related files will be overwritten.
2. Reinstall Npcap with whatever options you need. WinPcap-mode files will be removed prior to installation.

I am closing this issue. For problems with Npcap installations not working after applying Windows feature updates (version upgrades), see #998.

**Closed by dmiller-nmap** 2018-07-03 18:48 UTC
Labels: Npcap, bug
