### ISSUE TITLE
The network cannot connect after changing certain properties of the network adapter

### ISSUE THREAD

**Issue by 15092368540** [nmap/nmap#1985] opened 2020-04-01 16:20 UTC
must be turned off NPCAP Driver in the local connection properties Settings window, Then close the local connection properties window, Reopen the local connection properties window and enable NPCAP Driver, So the network goes back to normal
![12](https://user-images.githubusercontent.com/49462433/78161233-b97b0980-7477-11ea-92f8-33b740d2c42c.png)

**Comment by Permission13** [comment] 2020-04-04 22:38
Guess it matches better here:

Ill join this report. If you want  a separate one because you feel its different just tell me ;)
Win7 64 with D-Link USB Wifi Adapter. Upgraded from .9983 to .9989.
Wifi not connecting anymore, 0 packets, 169.*.*.* IP assigned
Not Errors in Event Log.
Starts exchanging packets as soon as i deactivate the NPCAP packet driver in the wifi connection properties . Wifi continues to work if i reactivate the NPCAP driver afterwards - but just until the next reboot.
Installed with only "WinPcap Compatible" option selected.
https://www.dropbox.com/s/04537cjty2q4rx9/DiagReport-20200329-175753.txt?dl=0

Update 1:
-Even with definitely installing the update without "NPCap Loopback Adapter" it was still installed or didnt get removed from probably an old installation
-Another thing which was bound to my Wifi was "ANOD network security filter driver" from the D-Link drivers.
Removed both and reinstalled NPCAP => Seemed to work.

Update2: Getting angry.
Phenomenon came back the next day. Now i also deactivated Virtual Box NDIS6 Bridged Driver.
=> No packets until i deactivate NPCAP.

If you need sth special just drop me a note here

**Comment by dmiller-nmap** [comment] 2020-05-05 18:50
This is most likely a duplicate of #2030, which we believe to be resolved in Npcap 0.9991. Please let us know if the problem persists.

**Closed by dmiller-nmap** 2020-05-05 18:50 UTC
