### ISSUE TITLE
Upgrade Nmap's PCRE library (libpcre) to pcre2

### ISSUE THREAD

**Issue by cpaelzer** [nmap/nmap#1335] opened 2018-09-26 11:39 UTC
Hi,
pcre2 was not mentioned commits nor on the mailing lists nor the issue tracker that now is mirrored to GH, unless I missed something.

pcre2 is available since [early 2015](https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html) and projects could start considering it stable, but due to a change in the API it usually is more than just changing the include being used.
pcre (8.x) continues to exists, but as bugifx only stream and any new features/development are going into pcre2 (10.x).

Therefore Ubuntu would like to demote pcre in favor of [pcre2](https://www.pcre.org/) at some point, but Nmap (among other pkgs) would need to be ported to use pcre2.

Therefore I wanted to ask if there are any plans to do so (or not) in your project?
If there is none yet, please feel free to use this issue to track it.

**Comment by dmiller-nmap** [comment] 2018-09-28 04:05
Thanks for suggesting this. The Nmap Project currently has no plans to update to PCRE2, but we have no immediate objections. However, these are our questions that would have to be answered before we commit to an upgrade:

1. Will all of our tens of thousands of existing regular expressions match the same strings that they did under original PCRE?
2. Does PCRE2 build and run on the platforms we need it to? Platforms officially supported by Nmap include GNU/Linux, Windows, Solaris, AIX, and FreeBSD, among others.
3. Has performance been negatively impacted for our specific use case? We compile tens of thousands of regular expressions and then attempt to find the one that matches some untrusted input, for up to several thousand inputs in succession.

There may be other concerns, but these are the primary ones I can think of.

**Comment by cpaelzer** [comment] 2018-09-28 06:10
Hi,
thanks for your answer @dmiller-nmap all concerns sound very reasonable.
First of all I'm not an pcre expert at all, just trying to understand/coordinate various projects position to prce2 from a Distributions perspective.
Therefore I'm trying to answer your concerns to my best knowledge, but do not really feel authoritative to do so- upstream pcre might be the right place to check these I'd think.

1. AFAICT the API changed but not the Rules. There are new constants that can be added to modify the behavior of rules but I'd expect the rules to match the same. [News](https://www.pcre.org/news.txt) and [Changelog](https://www.pcre.org/changelog.txt) are meant to give a high level overview and I found nothing suggesting that rules would behave differently.
1. Sorry I don't know, but again I have not found anything in upstreams statements that ould sugegst that pcre2 would be inferior in that regard. Via search engines I found pcre2 builds for all platforms you named, so I'd think yes - the same platforms are supported.
1. Well given that any new development since 2015 is in pcre2 I'd hope that if anything it got better there.

As I said, I'm the middle man in this case.
I'm moore "trying to track your intention and status" than "trying to convince" you on this.

**Comment by fyodor** [comment] 2022-06-20 17:53
Thanks for opening this issue (back in 2018), @cpaelzer.  I agree that we should probably upgrade to pcre2.  We might first upgrade to the latest libpcre (pcre1) since that will be easier.  The issue for that is #2250.

**Comment by XWwalker** [comment] 2023-01-04 03:16
Hi, is nmap planning to switch PCRE2 recently? I would like to know the exact time to switch PCRE2, or nmap release version.

**Comment by david-geiger** [comment] 2023-04-19 03:33
Hi,

Some distributions, like us Mageia Linux, now started to drop old pcre library from their mirrors.

Regards,
David

**Comment by XWwalker** [comment] 2023-06-19 02:03
Hi,  I have added a new PR that supports pcre2 compilation, please check and merge.

**Comment by hillu** [comment] 2023-07-02 13:59
Debian has marked all reverse dependencies on pcre3 as release-critical which means nmap will soon be auto-removed from the testing distribution. See [#1000012](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000012).

**Comment by fyodor** [comment] 2023-07-03 20:04
Thanks for the note, @hillu.  We finished and checked in our PCRE2 upgrade last week, including testing on Linux, Mac, and Windows.  It will be in the next Nmap release.  We don't have an exact date scheduled for that release, but it will probably be in August or September.

**Comment by hillu** [comment] 2023-07-07 07:39
> If Debian needs it before then, perhaps you could cherry-pick the changes from GitHub?

I've done just that, thanks.

**Comment by yselkowitz** [comment] 2023-07-11 13:28
RHEL 10 also plans on dropping support for classic pcre, and Fedora will certainly drop it in due course.

**Comment by iasdeoupxe** [comment] 2023-07-12 21:18
> 1. Will all of our tens of thousands of existing regular expressions match the same strings that they did under original PCRE?

There could be some compatibility problems depending on the used regex. For example this was valid PCRE:

```
^[[:alnum:]-_.]+$
```

which would need to be one of these in PCRE2 (hypen escaped or at the very first or last position):

```
^[[:alnum:]_.-]+$
^[-[:alnum:]_.]+$
^[[:alnum:]\-_.]+$
```

References:
- https://gitlab.gnome.org/GNOME/glib/-/issues/2760
- https://www.pcre.org/current/doc/html/pcre2pattern.html#SEC9

**Comment by dmiller-nmap** [comment] 2024-01-29 18:15
We updated the code back in 828ab48764b82d0226e860c73c5dac5b11f77385. We are keeping this issue open until we have the Windows and macOS builds confirmed working.

**Comment by dmiller-nmap** [comment] 2024-02-28 18:26
Windows build works fine. Closing this issue, since the macOS builds will be dealt with in release prep.

**Closed by dmiller-nmap** 2024-02-28 18:26 UTC
Labels: enhancement, question, Nmap
