### ISSUE TITLE
ncat throws "Input/Output" error when run as root.

### ISSUE THREAD

**Issue by le-jawa** [nmap/nmap#2241] opened 2021-02-03 19:01 UTC
**Describe the bug**
I use ncat in scripts to test connections before establishing the connection; have been for quite a while.  Recently, one of those scripts kept failing on the ncat check for a CIFS connection (port tcp/445).  In the script's log, I found "Ncat: Input/output error."  After a lot of troubleshooting, I discovered that when I run Ncat with my account, everything works fine.  When run as root (whether logged into root or just using sudo) the connection fails with the above error.  If I just run Ncat once (as my script does), it fails almost every time.  If I run it several times in a row, the failure rate is about 10%.

The CIFS server I'm connecting to is a Buffalo Terastation 5410 (NAS), presumably running Samba.

**To Reproduce**
1.  As an unprivileged user, run ncat -i5 -w5 <windows/samba hostname> 445.  Ncat will connect successfully and quit with the message "Ncat: Idle timeout expired (5000 ms).
2. As root, run the same command.  Chances are you'll get the Input/Output error.  If you don't get it right off, run the command manually a few times and you should see it.
3. Write a small script to loop execution of the same command many times (I used 100). 
4. Run the script as the unprivileged user; it will successfully connect every time.
5. Run the same script as root, it will fail between 5% and 10% of the time.   

**Expected behavior**
Ncat should connect every time when run with root privileges.

**Version info (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003 (Core)
 - Output of `ncat --version`:
     - Original Centos 7.8 install: Ncat: Version 7.50 ( https://nmap.org/ncat )
     - Package downloaded from nmap.org and installed: Ncat: Version 7.91 ( https://nmap.org/ncat )

**Additional context**
Other troubleshooting I performed:

- Since I know RHEL/CentOS keeps the same versions of most programs around for the entire 10-year lifetime of the system, and since CentOS 7 is about 6 1/2 years old, I tested with a newer version of Ncat, to see if perhaps this had been addressed since 7.50.  Unfortunately, that had no effect; I got the same error either way.
- Restarted the file share service on the NAS.  No effect.
- Rebooted the NAS, no effect
- Rebooted the server, no effect
- Played around with different ways of running the command (with variable for the hostname, redirecting output, storing output in a variable, etc).  No effect.

Additional Server info:
- I ran nmap's smb-protocols script against the server, and it reported that SMB2.1 and higher were supported.
    - Host script results:
        | smb-protocols:
       |   dialects:
       |     2.10
       |     3.00
       |     3.02
       |_    3.11
- smbclient couldn't get detailed info about the NAS (again, SMB1 not supported), but I did get this:
    - 	Sharename       Type      Comment
	---------           ----       -------
        ...
        IPC$                 IPC        IPC Service (TeraStation)

The NAS runs Buffalo's own Linux build, so I'd expect this to be Samba, but since it doesn't identify itself as such, it's hard to say.

Edit: Added additional server info.

**Comment by nnposter** [comment] 2021-02-03 21:44
FWIW, I have used stock Samba on Kali, 4.13.3+dfsg-1, as the target and stock Ubuntu 18.04 as the client, but I was not able to reproduce your issue:
```
# id
uid=0(root) gid=0(root) groups=0(root)
# (for (( i=0; i<100; ++i)) ; do ncat -i5 -w5 -v 192.168.46.131 445 2>&1; done) | sort -u
Ncat: Connected to 192.168.46.131:445.
Ncat: Idle timeout expired (5000 ms).
Ncat: Version 7.80SVN ( https://nmap.org/ncat )
#
```
You will need to keep digging into your environment specifics.

**Comment by le-jawa** [comment] 2021-02-03 22:16
As I pointed out in my post, this was on CentOS 7, not Ubuntu 18.04.  That said, yes I am still looking; I don't want to just dump this on the project and wash my hands of it.

**Comment by le-jawa** [comment] 2021-02-10 22:26
Continuing to dig into this, and I can confirm a few things:

- This isn't unique to port 445; it happens on any port.
- It happens regardless of the service or OS on the other end.  I tested against Ubuntu 14.04 (I found out that was what the NAS was running) and CentOS.

I ran several tests with debugging turned on (-vvv) and get this when it errors out:
```

Ncat: Version 7.91 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_tcp(): TCP connection requested to <peer.ip>:22 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 8 [<peer.ip>:22]
Ncat: Connected to <peer.ip>:22.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #2)
libnsock nsock_read(): Read request from IOD #1 [<peer.ip>:22] (timeout: -1ms) EID 18
libnsock nsock_readbytes(): Read request for 0 bytes from IOD #2 [peer unspecified] EID 26
libnsock nsock_timer_create(): Timer created - 2000ms from now.  EID 36
libnsock nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 18 [<peer.ip>:22] (21 bytes): SSH-2.0-OpenSSH_8.0..
SSH-2.0-OpenSSH_8.0^M
libnsock nsock_readbytes(): Read request for 0 bytes from IOD #1 [<peer.ip>:22] EID 42
libnsock nsock_event_cancel(): Event #36 (type TIMER) cancelled
libnsock nevent_delete(): nevent_delete on event #36 (type TIMER)
libnsock nsock_timer_create(): Timer created - 2000ms from now.  EID 52
**libnsock nsock_trace_handler_callback(): Callback: READ ERROR [Input/output error (5)] for EID 26 [peer unspecified]
Ncat: Input/output error.**
```

I've also got packet captures, but I haven't been able to analyze them yet.  I'll post my findings here when I do.

**Comment by nnposter** [comment] 2021-02-10 23:05
I believe that EID 26 is a read op from your local input, not from the target, so that's where your might want to focus. (It also supports your observation that the type of target seems irrelevant.)

**Comment by le-jawa** [comment] 2021-02-10 23:29
But that's the part that's throwing me and makes me think this is something in ncat - this only happens when it runs as root.  If this were an issue with reading from a socket, then my account would have trouble, but not root.

If this is something local, then what would be the unspecified "peer"?

**Comment by nnposter** [comment] 2021-02-10 23:35
That would be `stdin` (as seen by Ncat), so you should consider what type of terminal, shell or other wrapper is involved when invoking Ncat.

**Comment by nnposter** [comment] 2021-02-11 02:16
I have reread your original use case. If the only objective is to determine whether a given port is open, have you tried to run Ncat as
```
ncat -z -w5 target port
```
instead of
```
ncat -i5 -w5 target port
```
...which avoids the need for the idle timeout (and it is therefore faster) but, more importantly for you, it performs no read/write ops?

**Comment by le-jawa** [comment] 2021-02-11 17:40
No, I hadn't tried it until you mentioned it.  It looks like that will do great; thanks for the tip.

That said, I've tested a few different things in the environment (using the console vs a jump host, sudo vs direct login, etc) and I think I've finally narrowed it down the problem.  It looks like ncat doesn't like being run in the background; this problem occurs when I use` sudo -b`.  Is that a known issue?

**Comment by nnposter** [comment] 2021-02-12 16:56
>  It looks like ncat doesn't like being run in the background

Ncat has no problem being run in the background in general but you need to consider what you are asking Ncat to do. By default, Ncat reads from `stdin`, which it cannot if it is in the background. Consider the following:
```
$ sudo -b cat
$ cat: -: Input/output error
```
It is the same issue.

**Comment by le-jawa** [comment] 2021-02-12 19:37
Right, but in that example, you have deprived the cat of command of `stdin`, where `stdin` is absolutely required.  There is nothing in what I'm doing with that relies on `stdin`.  I pass it a server name and a port and away it goes; I don't pipe or redirect anything.  It gets its input from the network. 

Also, if the problem were the fact that `sudo -b` detaches the program from the terminal, and therefore from `stdin`, then I would expect it to error out very consistently (every single time), but what I'm seeing does not have any sort of consistency to it.  The problem occurs anywhere from **5% to 25%** of the time.  Backgrounding a program does not give access to `stdin` some of the time, and not the rest.

**Comment by nnposter** [comment] 2021-02-12 21:59
> There is nothing in what I'm doing with that relies on `stdin`.

Of course there is. As I said before, Ncat reads from `stdin` by default. If you do not want that, then you should be using redirects or option `--recv-only` (or the previously mentioned `-z`).

**Comment by fyodor** [comment] 2021-02-17 20:34
Thanks for the report and good followup discussion from everyone!  It sounds like the issue with using that command line in that particular context is now understood, and that there are some good alternative ways to accomplish the same.  So I'm marking this as closed for now.  Hopefully people can still find and learn from this issue if and when they need it.  And we can re-open if it there's a concrete proposal to change Ncat in a way that might improve it.

**Closed by fyodor** 2021-02-17 20:34 UTC
Labels: Ncat

**Comment by goarblt** [comment] 2022-04-11 15:18
hello
https://www.evil.com/
