### ISSUE TITLE
Error after running mongodb-databases.nse script 

### ISSUE THREAD

**Issue by moivica** [nmap/nmap#2321] opened 2021-06-14 11:04 UTC
**Describe the current behavior**

mongodb-databases.nse script does not work: errors are thrown after start. 

**Expected behavior**
Script should work without errors. 

Example :  output after start 
![image](https://user-images.githubusercontent.com/31037172/121882545-f8aa1900-cd10-11eb-958c-8352f668e166.png)

Example: debug mode
![image](https://user-images.githubusercontent.com/31037172/121882439-d2847900-cd10-11eb-906c-b445defdf4b9.png)

**Comment by goarblt** [comment] 2022-04-11 15:20
hello
https://www.evil.com/

**Comment by nnposter** [comment] 2022-05-08 01:47
This bug appears to be a duplicate of https://github.com/nmap/nmap/issues/2393, already rectified in fa029ca53127be26c1d6ab2117a3944508c6fa62.

Please refresh your copy of [nselib/mongodb.lua](https://github.com/nmap/nmap/blob/master/nselib/mongodb.lua). Feel free to reopen the issue if the script crash persists.

**Closed by nnposter** 2022-05-08 01:47 UTC
Labels: bug, duplicate, NSE
