### ISSUE TITLE
ubuntu 20.04 LTS support for zenmap

### ISSUE THREAD

**Issue by alcalpcr** [nmap/nmap#2022] opened 2020-04-24 12:52 UTC
Please support Ubuntu 20.04

[according to launchpad](https://launchpad.net/ubuntu/focal/+source/nmap) not available:
`ncat: NMAP netcat reimplementation`
`ncat-dbgsym: debug symbols for ncat`
`ndiff: The Network Mapper - result compare utility`
`nmap: The Network Mapper`
`nmap-common: Architecture independent files for nmap`
`nmap-dbgsym: debug symbols for nmap`
`zenmap: No summary available for zenmap in ubuntu focal`

`apt install zenmap`

The zenmap package is not available, but some other package references
to the. This can mean that the package is missing, obsolete, or just
is available from some other source
However, the following packages replace it:
   ndiff

E: The «zenmap» package does not have a candidate for installation

[Latest version available](https://www.ubuntuupdates.org/package_metas?q=zenmap): 
eoan | universe | base | [7.80+dfsg1-1build1](https://www.ubuntuupdates.org/package/core/eoan/universe/base/zenmap)

Thanks

**Comment by skaox** [comment] 2020-04-29 21:13
Hi,

Zenmap optionally depends on pygtk which depends on libglade which is a python2-gtk2 component not python3-gtk3.
https://forum.manjaro.org/t/no-module-named-gtk-error-while-running-zenmap/35102

Zenmap is not in the ubuntu repository anymore because is not compatible pyhton3-gtk3 we have to wait until they use PyGObject who replace pygtk and is compatible python3.
https://github.com/nmap/nmap/issues/1176
http://pygtk.org <-who's now-> https://pygobject.readthedocs.io

Ubuntu 20.04 when trying to launch zenmap from terminal :

`Could not import the zenmapGUI.App module: No module named gtk.
I checked in these directories:
    /usr/bin
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-x86_64-linux-gnu
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /usr/local/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages/gtk-2.0
    /usr/lib/python2.6/site-packages
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.`

I've tried to find an alternative but...
NmapGUI (java) to old and didn't work with my oracle-java14
Nutty has no ppa for focal at the moment
Nmapsi4 is the only one who's working but a bit old and buggy.

If you know another one don't hesitate ;-!

**Comment by skaox** [comment] 2020-04-29 22:17
Hi,

Zenmap optionally depends on pygtk which depends on libglade which is a python2-gtk2 component not python3-gtk3.
https://forum.manjaro.org/t/no-module-named-gtk-error-while-running-zenmap/35102

Zenmap is not in the ubuntu repository anymore because is not compatible pyhton3-gtk3 we have to wait until they use PyGObject who replace pygtk and is compatible python3.
https://github.com/nmap/nmap/issues/1176

http://pygtk.org <-who's now-> https://pygobject.readthedocs.io

Ubuntu 20.04 when trying to launch zenmap from terminal :

Could not import the zenmapGUI.App module: 'No module named gtk'.
I checked in these directories:
    /usr/bin
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-x86_64-linux-gnu
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /usr/local/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages/gtk-2.0
    /usr/lib/python2.6/site-packages
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.

I've tried to find an alternative but...
NmapGUI (java) to old and didn't work with my oracle-java14
Nmapsi4 is working but is a bit old and buggy.

If you know another one don't hesitate ;-!

**Comment by N0rbert** [comment] 2020-05-02 13:49
On 20.04 LTS it works after:

```
mkdir -p ~/Downloads/zenmap
cd ~/Downloads/zenmap

wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.80+dfsg1-1build1_all.deb

sudo apt install ./*.deb
```

**Comment by skaox** [comment] 2020-05-02 20:17
Perfect ;-!
THANK YOU

**Comment by Derek1957** [comment] 2020-05-12 05:46
@N0rbert 
Thank you very much! Been looking for 4 hours to find a solution and yours' is perfect...live long & prosper...Derek (Ubuntu 20.04LTS)

**Comment by edurenye** [comment] 2020-05-12 11:00
It's a workaround, it's not a solution.

Zenmap needs to add support to python 3 in order to be added again in the repos, as python 2 has been deprecated.

To fix this, #1176 need to be fixed.

**Comment by fyodor** [comment] 2020-05-26 00:03
Thanks for the notes and workaround code for Ubuntu.  We have been slow with this because the pygtk and Windows aspects make it more difficult than a traditional Python2 -> Python3 port.  But it is on our radar. I am closing this Issue as a duplicate of the older issue #1176 so we can track it all in one place.

**Comment by fyodor** [comment] 2020-05-26 00:04
Duplicate of #1176

**Closed by fyodor** 2020-05-26 00:04 UTC

**Comment by VishnuJeejo** [comment] 2020-06-28 16:22
> On 20.04 LTS it works after:
> 
> ```
> mkdir -p ~/Downloads/zenmap
> cd ~/Downloads/zenmap
> 
> wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
> wget http://archive.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.80+dfsg1-1build1_all.deb
> 
> sudo apt install ./*.deb
> ```

thankyou

**Comment by dazz2014** [comment] 2020-07-14 19:03
> On 20.04 LTS it works after:
> 
> ```
> mkdir -p ~/Downloads/zenmap
> cd ~/Downloads/zenmap
> 
> wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
> wget http://archive.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.80+dfsg1-1build1_all.deb
> 
> sudo apt install ./*.deb
> ```

thankz man..u r grate.. Hearn protect us

**Comment by martijintro** [comment] 2020-07-24 12:25
Not for me, maybe somebody knows why?

![12](https://user-images.githubusercontent.com/42765391/88390964-8e674d80-cdb9-11ea-8007-139490ad43cb.jpg)

**Comment by martijintro** [comment] 2020-07-24 12:26
-> neither dpkg --install ... nor apt instal ... ?!?

**Comment by martijintro** [comment] 2020-07-24 12:38
Oh.... the problem was that i used "dpkg --install ..." first - that was the mistake. I was thinking "dpkg --install" is equivalent to "apt install ..." which is wrong!!

**Comment by martijintro** [comment] 2020-07-24 12:41
at...but at the end i've got an "N" message (warning?), but i don't think this is a real problem...?

![Unbenannt](https://user-images.githubusercontent.com/42765391/88392113-c079af00-cdbb-11ea-88b1-d87e3ddd1317.jpg)

**Comment by DiegoTeixeira7** [comment] 2021-05-25 13:56
`wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb -O pygtk.deb
sudo apt install ./pygtk.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.60-1ubuntu5_all.deb - O zenmap.deb
sudo apt install ./*.deb
sudo zenmap`

**Comment by jayjupdhig** [comment] 2021-05-25 14:11
Thank you very very much!! :-)

**Comment by almir-campos** [comment] 2022-01-16 00:52
@DiegoTeixeira7 <<< Thanks **a lot**! 

Just a small fix required: in the second `wget` there is a space between '-' and '0', causing an error. So, the correct command should be:
```
wget http://archive.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.60-1ubuntu5_all.deb -O zenmap.deb
```

**Comment by N0rbert** [comment] 2022-01-16 07:34
I have update my [comment above](https://github.com/nmap/nmap/issues/2022#issuecomment-622956783) to be fully reproducible:

> On 20.04 LTS it works after:
> 
> ```
> mkdir -p ~/Downloads/zenmap
> cd ~/Downloads/zenmap
> 
> wget http://old-releases.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
> wget http://old-releases.ubuntu.com/ubuntu/pool/universe/n/nmap/zenmap_7.80+dfsg1-1build1_all.deb
> 
> sudo apt install ./python-gtk2_2.24.0-6_amd64.deb ./zenmap_7.80+dfsg1-1build1_all.deb
> ```


Official ZenMap for 22.04 LTS is still needed.

**Comment by maravento** [comment] 2022-11-17 19:54
Ubuntu 22.04
```
sudo apt install ./python-gtk2_2.24.0-6_amd64.deb
The following packages have unmet dependencies:
  python-gtk2 : Depends: python (< 2.8) but not installable
                Depends: python (>= 2.7) but it's not installable
                Depends: python:any (>= 2.6.6-7~) but it's not installable
                Depends: python-cairo (>= 1.0.2-1.1) but it's not installable
                Depends: python-gobject-2 (>= 2.21.3) but it's not installable
```

**Comment by N0rbert** [comment] 2022-11-17 20:48
Use Flatpak then as described in https://github.com/nmap/nmap/issues/1176#issuecomment-1013827740 .
