### ISSUE TITLE
ipidseq.nse uses packet.u16 function that is marked as local

### ISSUE THREAD

**Issue by rainoko** [nmap/nmap#2464] opened 2022-04-10 11:08 UTC
https://github.com/nmap/nmap/blob/705ac8d978cb212bdaa0962cd6b7f6a777586f79/scripts/ipidseq.nse#L234

packet.u16(...) is marked as local (it is right thing to do to achieve correct encapsulation) and cannot be used anymore.  
Maybe separate module for helper functions should be introduced.

**Comment by nnposter** [comment] 2022-04-10 20:13
Thank you for reporting the issue and identifying the root cause. A fix has been committed as r38371.

**Closed** 2022-04-10 21:09 UTC
Labels: bug, NSE script

**Comment by goarblt** [comment] 2022-04-11 15:24
hello
https://www.evil.com/

**Comment by nnposter** [comment] 2022-04-29 17:10
r38371 is not a version but an SVN commit. There is not yet an official version of Nmap that contains this update. Instead, you can simply replace your local copy of the file with what is in [GitHub](https://raw.githubusercontent.com/nmap/nmap/master/scripts/ipidseq.nse) or [SVN](https://svn.nmap.org/nmap/scripts/ipidseq.nse).

**Comment by LiJulle** [comment] 2022-05-03 07:00
Yes thank you now it’s working fine.

**Comment by bhanu5678** [comment] 2022-07-28 04:09
what i have to do solve that problem. please explain me how to copy to local file
