### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by mesteele101** [nmap/nmap#1671] opened 2019-07-26 14:20 UTC
This first half is on Windows 7 using Npcap 0.9881. Installing I got no errors and the service started as shown below.

Npcap 0.9881 is not showing any availabe NIC's. Now rolling back to 0.996 and I have listed the results of that below.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

```
C:\Windows\system32>d:\winids\snort\bin\snort.exe -W

   ,,_     -*> Snort! <*-
  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)
   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team
           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using PCRE version: 8.10 2010-06-25
           Using ZLIB version: 1.2.3

Index   Physical Address        IP Address      Device Name     Description
-----   ----------------        ----------      -----------     -----------

C:\Windows\system32>

C:\Windows\system32>sc query npcap

SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>
```

The Below id Npcap 0.996 and as yu can see it is listing the available NIC. Apparentlt 0.9981 is broken:(

```
C:\Windows\system32>d:\winids\snort\bin\snort.exe -W

   ,,_     -*> Snort! <*-
  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)
   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team
           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reser
ved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using PCRE version: 8.10 2010-06-25
           Using ZLIB version: 1.2.3

Index   Physical Address        IP Address      Device Name     Description
-----   ----------------        ----------      -----------     -----------
    1   00:0C:29:A5:39:2E       0000:0000:fe80:0000:0000:0000:094c:30b5 \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}      Intel(R) PRO/1000 MT Network Connection

C:\Windows\system32>

C:\Windows\system32>sc query npcap

SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>
```

**Comment by dmiller-nmap** [comment] 2019-07-29 17:08
Thanks for the report. Snort appears to not be built to target Npcap, so you must have Npcap installed in WinPcap API-compatible mode. What is the output of `sc query npf`? If it does not show that the service is installed, then reinstall Npcap and select the WinPcap API-compatible option.

If that does not fix the problem, it could be a version mismatch between the driver and the DLLs. Does Snort ship with its own `Packet.dll` or `wpcap.dll`? If so, this could be why it's not working with Npcap. The official line ever since WinPcap has been that the interface between Packet.dll and the NPF driver is opaque and subject to change without notice; in other words, the version of Packet.dll and the NPF driver (npcap driver in this case) must match exactly.

Here are some diagnostic steps to determine if this is the case:

1. Try listing adapters with different software such as an up-to-date Wireshark or Nmap that is intended to be used with Npcap.
2. Delete or rename any `wpcap.dll` or `Packet.dll` in the Snort installation directory so that it is forced to use the system-installed DLLs that Npcap installed.

Regardless, providing output from [DiagReport](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport) could be helpful in diagnosing any issues.

**Comment by mesteele101** [comment] 2019-07-29 17:41
It is definitely a problem with Npcap v0.9981 as v0.996 works. I am using it in WinPcap mode. 

 

I started over with a new install of windows and installed Npcap v0.996 and it works.

 

C:\Windows\system32>d:\winids\snort\bin\snort.exe -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reser

ved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

    1   00:0C:29:A5:39:2E       0000:0000:fe80:0000:0000:0000:094c:30b5 \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}      Intel(R) PRO/1000 MT Network Connection

 

C:\Windows\system32>

 

 

Now I updated from 0.996 to 0.9981 it fails to see any adaptors.

 

C:\Windows\system32>d:\winids\snort\bin\snort.exe -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reserved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

 

C:\Windows\system32>

 

 

I started over again with a new install of Windows, installed Npcap 0.9881 and it fails to see any adaptors.

 

C:\Windows\system32>d:\winids\snort\bin\snort.exe -W

 

   ,,_     -*> Snort! <*-

  o"  )~   Version 2.9.13-WIN32 GRE (Build 15013)

   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team

           Copyright (C) 2014-2019 Cisco and/or its affiliates. All rights reserved.

           Copyright (C) 1998-2013 Sourcefire, Inc., et al.

           Using PCRE version: 8.10 2010-06-25

           Using ZLIB version: 1.2.3

 

Index   Physical Address        IP Address      Device Name     Description

-----   ----------------        ----------      -----------     -----------

 

C:\Windows\system32>

 

Something changed in the code from 0.996 to 0.9881 that makes Snort unable to see the adaptors. Possibility WinPcap compatibility mode. 

 

If you have a windows box or VM, you only need to install short and Npcap.

 

Check for available adaptors: c:\snort\bin\snort -W

 

If you are not seeing any adaptors, Snort won’t work.

 

I preformed the task as you described. I only chose to install Npcap in WinPcap compatibility mode.

 

d:\nmap-7.70-win32\nmap-7.70>nmap –iflist

 

Starting Nmap 7.70 ( https://nmap.org ) at 2019-07-27 10:46 Eastern Daylight Time

************************INTERFACES************************

DEV  (SHORT) IP/MASK                      TYPE        UP   MTU  MAC

eth0 (eth0)  fe80::94c:30b5:237:b9f8/64   ethernet    up   1500 00:0C:29:A5:39:2

E

eth0 (eth0)  192.168.1.132/24             ethernet    up   1500 00:0C:29:A5:39:2

E

lo0  (lo0)   ::1/128                      loopback    up   -1

lo0  (lo0)   127.0.0.1/8                  loopback    up   -1

tun0 (tun0)  fe80::5efe:192.168.1.132/128 point2point down 1280

 

DEV    WINDEVICE

eth0   \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}

eth0   \Device\NPF_{A5EB8922-B7D4-49A8-A30D-E0C8863F1B2D}

lo0    <none>

lo0    <none>

tun0   <none>

<none> \Device\NPF_NdisWanIpv6

<none> \Device\NPF_NdisWanBh

<none> \Device\NPF_NdisWanIp

<none> \Device\NPF_{78032B7E-4968-42D3-9F37-287EA86C0AAA}

 

**************************ROUTES**************************

DST/MASK                     DEV  METRIC GATEWAY

192.168.1.132/32             eth0 266

255.255.255.255/32           eth0 266

192.168.1.255/32             eth0 266

127.255.255.255/32           lo0  306

127.0.0.1/32                 lo0  306

255.255.255.255/32           lo0  306

192.168.1.0/24               eth0 266

127.0.0.0/8                  lo0  306

224.0.0.0/4                  eth0 266

224.0.0.0/4                  lo0  306

0.0.0.0/0                    eth0 10     192.168.1.1

fe80::94c:30b5:237:b9f8/128  eth0 266

::1/128                      lo0  306

fe80::5efe:192.168.1.132/128 tun0 306

fe80::/64                    eth0 266

ff00::/8                     eth0 266

ff00::/8                     lo0  306

 

d:\nmap-7.70-win32\nmap-7.70>

 

WINSNORT.com Management Team Member

--

********************************************************

*     Since 2002 ~~ Visit http://www.winsnort.com

*      ~~ FREE Windows installation Tutorials ~~

*              ~~ FREE Support Forums ~~

* Snort: Open Source Network IDS - http://www.snort.org

********************************************************

**Comment by dmiller-nmap** [comment] 2019-09-04 22:26
Duplicate of #1677

**Closed by dmiller-nmap** 2019-09-04 22:26 UTC
