### ISSUE TITLE
Nmap 7.90:  time result cannot be represented in this installation

### ISSUE THREAD

**Issue by rbernasconi** [nmap/nmap#2141] opened 2020-10-07 10:44 UTC
A default scan (Intense scan) fails with the error:
"C:\Program Files (x86)\Nmap/nselib/afp.lua:353: time result cannot be represented in this installation"
...
QUITTING!

To reproduce start Zenmap, insert a target IP and press "Scan", the command line is:
nmap -T4 -A -v 192.168.XX.YY

OS: Windows 10 Pro 2004
npcap 1.0 (installed with default options plus wireless support)

 - Output of `nmap --version`:
Nmap version 7.90 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.5 openssl-1.1.1h nmap-libssh2-1.9.0 nmap-libz-1.2.11 nmap-libpcre-7.6 Npcap-1.00 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select

**Comment by nnposter** [comment] 2020-10-07 15:56
This known bug has been resolved in commit r38083 (63c88b1a746e77df85a241ee6d6eb726b025da3d). Please refresh file `nselib/afp.lua` from [SVN](https://svn.nmap.org/nmap/nselib/afp.lua) or [GitHub](https://raw.githubusercontent.com/nmap/nmap/master/nselib/afp.lua).

**Closed by nnposter** 2020-10-07 15:56 UTC
Labels: NSE, bug, duplicate

**Comment by nnposter** [comment] 2020-10-08 17:24
Duplicate of #2136

**Comment by fyodor** [comment] 2020-10-14 21:04
Update: this is now fixed in [Nmap 7.91](https://seclists.org/nmap-announce/2020/2)

**Comment by goarblt** [comment] 2022-04-11 15:15
hello
https://www.evil.com/
