### ISSUE TITLE
RDP porbe not worked on not standart port 7.25 Beta

### ISSUE THREAD

**Issue by Sarkancheg** [nmap/nmap#525] opened 2016-08-23 08:08 UTC
If i use nmap 6.47 to detect rdp services on 15325 port.
nmap -p 15325 -A -v -v -Pn 192.168.100.37
I see result
15325/tcp open ms-wbt-server Microsoft Terminal Service

If i use nmap 7.25BETA1 i see next result:
15325/tcp open ssl/unknown syn-ack ttl 128

**Comment by dmiller-nmap** [comment] 2016-08-25 20:21
Thanks for this report! We found the cause and fixed it in 498811b back in June. It will be fixed in the next release, but until then you can apply that commit or download the latest `nmap-service-probes` file to fix it.

**Closed by dmiller-nmap** 2016-08-25 20:21 UTC
Labels: bug, datafiles
