### ISSUE TITLE
Exception when trying to load pcap file using offline device

### ISSUE THREAD

**Issue by tomlevels** [nmap/nmap#1120] opened 2018-01-29 13:56 UTC
In my C# program, I try to load a pcap trace using SharpPcap. When using the normal WinPCap, everything is working fine, but when I install npcap, I get an exception:
SharpPcap.PcapException: 'Unable to open offline adapter: c:\Traces\VLAN.pcap: Permission denied'
I already tried to find similar reports but could not find anything. I also tried running the program in Administrative rights, but that does not help. What could be the issue here?

**Comment by tomlevels** [comment] 2018-01-29 14:35
I already found out the issue. It seems I was not closing the file before opening it using SharpPcap. In previous versions of WinPcap this did not cause any issues, but probably npcap tries to open the file in another way (maybe trying to lock the file) and since the file is already opened, it fails. This is not really an error of npcap, but the behavior seems different than the 'old' WinPcap.

**Comment by gvanem** [comment] 2018-01-29 15:03
Maybe SharpPcap (or you) could make it call `pcap_fopen_offline()` first. Then there should be no problem if it was already opened. Then try l `pcap_open_offline()` .

**Comment by dmiller-nmap** [comment] 2018-01-29 17:58
This looks like another instance of #997. It was speculated there by @guyharris that the MSVC runtime may have changed behavior of `fopen` since WinPcap was built. I will look into this as a potential fix.

**Comment by guyharris** [comment] 2018-01-29 19:11
Probably - but it's not that the `fopen()` behavior changed, it's that libpcap changed to use `fopen_s()` after the last WinPcap release but before the current Npcap release (and the change was from Npcap), and `fopen_s()` defaults to "deny all" sharing rather than the "deny none" sharing done by `fopen()`.  See my update to #997; I asked that somebody file a libpcap issue, pointing back to #997 (and perhaps also to this issue), noting the problem (as it'll be a problem if you build your own libpcap for Windows from the current libpcap source), and I'll revert libpcap to using `fopen()` and apply it to that issue.

**Comment by dmiller-nmap** [comment] 2018-07-03 21:40
Duplicate of #997

**Closed by dmiller-nmap** 2018-07-03 21:40 UTC
