### ISSUE TITLE
iscsi nse scripts failing on iscsi.lua library

### ISSUE THREAD

**Issue by DanMcInerney** [nmap/nmap#206] opened 2015-09-10 21:35 UTC
Both iscsi-brute and iscsi-info are failing with the following exception:

NSE: iscsi-info against 10.96.16.214:3260 threw an error!
/usr/bin/../share/nmap/nselib/iscsi.lua:314: bad argument #1 to 'rshift' (number expected, got nil)
stack traceback:
	[C]: in function 'rshift'
	/usr/bin/../share/nmap/nselib/iscsi.lua:314: in function 'fromSocket'
	/usr/bin/../share/nmap/nselib/iscsi.lua:462: in function 'exchange'
	/usr/bin/../share/nmap/nselib/iscsi.lua:611: in function 'discoverTargets'
	/usr/bin/../share/nmap/scripts/iscsi-info.nse:81: in function </usr/bin/../share/nmap/scripts/iscsi-info.nse:70>
	(...tail calls...)

**Comment by dmiller-nmap** [comment] 2015-09-12 03:33
Thanks for the report. I saw your comment on IRC and I think that the problem is an unexpected packet (probably non-iscsi) or timeout that isn't being caught. I applied a socket error check in r35235 (which has not been mirrored to Github yet). Could you try that out? patch below:

```diff
diff --git a/nselib/iscsi.lua b/nselib/iscsi.lua
index 47b3f5c..7aedea3 100644
--- a/nselib/iscsi.lua
+++ b/nselib/iscsi.lua
@@ -306,6 +306,7 @@ Packet = {
 
       repeat
         local status, header = s:receive_buf(match.numbytes(48), true)
+        if not status then return status, header end
         local pos, _, flags, _, _, len = bin.unpack(">CCCCI", header)
         local cont = ( bit.band(flags, 0x40) == 0x40 )
 
```

**Comment by dmiller-nmap** [comment] 2015-10-28 15:15
@DanMcInerney Have you been able to try out this fix? I'd like to be able to close this issue.

**Comment by DanMcInerney** [comment] 2015-10-28 16:00
Unfortunatley I haven't seen another iscsi device since I posted this.

**Comment by dmiller-nmap** [comment] 2015-10-30 04:28
Ok, I'm closing this as fixed. Please let us know if you have any more problems.

**Closed by dmiller-nmap** 2015-10-30 04:28 UTC
Labels: bug, NSE
