### ISSUE TITLE
Error script Mongodb-databases

### ISSUE THREAD

**Issue by tXambe** [nmap/nmap#2337] opened 2021-07-14 12:11 UTC
Hello,

When executing the script MongoDB-databases I have this error:

```
sudo nmap -d -p27017 --script mongodb-databases 10.0.0.0
Starting Nmap 7.91 ( https://nmap.org ) at 2021-07-14 13:52 CEST
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 1000, min 100, max 10000
  max-scan-delay: TCP 1000, UDP 1000, SCTP 1000
  parallelism: min 0, max 0
  max-retries: 10, host-timeout: 0
  min-rate: 0, max-rate: 0
---------------------------------------------
NSE: Using Lua 5.3.
NSE: Arguments from CLI: 
NSE: Loaded 1 script for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:52
Completed NSE at 13:52, 0.00s elapsed
Initiating Ping Scan at 13:52
Scanning 10.0.0.0 [4 ports]
Packet capture filter (device vpn0): dst host 10.0.0.1 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.0.0.0)))
We got a TCP ping packet back from 10.0.0.0 port 80 (trynum = 0)
Completed Ping Scan at 13:52, 0.06s elapsed (1 total hosts)
Overall sending rates: 69.53 packets / s, 2642.05 bytes / s.
mass_rdns: Using DNS server 127.0.2.1
Initiating Parallel DNS resolution of 1 host. at 13:52
mass_rdns: 0.00s 0/1 [#: 1, OK: 0, NX: 0, DR: 0, SF: 0, TR: 1]
Completed Parallel DNS resolution of 1 host. at 13:52, 0.00s elapsed
DNS resolution of 1 IPs took 0.00s. Mode: Async [#: 1, OK: 0, NX: 1, DR: 0, SF: 0, TR: 1, CN: 0]
Initiating SYN Stealth Scan at 13:52
Scanning 10.95.248.71 [1 port]
Packet capture filter (device vpn0): dst host 10.0.0.1 and (icmp or icmp6 or ((tcp or udp or sctp) and (src host 10.0.0.0)))
Discovered open port 27017/tcp on 10.0.0.0
Completed SYN Stealth Scan at 13:52, 0.05s elapsed (1 total ports)
Overall sending rates: 19.33 packets / s, 850.42 bytes / s.
NSE: Script scanning 10.0.0.0.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:52
NSE: Starting mongodb-databases against 10.95.248.71:27017.
NSE: [mongodb-databases 10.0.0.0:27017] Bson-ERR:Getter for 17 not implemented
NSE: mongodb-databases against 10.0.0.0:27017 threw an error!
/usr/bin/../share/nmap/nselib/mongodb.lua:244: table index is nil
stack traceback:
        /usr/bin/../share/nmap/nselib/mongodb.lua:244: in upvalue '_elements_to_dict'
        /usr/bin/../share/nmap/nselib/mongodb.lua:290: in function 'mongodb.fromBson'
        /usr/bin/../share/nmap/nselib/mongodb.lua:586: in function 'mongodb.query'
        /usr/bin/../share/nmap/scripts/mongodb-databases.nse:86: in function </usr/bin/../share/nmap/scripts/mongodb-databases.nse:52>
        (...tail calls...)

Completed NSE at 13:52, 0.02s elapsed
Nmap scan report for 10.0.0.0
Host is up, received reset ttl 255 (0.0058s latency).
Scanned at 2021-07-14 13:52:25 CEST for 0s

PORT      STATE SERVICE REASON
27017/TCP open  mongod  syn-ack ttl 62
Final times for host: srtt: 5772 rttvar: 4998  to: 100000

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 13:52
Completed NSE at 13:52, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 0.43 seconds
           Raw packets sent: 5 (196B) | Rcvd: 2 (84B)


```

I don't know what's happen.

A greeting and thanks

**Comment by HyunLj** [comment] 2021-07-29 09:06
i recently find this problem. by dong like these , i resolve this problem. you can try it.

----------------------------------------------------
if type(value) ~= 'table' then value=tostring(value) end
if key ~= nil then result[key] = value  end

**Comment by goarblt** [comment] 2022-04-11 15:20
hello
https://www.evil.com/

**Comment by tXambe** [comment] 2022-04-22 06:39
Hello

this configuration where apply or where I have to configure it -->  if type(value) ~= 'table' then value=tostring(value) end if key ~= nil then result[key] = value end

A greeting and thanks

**Comment by nnposter** [comment] 2022-05-07 23:16
This bug appears to be a duplicate of #2393, already rectified in fa029ca53127be26c1d6ab2117a3944508c6fa62.

Please refresh your copy of [nselib/mongodb.lua](https://github.com/nmap/nmap/blob/master/nselib/mongodb.lua). Feel free to reopen the issue if the script crash persists.

**Closed by nnposter** 2022-05-07 23:16 UTC
Labels: bug, duplicate, NSE
