### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [nmap/nmap#2368] opened 2021-09-12 09:34 UTC
**Describe the current behavior**
Looks like in git repo there is no at all git version tags.

**Expected behavior**
Each version should be tagged. With lat version tag for exwmple it would be easier see and asses what has been changed from lat release.

**Comment by fyodor** [comment] 2021-09-15 04:13
Thanks for the suggestion.  This is actually a duplicate of #2311 .

**Closed by fyodor** 2021-09-15 04:13 UTC

**Comment by kloczek** [comment] 2021-09-15 06:37
And .. still no tags :(
I would suggest to move away from svn and embrace power of git.

**Comment by goarblt** [comment] 2022-04-11 15:21
hello
https://www.evil.com/
