### ISSUE TITLE
Ncat fails with input/output error with --ssl

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#773] opened 2017-03-18 05:54 UTC
Ncat throws errors when used with --ssl

Reported on <a href="https://bugzilla.redhat.com/show_bug.cgi?id=1317924">Bugzilla</a> by Paulo Andrade. Related - http://seclists.org/nmap-dev/2015/q4/58

**Comment by dmiller-nmap** [comment] 2017-03-19 02:21
May be duplicate of #197

**Closed** 2017-03-19 02:32 UTC
Labels: bug, Ncat
