### ISSUE TITLE
Installing nmap-7.31-setup.exe on my machine causes all Wi-Fi access to be limited connectivity.

### ISSUE THREAD

**Issue by kumarnipun** [nmap/nmap#613] opened 2016-12-17 15:40 UTC
Installing nmap-7.31-setup.exe on my machine ( windows 7 professional 64 bit) causes all Wi-Fi access to be limited connectivity.
 I have to uninstall Nmap  and than restart my PC to get it working again.

Please help.

**Comment by hsluoyz** [comment] 2017-01-02 13:28
Please download latest Npcap here: https://github.com/nmap/npcap/releases and try again.

**Comment by dmiller-nmap** [comment] 2017-01-19 14:31
Duplicate of #373

**Closed by dmiller-nmap** 2017-01-19 14:31 UTC
Labels: duplicate, Npcap
