### ISSUE TITLE
dnet: Failed to open device eth0 QUITTING!

### ISSUE THREAD

**Issue by Sheep1Man** [nmap/nmap#1655] opened 2019-07-08 15:25 UTC
I have Nmap version 7.70 which downloaded automatically after I installed Metasploit-framework (I use Kali Linux subsystem on Windows 10) but I can't seem to perform any scan because of that error. I tried sudo and restarting, none worked. Any help?
P.S: The first command I tried is "sudo nmap -Pn 192.168.0.197/24" (Tried scanning all the up hosts in my IP range).

**Comment by dmiller-nmap** [comment] 2019-07-09 22:57
Duplicate of #1287

**Closed by dmiller-nmap** 2019-07-09 22:57 UTC

**Comment by dmiller-nmap** [comment] 2019-07-09 22:59
The Nmap Project does not offer support or accept bug reports for Nmap running on Windows Subsystem for Linux. Please use the native Windows build of Nmap from https://nmap.org/download.html#windows instead.
