### ISSUE TITLE
Potential memory leak in nsock_pcap.c

### ISSUE THREAD

**Issue by icy17** [nmap/nmap#2723] opened 2023-10-16 07:35 UTC
In nsock/src/nsock_pcap.c:111
Calling [pcap_compile](https://github.com/nmap/nmap/blob/master/nsock/src/nsock_pcap.c#L111) without releasing the parameter 2 (when pcap_setfilter fails) cause memory leak.

**Comment by dmiller-nmap** [comment] 2023-10-30 20:14
Duplicate of #2609

**Closed by dmiller-nmap** 2023-10-30 20:14 UTC
