### ISSUE TITLE
Npcap-0.07-r10 hang on install.

### ISSUE THREAD

**Issue by markpizz** [nmap/nmap#403] opened 2016-06-05 08:00 UTC
Npcap install never completes on Windows 10.

I downloaded the latest npcap-0.07-r10,exe and ran it on my Windows 10 test VM.  This machine has been used some months ago to test prior npcap installation details.  Before today's activities it did not have any npcap or WinPcap software installed on the system.

I started the installer and let it run with the single checked default option (This is what normal users do, right).  I was a little surprised by the fact that starting the install activities a black window appeared and the quickly disappeared.  Maybe this has nothing to do with the resulting hang.

I then clicked Next and the install started.  It seemed to move along normally for a while.  I received the prompt about installing the driver which I first unchecked the "Always Trust..." checkbox, but then clicked on the OK button.  Things seemed to continue, but then it ultimately stopped moving forward.  Task Manager shows very little or no CPU being used
![npcap-hang](https://cloud.githubusercontent.com/assets/422671/15804317/d7e83ad0-2ab8-11e6-8d8b-645543cc1760.png)

**Comment by hsluoyz** [comment] 2016-06-05 10:42
Hi @markpizz ,

Have you tried a 2nd time? I can't reproduce this issue on my Win10 physical host.


Cheers,
Yang

**Comment by markpizz** [comment] 2016-06-05 10:44
There is no cancel, so for now my only choice seems to be a hard reboot of the OS.  I have no idea what state things will be left in at that time.  I guess a System Restore should be possible.  I'll give it a try.

**Comment by markpizz** [comment] 2016-06-05 11:41
After a System Restore I was able to get a successful install.  I think that after unchecking the "Trust All..." checkbox during the driver install, I might have clicked on the Don't install button.  That probably resulted in the hang.  You might want to look at that case...

**Comment by hsluoyz** [comment] 2016-06-05 12:08
But I already checked "Trust All..."  long before, do you know how to let Windows prompt that window again on an old machine?

**Comment by hsluoyz** [comment] 2016-06-05 14:43
Hi Mark,

I retried the ``Don't install`` option, it prompts me the ``Failed to create the npcap service for Vista, Win7, Win8 and Win10`` window, then the installation stops normally, and I can quit the installer.

So I believe you have installed some incompatible software. If you can name it, I will put it to our incompatible list in README. I will close this issue for now. If you re-encounter it, please reply to this post.

**Closed by hsluoyz** 2016-06-05 14:43 UTC
Labels: bug, Npcap

**Comment by markpizz** [comment] 2016-06-05 17:58
I've installed nothing else on this system since our original testing.

**Comment by hsluoyz** [comment] 2016-06-05 18:04
I saw you stalled at ``NPFInstall.exe -i`` command, which uses a standard driver install code from the MS example or somewhere else. There aren't many places for me to check whether Npcap code causes this. So in this condition, I have to believe this hang is caused by Windows itself for now.
