### ISSUE TITLE
ZENMAP 7.80 fails on startup in openSUSE Linux

### ISSUE THREAD

**Issue by lbickley** [nmap/nmap#1684] opened 2019-08-10 23:33 UTC
Operating Environment:
GTK+ 2.24.32 / GLib 2.54.3
Locale: en_US.UTF-8 (charset: UTF-8)
Operating System: Linux 4.12.14-lp151.28.10-default (x86_64)

zenmap on startup faiils with:
--------------------------------------------------
asrock:~ # zenmap
  File "/usr/bin/zenmap", line 182
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
(base) asrock:~ # 
-------------------------------------------------

Interestingly, starting zenmap in user mode "works" with the usual warnings regarding user mode....

**Comment by ylot0** [comment] 2020-04-12 03:52
same here on ubuntu20.04LTS

**Comment by siv-cmd** [comment] 2020-05-19 08:07
same here on kali 2020.2

**Comment by rrioux** [comment] 2020-05-20 19:23
For those experiencing this error...

I'm using Fedora 32 and openSUSE Leap 15.1. In both instances, the system Python is version 3. Zenmap wants version 2. A quick fix is to edit the first line in /usr/bin/zenmap to directly use python2.

For example:

#!/usr/bin/env python2

This assumes you already installed Python 2 alongside Python 3.

**Comment by siv-cmd** [comment] 2020-05-21 12:14
it works rrioux

**Comment by siv-cmd** [comment] 2020-05-27 04:50
but in linux you need root access to edit the zenmap file for that use thunar file manager

**Comment by fyodor** [comment] 2020-06-13 23:05
Thanks for all of the notes and suggestions. I'm closing this as a Duplicate of #1176 , but I'll post a summary of this discussion to that issue, and of course this issue will still be available for people to review (even though closed as duplicate).  Cheers!

**Closed by fyodor** 2020-06-13 23:05 UTC

**Comment by fyodor** [comment] 2020-06-13 23:16
Duplicate of #1176

**Comment by roy602** [comment] 2020-09-14 09:35
Thank you....it worked fine

**Comment by vijayrajkoduru** [comment] 2020-12-11 20:10
......................it is not working.....................

root@kali:~# zenmap
  File "/usr/bin/zenmap", line 182
    except ImportError, e:
                      ^

**Comment by ElTorado1** [comment] 2021-05-31 16:54
> ......................it is not working.....................
> 
> root@kali:~# zenmap
> File "/usr/bin/zenmap", line 182
> except ImportError, e:
> ^

You can use:

leafpad   /usr/bin/zenmap

Than you must to change first line:

From   #!/usr/bin/env python      to    #!/usr/bin/env python2

**Comment by serdio-nerd** [comment] 2021-10-19 13:50
I've Got This Error after Editing /usr/bin/zenmap 
![Screenshot_20211019_094854](https://user-images.githubusercontent.com/90315466/137923531-f31dc470-0237-4103-b6af-439c6c349697.png)

**Comment by oguzytp** [comment] 2022-01-12 20:57
File "/usr/bin/zenmap", line 114
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

I'm getting an error can you help me?

**Comment by teke6** [comment] 2022-02-17 01:49
> File "/usr/bin/zenmap", line 114 except ImportError, e: ^ SyntaxError: invalid syntax
> 
> I'm getting a kali linux zenmap error, can you help?

did u find it the solution?

**Comment by silaaydiin** [comment] 2022-02-23 20:11
same problem on my Kali: 

File "/usr/bin/zenmap", line 182 except ImportError, e: ^ SyntaxError: invalid syntax

could you help me??

**Comment by hiagosilva12** [comment] 2022-03-14 12:50
> Eu tenho este erro após editar /usr/bin/zenmap ![Captura de tela_20211019_094854](https://user-images.githubusercontent.com/90315466/137923531-f31dc470-0237-4103-b6af-439c6c349697.png)

o meu tá dando esse erro

**Comment by memmedrehimzade** [comment] 2022-05-05 06:44
same problem

**Comment by supervisor1129** [comment] 2023-01-04 02:03
> For those experiencing this error...
> 
> I'm using Fedora 32 and openSUSE Leap 15.1. In both instances, the system Python is version 3. Zenmap wants version 2. A quick fix is to edit the first line in /usr/bin/zenmap to directly use python2.
> 
> For example:
> 
> #!/usr/bin/env python2
> 
> This assumes you already installed Python 2 alongside Python 3.

**Comment by supervisor1129** [comment] 2023-01-04 02:04
Thanks, it is working
