### ISSUE TITLE
Nmap quits if pcap_datalink and Windows adapter info do not match.

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#2381] opened 2021-10-14 18:29 UTC
A licensee reports that Nmap quits with the message, "Error compiling our pcap filter: expression rejects all packets," when scanning for an address in the 169.254.0.0/16 link-local IPv4 network range. This is because the Npcap Loopback Adapter (legacy loopback capture support, possibly a leftover from a previous failed uninstallation of Npcap, see nmap/npcap#55) is reported by Windows as an Ethernet adapter with a route to this network, but libpcap (via Npcap) reports it as DLT_NULL. Nmap chooses it as a route for the ARP scan based on Windows's information, but libpcap's pcap filter optimizer correctly identifies that the ARP protocol has no valid offset for DLT_NULL link types, resulting in the error.

Nmap should instead:
1. Verify that the pcap_datalink() type supports ARP before using ARP scan for host discovery on that link, as well as use that reported link type when constructing raw packets.
2. Not quit (`fatal()`) when pcap filter cannot be compiled for a target or set of targets, but rather mark those targets as unable to scan (similar to unable to resolve or other errors) and proceed with remaining target groups.

**Comment by dmiller-nmap** [comment] 2021-12-14 14:52
Some notes and discoveries:
* If the Npcap Loopback Adapter is correctly installed (i.e. it is registered with the driver and can be used as intended), Nmap will not detect it as anything but a loopback device. Therefore the original report indicates that this was a leftover Npcap Loopback Adapter from a previous installation (nmap/npcap#55).
* libnetutil's standard error mode is to terminate the program. Adding error checking around `set_pcap_filter()` would require extensive rework of all programs (Nmap, Ncat, Nping) as well as libnetutil itself internally.

**Comment by guyharris** [comment] 2022-08-08 19:01
It might help figure out the cause of the failure if the error message included the name of the device and the offending filter, with a change such as this:

```
diff --git a/libnetutil/netutil.cc b/libnetutil/netutil.cc
index 56757e236..4d4eaa49f 100644
--- a/libnetutil/netutil.cc
+++ b/libnetutil/netutil.cc
@@ -4084,9 +4084,9 @@ void set_pcap_filter(const char *device, pcap_t *pd, const char *bpf, ...) {
     netutil_fatal("%s called with too-large filter arg\n", __func__);
 
   if (pcap_compile(pd, &fcode, buf, 1, PCAP_NETMASK_UNKNOWN) < 0)
-    netutil_fatal("Error compiling our pcap filter: %s", pcap_geterr(pd));
+    netutil_fatal("Error compiling our pcap filter (%s) for %s: %s", buf, device, pcap_geterr(pd));
   if (pcap_setfilter(pd, &fcode) < 0)
-    netutil_fatal("Failed to set the pcap filter: %s\n", pcap_geterr(pd));
+    netutil_fatal("Failed to set the pcap filter (%s) for %s: %s\n", buf, device, pcap_geterr(pd));
   pcap_freecode(&fcode);
 }
```

The device name would be less useful on Windows, as most device names consist mostly of a meaningless GUID.  Providing the "friendly name" on those versions of Windows that make it available would be better; if this change would be useful, I could look at Wireshark to see what Windows calls should be used to fetch it.

(In the long run, I'd like to have a new "enumerate interfaces" API as an alternative to `pcap_findalldevs()` and `pcap_findalldevs_ex()`, and another interface that takes a `pcap_t` and gets interface information, designed around the pcapng Interface Description Block, and have that supply a "friendly name" as the interface description if one is available, so that programs don't themselves have to dig up the friendly name.)

**Comment by guyharris** [comment] 2022-10-09 07:14
And there may be other network types that, for example, report an NdisMedium type of `NdisMediumIP`, meaning "no link-layer header, just packets that begin with an IP header"; that may be the case, for example, for Wireguard interfaces.  See, for example, nmap/npcap#640.

This means that Nmap should handle `pcap_compile()` errors in some fashion.  Unfortunately, the `pcap_compile()` API was defined before the New Era, in which libpcap defines multiple `PCAP_ERROR_` values that could allow programs to reliably specific errors and treat them differently, so it returns only a success or failure indication, rather than a success indication and one of a set of error indications, including one or more "you can't filter for that with that header type", so you might have to do a kludge such as checking whether the error string is "expression rejects all packets".

(And, yes, it should also report the error, as that's not the only error message you can get from `pcap_compile()`

**Comment by fyodor** [comment] 2024-09-23 21:06
So the issue which caused pcap_compile to fail was resolved in Npcap some years ago and is so isn't as relevant these days.   Changing libnetutil so that it doesn't fatal() out of so many things (such as pcap_compile failure) would still be an improvement but, given the many other pressing priorities, we might wait until we see another concrete case where we need this rather than spending time and risking destabilization on pre-emptive change just in case.

**Closed by fyodor** 2024-09-23 21:06 UTC
Labels: bug, Nmap
