### ISSUE TITLE
ncat version 7.93 is broken on windows 11.  There doesn't seem to e a download for 7.92.

### ISSUE THREAD

**Issue by steowens** [nmap/nmap#2585] opened 2022-12-16 06:56 UTC
**Describe the bug**
A clear and concise description of what the bug is. When attempting to run the following command we get
ncat localhost 9001
we get
libnsock ssl_init_helper(): OpenSSL legacy provider failed to load.

**To Reproduce**
Steps to reproduce the behavior, including command-line options.
run the above command on a windows 11 machine running the latest ncat.

**Expected behavior**
A clear and concise description of what you expected to happen. For issues related to EOF handling (socket disconnect), see [our document on EOF behavior in Ncat](https://secwiki.org/w/Ncat/EOF_behavior).
expected behavior is that it works.

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]  Windows Professional 11
 - Output of `ncat --version`: 
 ncat -version
Ncat: Version 7.93 ( https://nmap.org/ncat )
Ncat: You must specify a host to connect to. QUITTING.

**Additional context**
Add any other context about the problem here, such as software version of the service you are connecting Ncat to.

**Comment by eternalphane** [comment] 2023-01-22 13:25
duplicate of #2532

**Comment by fyodor** [comment] 2023-01-23 05:52
As @eternalphane notes, this is a duplicate of #2532.  It's not a real error--you can ignore the message.  And the next version of Nmap will only print it in debug mode.

**Closed by fyodor** 2023-01-23 05:52 UTC
Labels: Ncat
