### ISSUE TITLE
zenmap crash 

### ISSUE THREAD

**Issue by GPT4o** [nmap/nmap#2842] opened 2024-05-16 07:51 UTC
![2024-05-16_15-50-26](https://github.com/nmap/nmap/assets/87692915/5c91de41-d6a1-4cdf-a772-7a653fc8ccd7)

Version: 7.95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 286, in run
    window = new_window()
             ^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\App.py", line 130, in new_window
    w = ScanWindow()
        ^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\MainWindow.py", line 140, in __init__
    self.scan_interface = ScanInterface()
                          ^^^^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 141, in __init__
    self.__create_toolbar()
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanInterface.py", line 267, in __create_toolbar
    self.toolbar = ScanToolbar()
                   ^^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 110, in __init__
    self._create_profile()
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ScanToolbar.py", line 142, in _create_profile
    self.profile_entry = ProfileCombo()
                         ^^^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ProfileCombo.py", line 77, in __init__
    self.update()
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapGUI\ProfileCombo.py", line 86, in update
    profile = CommandProfile()
              ^^^^^^^^^^^^^^^^
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\UmitConf.py", line 353, in __init__
    Profile.__init__(self, user_profile)
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\UmitConf.py", line 195, in __init__
    self.read(user_profile)
  File "C:\work\app\Nmap\zenmap\lib\python3.11\site-packages\zenmapCore\UmitConfigParser.py", line 81, in read
    if ConfigParser.read(self, filename):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../lib/python3.11/configparser.py", line 713, in read
  File "../lib/python3.11/configparser.py", line 1037, in _read
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'mbcs' codec can't decode byte 0x8f in position 2073: No mapping for the Unicode character exists in the target code page.

**Comment by fyodor** [comment] 2024-05-16 12:51
Thanks for the report.  This looks like a Duplicate of #2820 , which we are planning to work on soon.

**Closed by fyodor** 2024-05-16 12:51 UTC
Labels: Zenmap
