### ISSUE TITLE
Ncat connecting outside lan

### ISSUE THREAD

**Issue by xkarosx** [nmap/nmap#2442] opened 2022-02-12 08:39 UTC
Hi
A few months back i wanted to use Ncat outside of my local internet 
Basically for an example: i wanted to connect a ncat client from my friends home to my server

And so the problem is:

```
Ncat -lk 2399
```
I do this to create a Listener
```
Ncat 105.34.13.32 2399
```
_replaced public ip with fake ip_
And so when i want to connect to that listener using the machines public ip it doesnt work

Is it even possible? If so how?
Maybe i shouldn't use the public ip?
Its so confusing. Thanks!

**Comment by nnposter** [comment] 2022-02-12 19:00
Yes, this definitely possible. Most likely you are dealing with same networking issues as if you used any other server listener on your system, such as:

* Your server is behind a router NAT and you have not configured port forwarding to your private IP address and port.
* Your server is protected with a router firewall, which does not allow inbound connections.
* You might have a host-based firewall on your server, not allowing inbound connections to this port (or process).

As the issue is a general networking question, not something specific to Ncat, then I am closing it. If my hints do not help then I would suggest to post your question to one of public forums covering home networking.

**Closed by nnposter** 2022-02-12 19:00 UTC
Labels: question, Ncat

**Comment by goarblt** [comment] 2022-04-11 15:24
hello
https://www.evil.com/
