### ISSUE TITLE
NCAT SSL ERROR on 144

### ISSUE THREAD

**Issue by programme-zero** [nmap/nmap#1592] opened 2019-05-11 17:44 UTC
Hello,
I'm trying to get a shell working between Windows and my other machine running on KDE plasma (up to date). The connection establishes and I get the shell, however executing a single command from my Linux machine to the Windows machine will provoke those errors and the connection ends up being lost 
I read several issues here talking about a version error, but I believe to have installed the latest ncat version ( I got it from https://nmap.org/ncat/).
This is the output on the listener (Windows machine) :
`NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG: SSL error on 144: error:00000002:lib(0):func(0):system lib
NCAT DEBUG:
C:\Windows\system32>C`
The errors never stop until I hit Ctrl + C.

The command line I used on the Windows machine : ncat --exec cmd.exe --allow 192.168.0.19 -vnl 4444 --ssl
The command line on the Linux machine : ncat -v 192.168.0.16 4444 --ssl
Thanks for your help.

**Comment by nnposter** [comment] 2019-05-12 00:52
This appears to be a duplicate of #1267.

Published ncat 7.70 binaries predate a fix for this issue. If possible, please try to replicate the issue with ncat compiled from the current source code. (FWIW, I have not experienced these errors with newer ncat.)

**Closed** 2019-05-19 20:13 UTC
