### ISSUE TITLE
Lose connection to network after install npcap 0.9990

### ISSUE THREAD

**Issue by emikg777** [nmap/nmap#2030] opened 2020-04-29 09:23 UTC
After installing and rebooting no internet. I opened wireshark, and had seen trafic from my router, and my own trafic but it seems there is no interconnection between them. DHCP send but there is no answer, static same don't work. No ping in LAN network. I tried reboot but no affect after this. Only command(in cmd as administrator):
`net stop npcap`
and after:
`net start npcap`
After I can't see problem, but after rebooting problem occur again. After uninstall npcap I can't see problem,
OS: Windows 7 x64. 
Problem looks like [this](https://github.com/nmap/nmap/issues/1208)
Fix with  `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Network\MaxNumFilters` don't work.
All logs and DiagReport here:
[DiagReport-20200429-130602.txt](https://github.com/nmap/nmap/files/4550697/DiagReport-20200429-130602.txt)
[NPFInstall.log](https://github.com/nmap/nmap/files/4550698/NPFInstall.log)
[install.log](https://github.com/nmap/nmap/files/4550699/install.log)

**Comment by Astrobirder** [comment] 2020-04-29 15:41
@emikg777  Take a look here, specifically a workaround that works for me, until a fix is released:
https://github.com/nmap/nmap/issues/1998#issuecomment-621284100

**Comment by Fremboli** [comment] 2020-04-30 06:46
Someone should warn the Wireshark people.
I installed 3.2.2 (with Npcap 0.9986) - and Fortigate VPN stopped working.
I installed 3.2.3 (with Npcap 0.9989) - and the complete networking stopped working.
On Windows 7 after reboot. Nice, when you are working from Homeoffice :)

**Comment by emikg777** [comment] 2020-04-30 09:13
@Astrobirder Thank you I will try

**Comment by dmiller-nmap** [comment] 2020-05-05 18:05
This may be a duplicate of #1996/#1998. Please try Npcap 0.9991, released yesterday, which should resolve this issue.

**Closed by dmiller-nmap** 2020-05-05 18:05 UTC

**Comment by goarblt** [comment] 2022-04-11 15:11
hello
https://www.evil.com/
