### ISSUE TITLE
ncat 7.91 with proxy option drops connection after success

### ISSUE THREAD

**Issue by pkreuzt** [nmap/nmap#2280] opened 2021-03-28 17:30 UTC
When using a proxy to make a connection (tested with socks5 type, if relevant) it inmediately drops after connection success without further I/O.

For example, a listener shows this output:

```
$ ncat -l -p 33333 -vv`
Ncat: Version 7.91 ( https://nmap.org/ncat )
Ncat: Listening on :::33333
Ncat: Listening on 0.0.0.0:33333
Ncat: Connection from <anotherhost>
Ncat: Connection from <anotherhost>:49276.
NCAT DEBUG: Closing fd 5.
```

with this connecting ncat vía tor:

```
$ ncat --proxy-type socks5 --proxy localhost:9050 <myhostname> 33333 -vv`
Ncat: Version 7.91 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
Ncat: Connected to proxy 127.0.0.1:9050
Ncat: No authentication needed.
Ncat: Host <myhostname> will be resolved by the proxy.
Ncat: connection succeeded.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_iod_new2(): nsock_iod_new (IOD #2)
Ncat: 0 bytes sent, 0 bytes received in 0.33 seconds.
libnsock nsock_iod_delete(): nsock_iod_delete (IOD #1)
libnsock nsock_iod_delete(): nsock_iod_delete (IOD #2)
```

It should stay connected until interruption

Problem seems to be on client part and specifically 7.91 version. Listener works well when connecting older versions. Affects both Win32 and Linux.

**Comment by nnposter** [comment] 2021-03-28 20:58
This is likely a manifestation of bug #2149, impacting versions 7.90 and 7.91 and rectified last November. If you can, please try to reproduce the bug with a freshly compiled Ncat.

**Comment by pkreuzt** [comment] 2021-03-28 21:03
> This is likely a manifestation of bug #2149, impacting versions 7.90 and 7.91 and rectified last November. If you can, please try to reproduce the bug with a freshly compiled Ncat.

Doy you mean with code from master? I've tested this with an official source tarball (from nmap.org) from a couple days ago.

**Comment by nnposter** [comment] 2021-03-28 21:11
Yes, a fresh source from Subversion or GitHub.

**Comment by nnposter** [comment] 2021-04-15 18:33
No further info provided. Presumably a duplicate of #2149

**Closed by nnposter** 2021-04-15 18:33 UTC
Labels: Ncat, bug, duplicate

**Comment by goarblt** [comment] 2022-04-11 15:19
hello
https://www.evil.com/
