### ISSUE TITLE
RFE: Add TLS v1.3 ciphers

### ISSUE THREAD

**Issue by landgraf** [nmap/nmap#1348] opened 2018-10-09 15:16 UTC
Currently ssl-enum-ciphers can detect tls v1.0,1.1 and 1.2 but doesnt' detect v1.3 as well as sslv3 (tested with 7.70 on Linux). It'd be good to add support for missed ciphers. 
Probably related to #162

**Comment by dmiller-nmap** [comment] 2018-10-09 16:16
I have a private branch where I'm working on TLSv1.3 support for `tls.lua` and `ssl-enum-ciphers`. There are enough big changes in the protocol to make it a challenge to implement. Here are some of the sticking points:

1. Non-AEAD ciphers are not valid in TLSv1.3. Should we test them anyway in case implementations misbehave, or should we go for speed? If we go for speed, should we maintain separate cipher lists for all protocol versions?
2. Parts of the handshake (most notably for us, Certificate and EncryptedExtensions) are encrypted. Should we extend tls.lua to do actual encryption, or make some features of scripts (e.g. certificate parsing) not able to handle TLSv1.3?
3. The `legacy_version` field needs special handling; TLSv1.3 doesn't get its own handshake version, but uses TLSv1.2 with an additional `supported_versions` extension. A TLSv1.3 ClientHello could get a TLSv1.2 ServerHello in response, so we have to add extra checking for that.

Thanks for creating this issue to track progress.

**Comment by kjbeeman** [comment] 2019-03-14 05:09
Any update on support for TLS1.3?

**Comment by bleetsheep** [comment] 2019-10-07 08:40
@landgraf 

> as well as sslv3

You sure about that? Looking in [the nse script](https://svn.nmap.org/nmap/scripts/ssl-enum-ciphers.nse), it explicitly mentions: "This script repeatedly initiates SSLv3/TLS connections" and contains code like `if protocol == "SSLv3"`. Which doesn't mean that it works, but SSLv3 should be supported. If it doesn't work, that's a different bug from missing protocol support.

**Comment by MarcDoughty** [comment] 2019-10-23 19:28
> SSLv3 should be supported

SSLv2 and SSLv3 are legacy protocols, predating TLS, but TLSv1.3 is new and nmap doesn't yet probe for it.

**Comment by dmiller-nmap** [comment] 2021-07-02 19:58
Duplicate of #1691

**Closed by dmiller-nmap** 2021-07-02 19:58 UTC
Labels: NSE, enhancement

**Comment by bleetsheep** [comment] 2021-07-02 20:01
I'm confused, ticket 1348 is a duplicate of another bug reported some 350 tickets later? Isn't that a dup of this then? :p oh well

**Comment by dmiller-nmap** [comment] 2021-07-02 20:04
@bleetsheep The other ticket is the one we have on our project board and has more discussion than this one. If you know of a way to merge an issue with another one, I'd be glad to learn.

**Comment by Johnny4Fun** [comment] 2021-07-07 01:50
so in which version of Nmap can we use the ssl-enum-ciphers to enumerate the ciphers of a server with TLS 1.3? @dmiller-nmap

**Comment by dmiller-nmap** [comment] 2021-07-07 14:34
@Johnny4Fun The changes can be used immediately if you [build Nmap yourself](https://nmap.org/book/install.html#inst-svn) either from SVN or this Github repo. Otherwise, they will be available in the next release, which we hope to issue sometime this summer.
