### ISSUE TITLE
[npcap] - Uninstalling Npcap doesnt uninstall Npcap Loopback Adapter

### ISSUE THREAD

**Issue by lbalbalba** [nmap/nmap#589] opened 2016-11-12 10:02 UTC
When I uninstalled npcap, the loopback adapter remained installed. I had to manually remove the adapter from 'Computer Management -> Device Manager'. After that, my wifi network connection was gone, and I had to uninstall and reinstall my wifi device driver to get it back.

Running Windows 10 Home 'Anniversary Update' (version 1607 [build 14393.447]). Npcap version 0.10-r18, installed in winpcap compatibility mode.

**Comment by lbalbalba** [comment] 2016-11-12 10:36
Hrm. Ive tried to reproduce this, installing/uninstalling npcap 0.10-r18 again (with no previous npcap version installed), and I cant reproduce it.  Something must have gone wrong during the installation or upgrade from previous versions (or during a windows update). Please close this, sorry for the noise.

**Comment by binbjz** [comment] 2017-01-16 10:29
I have also the same issue. How should I uninstall Npcap Loopback Adapter ?

**Comment by lbalbalba** [comment] 2017-01-16 12:39
This seems to have been addressed in Npcap '0.78-r4' and higher: https://github.com/nmap/npcap/releases

**Comment by dmiller-nmap** [comment] 2017-01-18 16:04
@binbjz Please try the latest Npcap release which should resolve this issue.

**Comment by PaulBags** [comment] 2017-02-24 08:04
Would you mind adding an uninstaller for the adapter to the installer? It's a bit much to have to reinstall npcap just to uninstall the adapter.

**Comment by Kyefer** [comment] 2017-02-27 19:59
Just installed 0.82 and uninstalled it. It did not remove the adapter

**Comment by sphaugh** [comment] 2017-02-28 16:32
Please reopen this issue. I believe the orphaned loopback interface is causing networking problems on my machine.

**Comment by PaulBags** [comment] 2017-02-28 18:10
I went in to adapter properties > driver and uninstalled the driver from there, I can't be sure it's clean but it's cleaner than the npcaps uninstallers failure to uninstall.

**Comment by dmiller-nmap** [comment] 2017-02-28 20:37
@PaulBags @sphaugh @Kyefer Thanks for the reports. I'm working through some mixups in the installer code right now, but I'm not sure they're directly related. Can you tell me whether running (in an Administrator cmd.exe) `"\Program Files\Npcap\NPFInstall.exe" -ul` correctly removes the interface? This is how the uninstaller is supposed to do it, but I'd like to see if anything is going wrong. It still seems to work for me here.

**Comment by dmiller-nmap** [comment] 2017-03-01 01:42
Ok, it looks like I can produce loopback interfaces that `NPFInstall -ul` will not remove, if I run `NPFInstall -il` multiple times. This could have happened naturally if previous versions of Npcap were installed and upgraded so that some instance of Npcap Loopback Adapter already existed at the time that the fixed (>0.78r4) Npcap was installed. So the changelog is correct: the uninstaller now successfully removes *one* loopback adapter: namely, the last one installed. But something is wrong causing the older ones to be unremovable with `NPFInstall`. I'll look into this and see if we can fix it. Not exactly sure the best mechanism: always pop the most recent one off, or remove the oldest one first, or prevent installing more than one at all? Ideas welcome.

**Comment by dmiller-nmap** [comment] 2017-03-05 14:08
It appears that NPFInstall has no problem removing the extra loopback adapters if it can find them. We keep the index number of the latest one installed in Npcap's installation directory in the `loopback.ini` file. So here's the procedure to manually clean them up:

1. Open the Npcap installation directory (usually `C:\Program Files\Npcap\`)
2. Run `DiagReport.bat`, which produces `DiagReport-<some numbers>.txt`
3. In the resulting text file, find the section "Network Adapter(s) Info:"
4. Note the `PNPDeviceID` for each of the problem adapters, which looks like "ROOT\NET\0001"
5. For each of the device IDs, extract the number from the end ("1" in the example case) and edit `loopback.ini` to contain just that number.
6. Run `NPFInstall -ul` to remove the selected adapter.
7. Repeat steps 5 and 6 until all the adapters are removed.

I hope to have a better solution in the future, but at least this will clean up your system. And the issue is not likely to happen again unless you manually run `NPFInstall -il` repeatedly.

**Comment by arefai** [comment] 2017-03-08 22:24
I have this same problem. I uninstalled npcap to discover that the adapter was still there. Upon reading your instructions, I reinstalled npcap but unchecked the loopback option so it would not install another adapter. However, I have found the index to be 0 but my installation directory does not have a loopback.ini file. What should I do? 

Thanks for your help.

**Comment by didacci** [comment] 2017-03-17 19:57
Hey, I did all the instructions that dmiller put, but the loopback adapter keeps showing in my Network Connections. Anything to do that? BTW, don't know if there is a problem, but my adapter showed "ROOT\NET\0000" as its ID

**Comment by Neville2312** [comment] 2017-06-13 03:13
# Windows 10 uninstall instructions

Press the Windows/Start key and press x at the same time. Alternatively right click on the start button in the task bar.

Click on Device Manager.

Expand Network Adapters by clicking on the ">" (without quotes) arrow.

Find the Network Adapter which you wish to uninstall. In this case it is called "Npcap Loopback Adapter" (without the quotes).

Right click and select "Uninstall" (without the quotes).

Click "OK" (without the quotes) in the alert box to start the uninstall process.

This should fix your issue.

**Comment by fyodor** [comment] 2017-06-13 03:39
Thanks everyone!  I'm closing this because I believe it was fixed.  The main issue was that Npcap versions 0.78r5 through 0.83 failed to fully uninstall the driver.  A somewhat related problem is that later versions of Npcap didn't (until today) overwrite earlier versions of the driver if they already existed.  We released Npcap 0.92 today, and it both has a properly working uninstaller (as all Npcap's have since 0.83) and, even if the old driver doesn't get deleted somehow, this one is willing to overwrite it with the 0.92 driver.  If anyone is still seeing these problems with 0.92, please let us know.  You can download it from https://nmap.org/npcap/ as usual.

**Closed by fyodor** 2017-06-13 03:39 UTC

**Comment by LorenAmelang** [comment] 2017-08-20 19:58
For months I've seen an "unidentified network" everywhere in my Win10 GUI. I found 
<https://github.com/nmap/nmap/issues/653>
<https://github.com/nmap/npcap/commit/a9b7f9e>
Which seemed to say the new Npcap version should not appear in my Wi-Fi selector or Network Settings as an unidentified network, where it says "npcap loopback adapter doesn't have a valid ip configuration"

--> With default install of new npcap-0.93.exe version - it still appears...
--> Install with support loopback unchecked - it still appears. Even after a restart. 
With "Npcap Loopback Adapter" disabled in Network Connections, it doesn't appear all over, just there.

Trying the uninstall procedure shown above here, there is one "Npcap Loopback Adapter", but inside that it is all Microsoft, version 10.0.14393.0 (rs1_release.160715-1616), \raspptp.sys - is that Npcap? 

The only "events" are from 8/8/2016 10:22:33 AM (the Anniversary Update), device configured (netrasa.inf), device started (Pptp Miniport). No sign of all the installs and supposed uninstalls of Npcap since then! Cycling through all the "Details", the only hints of Npcap are the "Display Name" and "Friendly Name". 

I'm a bit afraid to uninstall this - it doesn't look to me like Npcap...  But how can it have your name? Clues would be very welcome!

**Comment by LorenAmelang** [comment] 2017-08-20 20:26
This gets weirder...  In Device Manager there are now "Microsoft KM-TEST Loopback Adapter" which is Disabled, and "Npcap Loopback Adapter" which is Enabled. The KM_TEST driver shows Events from today and from old installs of Nmap 7.40 and 7.31. Its Details, like the other version all look to be from Microsoft. 

In Control Panel - Network Connections, there is only one entry: 
Npcap Loopback Adapter
Disabled
Microsoft KM-TEST Loopback Adapter

Does this make any sense?

**Comment by MaxFun** [comment] 2017-09-13 23:04
I have tried all the above but can not get rid of the Loopback Adapter.
Also Npcap 0.91 will not uninstall from windows App & feature remove program.
Can you provide a list of register changes to kill this beast?
I am running windows 10

**Comment by FollowSteph** [comment] 2018-10-10 19:57
Just to report I had the same issue as well on Windows 10.

**Comment by dmiller-nmap** [comment] 2018-10-12 17:39
This issue refers to older releases of Npcap. If the same issue persists in recent releases, please follow this procedure:

1. Install the latest Npcap release from https://npcap.org/#download
2. In the Npcap installation directory (usually `C:\Program Files\Npcap\`), run the `FixInstall.bat` script as administrator: right-click -> Run as Administrator.

This should leave you with a correctly-installed Npcap with no extra Loopback Adapters. When Npcap is upgraded or uninstalled, the Loopback Adapter will be removed as well.

If you follow this procedure with the latest Npcap release and still have problems, please open a new issue according to the instructions in the Npcap Guide: https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues

**Comment by EmpireFall** [comment] 2019-05-24 20:01
if attempting to disable or uninstall 'npcap loopback adapter' or if installing any other network related driver onto the system is causing it to bluescreen with the error code 'RQTL_NOT_LESS_OR_EQUAL' on Windows 10, I cannot guarantee this will work but you might want to try the following:-

put the computer into safe mode > right-click the start button (the Windows icon) in the bottom left-hand corner of the screen > click run in the pop-up menu that appears > type in 'msconfig' and hit enter > in the system configuration window, click the 'boot' tap > on the boot tab, in the 'boot options' section, tick 'Safe boot' and select 'minimal' (do NOT select safe mode with 'network' because attempting to remove npcap loopback adapter with that enabled will cause bluescreen) > click 'apply' in the lower right-hand side of the window and the system will then prompt to restart the computer so that the selected settings can take effect (there are many other ways to boot into safe mode, such as holding the power button and forcing the computer to turn off as it is booting up, doing that 3 times in succession will lead into the 'automatic repair' screen where safe mode can be accessed, for further details on how to do that, please look it up via a search engine)

once you have booted into safe mode > right-click the start button (Windows icon) in the lower left-hand corner of the screen > click 'device manager' > in device manager expand 'Network adapters' > right-click 'npcap loopback adapter' and click uninstall driver (if all goes well, it should remove the driver from 'Device Manager' without causing bluescreen) > now, right-click the start button (Windows icon) in the lower left-hand corner of the screen > click 'Settings' in the pop-up menu > click 'Network & Internet' > this should take you directly to the 'Status' menu where at the very bottom you should find 'Network Reset', in the menu that appears click 'reset', a notification window should show up and inform that in 5 minutes the computer will be restarted, the network adapters will then be removed and network settings reset

after booting back into safe mode > right-click the start button (Windows icon) in the lower left-hand side > click 'run' > type in 'msconfig' > when the System Configuration window appears click 'boot' tab > in the 'Boot options' section, untick 'Safe boot' then click apply in the bottom right-hand corner of the window, the computer will prompt the system to restart and this will boot Windows back into the normal operating environment

if you were unable to install any network related drivers before, try doing so again now, to see if bluescreen still occures, again, I cannot guarantee that this will work, it seem to have helped me get rid of that pesky npcap loopback adapter and allowed me to install network drivers without getting that annoying bluescreen with RQTL_NOT_LESS_OR_EQUAL error code, knowing all to well of the frustration that this causes, I hope that this works

and with that I would very much appreciate it if the developers of this software would go #### themselves, it was a ####### headache trying to get your #### off the computer

have a nice day

**Comment by LorenAmelang** [comment] 2019-05-24 22:45
> dmiller-nmap commented on Oct 12, 2018
> This issue refers to older releases of Npcap. If the same issue persists in recent releases, please follow this procedure:
> 
> Install the latest Npcap release from https://npcap.org/#download
> In the Npcap installation directory (usually C:\Program Files\Npcap\), run the FixInstall.bat script as administrator: right-click -> Run as Administrator.
> This should leave you with a correctly-installed Npcap with no extra Loopback Adapters. When Npcap is upgraded or uninstalled, the Loopback Adapter will be removed as well.
> 
> If you follow this procedure with the latest Npcap release and still have problems, please open a new issue according to the instructions in the Npcap Guide: https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues


I found this interesting because of my problem with Hexagora PerfMon 4 not being able to find my actual Wi-Fi adapter:
http://www.hexagora.com/forum/topic.asp?TOPIC_ID=2516

> Yesterday I added an additional USB Wi-Fi adapter, and re-installed the latest Npcap to work with it. Pretty sure PerfMon was still working after that. But today it shows no net activity and "0 interfaces". In Settings it shows tons of interfaces - all of them virtual miniport or loopback adapters. 
> 
> After about 40 of them repeating in the dropdown, it gets to:
> Software Loopback Interface 1
> Software Loopback Interface 
> Software Loopback Interface
> Software Loopback Interfac
> Software Loopback Interfa
> Software Loopback Interf
> Software Loopback Inter
> Software Loopback Inte
> and so on until the line has only the first 'S'. Never finds my actual Wi-Fi, though I'm obviously using it to type this. 
> 
> I've uninstalled PerfMon, deleted its registry keys, reinstalled the latest Performance Monitor 4.1.3, and it just keeps doing this. The order of interfaces in the list changed, but the content didn't. 
> 
> Windows finds a few of the listed interfaces, but not nearly all of them...


Today when I checked in Windows there were 3 Npcap Loopback Adpters, 3, 4, 5, the ones that fill the system log with "no DHCP" errors, and clutter the PerfMon4 adapter list. I eventually deleted them from devmgr. 


> PS C:\Program Files\Npcap> ./CheckStatus.bat
> Npcap Loopback Adapter                          Ethernet 3
> Npcap Loopback Adapter                          Ethernet 5
> Npcap Loopback Adapter                          Ethernet 4

> PS C:\Program Files\Npcap> ./FixInstall.bat
> Dot11Support = 0x1
> LoopbackSupport = 0x1
> WinPcapCompatible = 0x0
> NPCAP_DIR = "C:\Program Files\Npcap"
> 
> The Npcap Packet Driver (NPCAP) service was stopped successfully.
> 
> [SC] ChangeServiceConfig SUCCESS
> The Npcap Packet Driver (NPCAP) (Wi-Fi) service is not started.
> 
> More help is available by typing NET HELPMSG 3521.
> 
> [SC] ChangeServiceConfig SUCCESS
> ROOT\NET\0002                                               : Removed
> Npcap Loopback adapter has been successfully uninstalled!
> Npcap Loopback adapter has been successfully installed!
> [SC] OpenService FAILED 5:
> 
> Access is denied.
> 
> The requested service has already been started.
> 
> More help is available by typing NET HELPMSG 2182.
> 
> The Npcap Packet Driver (NPCAP) service was started successfully.
> 
> The bindings of Npcap driver (with Wi-Fi support) have been successfully restarted!

> PS C:\Program Files\Npcap> ./CheckStatus.bat
> Npcap Loopback Adapter                          Ethernet 3
> Npcap Loopback Adapter                          Ethernet 5
> Npcap Loopback Adapter                          Ethernet 4


PS C:\Program Files\Npcap> ncpa.cpl
[Deleted three adapters]


> PS C:\Program Files\Npcap> ./CheckStatus.bat
> Dot11Support = 0x1
> LoopbackSupport = 0x1
> WinPcapCompatible = 0x0
> NPCAP_DIR = "C:\Program Files\Npcap"
> 
> The Npcap Packet Driver (NPCAP) service was stopped successfully.
> 
> [SC] ChangeServiceConfig SUCCESS
> The Npcap Packet Driver (NPCAP) (Wi-Fi) service is not started.
> 
> More help is available by typing NET HELPMSG 3521.
> 
> [SC] ChangeServiceConfig SUCCESS
> Npcap Loopback adapter has been successfully uninstalled!
> Npcap Loopback adapter has been successfully installed!
> [SC] OpenService FAILED 5:
> 
> Access is denied.
> 
> The requested service has already been started.
> 
> More help is available by typing NET HELPMSG 2182.
> 
> The Npcap Packet Driver (NPCAP) service was started successfully.
> 
> The bindings of Npcap driver (with Wi-Fi support) have been successfully restarted!
> PS C:\Program Files\Npcap>


PerfMon4 is now working! Shows "62 interfaces". The list shows all the previous Npcap Loopback Adapters plus more variations of them, and still shows the final name losing one char from the end until it is just an 'S' - but the display works! 

My Surface Book has no ethernet at all, one internal Wi-Fi adapter, and traces of a USB Wi-Fi adapter that has been connected in the past. Why do these "Npcap Loopback Adapter                          Ethernet 3/4/5/? adapters keep appearing? 

If they have some purpose, is there a way to keep them from filling my Windows System log with hundred of DHCP errors per day? 

Any idea why deleting them would make PerfMon4 work again?

**Comment by snmnrlld** [comment] 2019-05-25 00:23
> if attempting to disable or uninstall 'npcap loopback adapter' or if installing any other network related driver onto the system is causing it to bluescreen with the error code 'RQTL_NOT_LESS_OR_EQUAL' on Windows 10, I cannot guarantee this will work but you might want to try the following:-
> 
> put the computer into safe mode > right-click the start button (the Windows icon) in the bottom left-hand corner of the screen > click run in the pop-up menu that appears > type in 'msconfig' and hit enter > in the system configuration window, click the 'boot' tap > on the boot tab, in the 'boot options' section, tick 'Safe boot' and select 'minimal' (do NOT select safe mode with 'network' because attempting to remove npcap loopback adapter with that enabled will cause bluescreen) > click 'apply' in the lower right-hand side of the window and the system will then prompt to restart the computer so that the selected settings can take effect (there are many other ways to boot into safe mode, such as holding the power button and forcing the computer to turn off as it is booting up, doing that 3 times in succession will lead into the 'automatic repair' screen where safe mode can be accessed, for further details on how to do that, please look it up via a search engine)
> 
> once you have booted into safe mode > right-click the start button (Windows icon) in the lower left-hand corner of the screen > click 'device manager' > in device manager expand 'Network adapters' > right-click 'npcap loopback adapter' and click uninstall driver (if all goes well, it should remove the driver from 'Device Manager' without causing bluescreen) > now, right-click the start button (Windows icon) in the lower left-hand corner of the screen > click 'Settings' in the pop-up menu > click 'Network & Internet' > this should take you directly to the 'Status' menu where at the very bottom you should find 'Network Reset', in the menu that appears click 'reset', a notification window should show up and inform that in 5 minutes the computer will be restarted, the network adapters will then be removed and network settings reset
> 
> after booting back into safe mode > right-click the start button (Windows icon) in the lower left-hand side > click 'run' > type in 'msconfig' > when the System Configuration window appears click 'boot' tab > in the 'Boot options' section, untick 'Safe boot' then click apply in the bottom right-hand corner of the window, the computer will prompt the system to restart and this will boot Windows back into the normal operating environment
> 
> if you were unable to install any network related drivers before, try doing so again now, to see if bluescreen still occures, again, I cannot guarantee that this will work, it seem to have helped me get rid of that pesky npcap loopback adapter and allowed me to install network drivers without getting that annoying bluescreen with RQTL_NOT_LESS_OR_EQUAL error code, knowing all to well of the frustration that this causes, I hope that this works
> 
> and with that I would very much appreciate it if the developers of this software would go #### themselves, it was a ####### headache trying to get your #### off the computer
> 
> have a nice day

THIS DID WORK FOR ME, THANK YOU!

**Comment by dmiller-nmap** [comment] 2019-06-11 18:46
This issue is only relevant to Npcap 0.10. We are locking this issue to avoid confusion. Please open a new issue if Npcap 0.996 or newer is affected.
