### ISSUE TITLE
Network connectivity disruption on Windows 2019 during installation

### ISSUE THREAD

**Issue by mkolechkin** [nmap/nmap#1866] opened 2019-12-19 20:05 UTC
Silent installation of the latest available build 0.9986 on Windows 2019 disrupts connectivity. I started installation with options '/S /winpcap_mode=yes /loopback_support=no' and during installation my Remote Desktop session was interrupted and then RDC reconnected back after some time. Other connections failed, so disruption is a problem. I did not observe this issue on earlier Windows Server versions, like 2012 R2. I did not try Win2016, I heard from a colleague it is not a problem on Win2016, but not sure.
Could you please take a look at this issue.

Thank you,
Mike

[install.log](https://github.com/nmap/nmap/files/3985443/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/3985445/NPFInstall.log)

**Comment by mkolechkin** [comment] 2019-12-19 20:53
I just checked WinPcap 4.1.3 aka 4.1.0.2980 silent installation on the same Windows 2019 machine.
It works perfectly without network disconnection. Just for information, I know they are different (NDIS 5 vs NDIS 6 etc), I just hope it can help to narrow down options.

**Comment by dmiller-nmap** [comment] 2019-12-20 01:39
Thanks for the report. This is a known issue (see #1658 for instance) that is not unique to Npcap; installing the demo NDIS 6 filter driver from [Microsoft/Windows-driver-samples](https://github.com/Microsoft/Windows-driver-samples/) will do the same thing in certain situations. It appears to only affect newer releases of Windows 10 (e.g. Server 2019 Datacenter) and only in some situations like interfaces with QoS or 802.1X enabled. We've reached out on [TechNet Forums](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/2f545a16-721d-4817-8bdf-3648a6cfc00b/installing-ndis-6-lwf-filter-driver-interrupts-networking-in-windows-server-2019-when-qos-enabled?forum=wdk) and [StackOverflow](https://stackoverflow.com/questions/58381644/installing-ndis-6-lwf-filter-driver-interrupts-networking-in-windows-server-2019) without getting any solid answers. It is really out of our hands, and the only workaround currently is to schedule installation for a time when the interruption will have the least impact, such as at the next boot.

I'm closing this issue as a duplicate of #1658, since the underlying cause is the same even if this is not 802.1X-specific.

**Closed by dmiller-nmap** 2019-12-20 01:39 UTC

**Comment by mkolechkin** [comment] 2019-12-20 01:43
Daniel, Thank you!
