### ISSUE TITLE
the npcap-0.85 cause Windows bLUE

### ISSUE THREAD

**Issue by w1nst0nwU** [nmap/nmap#840] opened 2017-04-12 06:50 UTC

**Comment by w1nst0nwU** [comment] 2017-04-12 06:54
we installed the npcap-0.85，but both cause BlueSreen wehn running Wireshark  loading interfaces。we tried WIN10 and WIN7，all the same。 does anyone like it？

**Comment by bguerin** [comment] 2017-04-12 09:58
+1 here

**Comment by dmiller-nmap** [comment] 2017-04-12 12:47
Thanks for the dumps, we'll check on this.

**Comment by dmiller-nmap** [comment] 2017-04-12 13:07
Oh my goodness I'm an idiot. I caught this crash yesterday prior to release, put in a fix and tested it, but forgot to rebuild the installer with the fixed driver. Very simple fix, but I'll probably have to bump the version just to be clear.

**Comment by dmiller-nmap** [comment] 2017-04-12 14:09
The fix has been released in Npcap 0.86. The commit that fixed the issue is nmap/npcap@f919f3ff2efccd71592816501fbf578ab1d0acc9 which was already in the source zip for 0.85 but had not been compiled into the driver.

**Closed by dmiller-nmap** 2017-04-12 14:09 UTC
Labels: bug, Npcap

**Comment by bguerin** [comment] 2017-04-12 20:06
Yeah ! Thanks :)
