### ISSUE TITLE
nmap: Windows version crashes when decoding certain gzip-encoded HTTP response

### ISSUE THREAD

**Issue by cnotin** [nmap/nmap#1883] opened 2020-01-07 14:00 UTC
I use Nmap 7.80 on Windows 10 from the official installer, against an HTTP service with using the http-title script:
> nmap -sSV -p 80 --script http-title --open -n -v -T5 <ip>

It crashes during the NSE scanning phase, just after displaying:
>Initiating NSE at 14:40

A quick debug with Visual Studio (attached on the binary, not using a debug build) shows that the error is in **zlibwapi.dll** (some access violation). Using another debug, I see that the error is around:
https://github.com/nmap/nmap/blob/f566d59595a526e913cd6e7d3b73e4d35014608d/nse_zlib.cc#L398
The zlib inflate function is indeed called to decompress HTTP response body:
https://github.com/nmap/nmap/blob/a87b0ca13311effd7d76a97a227eaeccb5bc28b5/nselib/http.lua#L856-L857

Also, Wireshark shows that the HTTP response is indeed gzip encoded. Hexdump of the body is (if you want to reproduce the bug):
```
    00000201  1f 8b 08 00 00 00 00 00  02 03 8d 54 5d 4f db 30   ........ ...T]O.0
    00000211  14 7d 8f b4 ff 70 f1 5e  c6 83 e3 4d f0 80 68 52   .}...p.^ ...M..hR
    00000221  69 6b 41 30 c1 a8 b6 22  34 21 1e dc e4 a6 71 49   ikA0..." 4!....qI
    00000231  ed cc be 6d a9 a6 fd f7  d9 4d 0b 69 f9 d8 9e 1c   ...m.... .M.i....
    00000241  df 7b 7c ee c9 fd 4a f6  fa 57 bd e1 cf c1 09 9c   .{|...J. .W......
    00000251  0d 2f 2f 60 70 fd e5 e2  bc 07 8c 0b 71 73 d0 13   .//`p... ....qs..
    00000261  a2 3f ec 37 8e c3 f8 e3  27 21 4e be 31 60 25 51   .?.7.... '!N.1`%Q
    00000271  7d 2c c4 62 b1 88 17 07  b1 b1 63 31 fc 2e 4a 9a   },.b.... ..c1..J.
    00000281  56 87 c2 91 55 19 c5 39  e5 ac fb 2e 4a 82 b1 eb   V...U..9 ....J...
    00000291  0f 94 79 37 02 48 a6 48  12 c2 73 8e bf 66 6a 9e   ..y7.H.H ..s..fj.
    000002A1  b2 9e d1 84 9a f8 70 59  23 83 ac b9 a5 8c f0 81   ......pY #.......
    000002B1  56 8c 1d c8 4a 69 1d 52  7a 3d 3c e5 47 ac 1b 05   V...Ji.R z=<.G...
    000002C1  9a 4a e9 7b 28 2d 16 29  13 85 95 53 5c 18 7b 2f   .J.{(-.) ...S\.{/
    000002D1  ae b5 2a 14 e6 71 e6 1c  03 8b 55 ca 1c 2d 2b 74   ..*..q.. ..U..-+t
    000002E1  25 22 31 20 1f 61 4d 1c  00 0d 91 cb ac aa a9 ed   %"1 .aM. ........
    000002F1  9b c8 b9 6c ac 2c 28 5e  b1 df 78 f6 ab d1 04 52   ...l.,(^ ..x....R
    00000301  f8 fd a7 b3 63 8c a9 c4  29 7a 17 63 cf 5c b5 1c   ....c... )z.c.\..
    00000311  e3 e5 d8 f6 25 c9 81 a4  72 e0 05 ab 87 00 15 0b   ....%... r.......
    00000321  1c 7d ae 6b 27 2e e4 d2  cc 48 ac 9e 26 a2 89 bb   .}.k'... .H..&...
    00000331  a5 cc d9 ec c5 7f 9c 38  f6 9a ea 27 9e 44 34 89   .......8 ...'.D4.
    00000341  8f 92 91 c9 97 fe be c7  f9 ad 2a a0 22 38 3f 81   ........ ..*."8?.
    00000351  a3 3b 6f 51 2b 6a 50 79  ca ea f1 94 97 ca 91 b1   .;oQ+jPy ........
    00000361  4b de 98 d9 b3 f0 67 8d  ff 34 18 e2 50 1f 0f 09   K.....g. .4..P...
    00000371  39 4e 59 ae 5c 5d c9 e5  31 68 a3 b1 13 54 34 1c   9NY.\].. 1h...T4.
    00000381  21 ea 2d ea 5c 15 77 9c  07 29 eb 88 bb cc 99 31   !.-.\.w. .).....1
    00000391  f7 0a d7 c7 ff 52 47 49  ae e6 8f e2 cd 1c ad ac   .....RGI ........
    000003A1  2a 1e ba 48 2a 8d 76 55  c1 2d 48 25 f5 78 e6 ab   *..H*.vU .-H%.x..
    000003B1  c2 bd 31 10 f9 c3 b7 e9  0e 68 24 f5 ea f1 2b 6e   ..1..... .h$...+n
    000003C1  32 35 af a5 c6 d7 01 8a  aa ad 08 d1 06 91 55 d2   25...... ......U.
    000003D1  b9 06 f4 96 48 2c 68 27  c2 0e 81 ef 19 b4 eb d1   ....H,h' ........
    000003E1  19 ac 80 6d 8e ac e5 d8  bc 68 db 36 aa 42 cb 6d   ...m.... .h.6.B.m
    000003F1  3e 5a e4 59 85 d2 3e 03  41 68 1e 88 b7 a4 c3 aa   >Z.Y..>. Ah......
    00000401  a2 3b ea 0b 63 e8 8d ec  85 99 e0 e4 b6 d2 d3 8e   .;..c... ........
    00000411  f0 fe c5 4a 36 91 76 4a  19 46 87 3b 92 63 a5 c7   ...J6.vJ .F.;.c..
    00000421  db 05 8d fe 35 d8 42 34  93 0a a3 99 f3 6a 23 55   ....5.B4 .....j#U
    00000431  7c f0 65 85 bd 14 1c 56  c5 be 17 ed af 71 65 32   |.e....V .....qe2
    00000441  49 ca e8 d8 a2 6f c0 0c  3f 04 e7 93 35 2c a0 fd   I....o.. ?...5,..
    00000451  4e d4 9a db 44 9b c7 d9  6b 6b d5 86 4f 1c 0f 32   N...D... kk..O..2
    00000461  7c ec a4 ee 7e f5 5a 7e  34 0a 95 f3 ab ca ef 42   |...~.Z~ 4......B
    00000471  8b b9 8f 09 32 cb d0 39  20 3f 88 e0 97 84 53 84   ....2..9  ?....S.
    00000481  71 22 ea c0 5d 77 07 be  32 0e 01 b5 1c 55 08 2d   q"..]w.. 2....U.-
    00000491  12 63 61 e6 1d 12 46 d6  2c 9c 4f 17 95 d2 ef 8e   .ca...F. ,.O.....
    000004A1  59 5d 1b 4b ae 85 6c b8  1e d3 de 92 2b d6 2b 42   Y].K..l. ....+.+B
    000004B1  34 2b fb 2f 39 4a 92 60  16 06 00 00               4+./9J.` ....
```
CyberChef has no issue in decompressing it ([see recipe](https://gchq.github.io/CyberChef/#recipe=From_Hexdump()Gunzip()&input=ICAgIDAwMDAwMjAxICAxZiA4YiAwOCAwMCAwMCAwMCAwMCAwMCAgMDIgMDMgOGQgNTQgNWQgNGYgZGIgMzAgICAuLi4uLi4uLiAuLi5UXU8uMAogICAgMDAwMDAyMTEgIDE0IDdkIDhmIGI0IGZmIDcwIGYxIDVlICBjNiA4MyBlMyA0ZCBmMCA4MCA2OCA1MiAgIC59Li4ucC5eIC4uLk0uLmhSCiAgICAwMDAwMDIyMSAgNjkgNmIgNDEgMzAgYzEgYTggYjYgMjIgIDM0IDIxIDFlIGRjIGU0IGE2IDcxIDQ5ICAgaWtBMC4uLiIgNCEuLi4ucUkKICAgIDAwMDAwMjMxICBlZCBjYyBiZSA2ZCBhOSBhNiBmZCBmNyAgZDkgNGQgMGIgNjkgZjkgZDggOWUgMWMgICAuLi5tLi4uLiAuTS5pLi4uLgogICAgMDAwMDAyNDEgIGRmIDdiIDdjIGVlIGM5IGZkIDRhIGY2ICBmYSA1NyBiZCBlMSBjZiBjMSAwOSA5YyAgIC57fC4uLkouIC5XLi4uLi4uCiAgICAwMDAwMDI1MSAgMGQgMmYgMmYgNjAgNzAgZmQgZTUgZTIgIGJjIDA3IDhjIDBiIDcxIDczIGQwIDEzICAgLi8vYHAuLi4gLi4uLnFzLi4KICAgIDAwMDAwMjYxICBhMiAzZiBlYyAzNyA4ZSBjMyBmOCBlMyAgMjcgMjEgNGUgYmUgMzEgNjAgMjUgNTEgICAuPy43Li4uLiAnIU4uMWAlUQogICAgMDAwMDAyNzEgIDdkIDJjIGM0IDYyIGIxIDg4IDE3IDA3ICBiMSBiMSA2MyAzMSBmYyAyZSA0YSA5YSAgIH0sLmIuLi4uIC4uYzEuLkouCiAgICAwMDAwMDI4MSAgNTYgODcgYzIgOTEgNTUgMTkgYzUgMzkgIGU1IGFjIGZiIDJlIDRhIDgyIGIxIGViICAgVi4uLlUuLjkgLi4uLkouLi4KICAgIDAwMDAwMjkxICAwZiA5NCA3OSAzNyAwMiA0OCBhNiA0OCAgMTIgYzIgNzMgOGUgYmYgNjYgNmEgOWUgICAuLnk3LkguSCAuLnMuLmZqLgogICAgMDAwMDAyQTEgIGIyIDllIGQxIDg0IDlhIGY4IDcwIDU5ICAyMyA4MyBhYyBiOSBhNSA4YyBmMCA4MSAgIC4uLi4uLnBZICMuLi4uLi4uCiAgICAwMDAwMDJCMSAgNTYgOGMgMWQgYzggNGEgNjkgMWQgNTIgIDdhIDNkIDNjIGU1IDQ3IGFjIDFiIDA1ICAgVi4uLkppLlIgej08LkcuLi4KICAgIDAwMDAwMkMxICA5YSA0YSBlOSA3YiAyOCAyZCAxNiAyOSAgMTMgODUgOTUgNTMgNWMgMTggN2IgMmYgICAuSi57KC0uKSAuLi5TXC57LwogICAgMDAwMDAyRDEgIGFlIGI1IDJhIDE0IGU2IDcxIGU2IDFjICAwMyA4YiA1NSBjYSAxYyAyZCAyYiA3NCAgIC4uKi4ucS4uIC4uVS4uLSt0CiAgICAwMDAwMDJFMSAgMjUgMjIgMzEgMjAgMWYgNjEgNGQgMWMgIDAwIDBkIDkxIGNiIGFjIGFhIGE5IGVkICAgJSIxIC5hTS4gLi4uLi4uLi4KICAgIDAwMDAwMkYxICA5YiBjOCBiOSA2YyBhYyAyYyAyOCA1ZSAgYjEgZGYgNzggZjYgYWIgZDEgMDQgNTIgICAuLi5sLiwoXiAuLnguLi4uUgogICAgMDAwMDAzMDEgIGY4IGZkIGE3IGIzIDYzIDhjIGE5IGM0ICAyOSA3YSAxNyA2MyBjZiA1YyBiNSAxYyAgIC4uLi5jLi4uICl6LmMuXC4uCiAgICAwMDAwMDMxMSAgZTMgZTUgZDggZjYgMjUgYzkgODEgYTQgIDcyIGUwIDA1IGFiIDg3IDAwIDE1IDBiICAgLi4uLiUuLi4gci4uLi4uLi4KICAgIDAwMDAwMzIxICAxYyA3ZCBhZSA2YiAyNyAyZSBlNCBkMiAgY2MgNDggYWMgOWUgMjYgYTIgODkgYmIgICAufS5rJy4uLiAuSC4uJi4uLgogICAgMDAwMDAzMzEgIGE1IGNjIGQ5IGVjIGM1IDdmIDljIDM4ICBmNiA5YSBlYSAyNyA5ZSA0NCAzNCA4OSAgIC4uLi4uLi44IC4uLicuRDQuCiAgICAwMDAwMDM0MSAgOGYgOTIgOTEgYzkgOTcgZmUgYmUgYzcgIGY5IGFkIDJhIGEwIDIyIDM4IDNmIDgxICAgLi4uLi4uLi4gLi4qLiI4Py4KICAgIDAwMDAwMzUxICBhMyAzYiA2ZiA1MSAyYiA2YSA1MCA3OSAgY2EgZWEgZjEgOTQgOTcgY2EgOTEgYjEgICAuO29RK2pQeSAuLi4uLi4uLgogICAgMDAwMDAzNjEgIDRiIGRlIDk4IGQ5IGIzIGYwIDY3IDhkICBmZiAzNCAxOCBlMiA1MCAxZiAwZiAwOSAgIEsuLi4uLmcuIC40Li5QLi4uCiAgICAwMDAwMDM3MSAgMzkgNGUgNTkgYWUgNWMgNWQgYzkgZTUgIDMxIDY4IGEzIGIxIDEzIDU0IDM0IDFjICAgOU5ZLlxdLi4gMWguLi5UNC4KICAgIDAwMDAwMzgxICAyMSBlYSAyZCBlYSA1YyAxNSA3NyA5YyAgMDcgMjkgZWIgODggYmIgY2MgOTkgMzEgICAhLi0uXC53LiAuKS4uLi4uMQogICAgMDAwMDAzOTEgIGY3IDBhIGQ3IGM3IGZmIDUyIDQ3IDQ5ICBhZSBlNiA4ZiBlMiBjZCAxYyBhZCBhYyAgIC4uLi4uUkdJIC4uLi4uLi4uCiAgICAwMDAwMDNBMSAgMmEgMWUgYmEgNDggMmEgOGQgNzYgNTUgIGMxIDJkIDQ4IDI1IGY1IDc4IGU2IGFiICAgKi4uSCoudlUgLi1IJS54Li4KICAgIDAwMDAwM0IxICBjMiBiZCAzMSAxMCBmOSBjMyBiNyBlOSAgMGUgNjggMjQgZjUgZWEgZjEgMmIgNmUgICAuLjEuLi4uLiAuaCQuLi4rbgogICAgMDAwMDAzQzEgIDMyIDM1IGFmIGE1IGM2IGQ3IDAxIDhhICBhYSBhZCAwOCBkMSAwNiA5MSA1NSBkMiAgIDI1Li4uLi4uIC4uLi4uLlUuCiAgICAwMDAwMDNEMSAgYjkgMDYgZjQgOTYgNDggMmMgNjggMjcgIGMyIDBlIDgxIGVmIDE5IGI0IGViIGQxICAgLi4uLkgsaCcgLi4uLi4uLi4KICAgIDAwMDAwM0UxICAxOSBhYyA4MCA2ZCA4ZSBhYyBlNSBkOCAgYmMgNjggZGIgMzYgYWEgNDIgY2IgNmQgICAuLi5tLi4uLiAuaC42LkIubQogICAgMDAwMDAzRjEgIDNlIDVhIGU0IDU5IDg1IGQyIDNlIDAzICA0MSA2OCAxZSA4OCBiNyBhNCBjMyBhYSAgID5aLlkuLj4uIEFoLi4uLi4uCiAgICAwMDAwMDQwMSAgYTIgM2IgZWEgMGIgNjMgZTggOGQgZWMgIDg1IDk5IGUwIGU0IGI2IGQyIGQzIDhlICAgLjsuLmMuLi4gLi4uLi4uLi4KICAgIDAwMDAwNDExICBmMCBmZSBjNSA0YSAzNiA5MSA3NiA0YSAgMTkgNDYgODcgM2IgOTIgNjMgYTUgYzcgICAuLi5KNi52SiAuRi47LmMuLgogICAgMDAwMDA0MjEgIGRiIDA1IDhkIGZlIDM1IGQ4IDQyIDM0ICA5MyAwYSBhMyA5OSBmMyA2YSAyMyA1NSAgIC4uLi41LkI0IC4uLi4uaiNVCiAgICAwMDAwMDQzMSAgN2MgZjAgNjUgODUgYmQgMTQgMWMgNTYgIGM1IGJlIDE3IGVkIGFmIDcxIDY1IDMyICAgfC5lLi4uLlYgLi4uLi5xZTIKICAgIDAwMDAwNDQxICA0OSBjYSBlOCBkOCBhMiA2ZiBjMCAwYyAgM2YgMDQgZTcgOTMgMzUgMmMgYTAgZmQgICBJLi4uLm8uLiA/Li4uNSwuLgogICAgMDAwMDA0NTEgIDRlIGQ0IDlhIGRiIDQ0IDliIGM3IGQ5ICA2YiA2YiBkNSA4NiA0ZiAxYyAwZiAzMiAgIE4uLi5ELi4uIGtrLi5PLi4yCiAgICAwMDAwMDQ2MSAgN2MgZWMgYTQgZWUgN2UgZjUgNWEgN2UgIDM0IDBhIDk1IGYzIGFiIGNhIGVmIDQyICAgfC4uLn4uWn4gNC4uLi4uLkIKICAgIDAwMDAwNDcxICA4YiBiOSA4ZiAwOSAzMiBjYiBkMCAzOSAgMjAgM2YgODggZTAgOTcgODQgNTMgODQgICAuLi4uMi4uOSAgPy4uLi5TLgogICAgMDAwMDA0ODEgIDcxIDIyIGVhIGMwIDVkIDc3IDA3IGJlICAzMiAwZSAwMSBiNSAxYyA1NSAwOCAyZCAgIHEiLi5ddy4uIDIuLi4uVS4tCiAgICAwMDAwMDQ5MSAgMTIgNjMgNjEgZTYgMWQgMTIgNDYgZDYgIDJjIDljIDRmIDE3IDk1IGQyIGVmIDhlICAgLmNhLi4uRi4gLC5PLi4uLi4KICAgIDAwMDAwNEExICA1OSA1ZCAxYiA0YiBhZSA4NSA2YyBiOCAgMWUgZDMgZGUgOTIgMmIgZDYgMmIgNDIgICBZXS5LLi5sLiAuLi4uKy4rQgogICAgMDAwMDA0QjEgIDM0IDJiIGZiIDJmIDM5IDRhIDkyIDYwICAxNiAwNiAwMCAwMCAgICAgICAgICAgICAgIDQrLi85Si5gIC4uLi4))

Seeing that the error seemed to come from zlibwapi.dll, I went to the original site as instructed in one of the README files, http://www.winimage.com/zLibDll/, and downloaded the latest 1.2.3 version. I replaced the original DLL in the Nmap Program Files folder and it works fine now (no crash, and HTTP response properly decoded)!
I do not suggest it as a proven solution because I am not aware of other stuff it might impact.

**Comment by nnposter** [comment] 2020-01-07 14:58
At first glance this appears to be a duplicate of #1723. Can you test nmap from SVN?

**Comment by dmiller-nmap** [comment] 2020-01-07 15:16
The fix for #1723 was a change to the Windows build environment, not
anything in the nmap/nmap repository. Replacing the zlibwapi.dll file is
the right thing to do. Our zlib dll will be corrected in the next release.

**Comment by nnposter** [comment] 2020-01-07 15:20
I do understand that you have not changed the code but the build

**Comment by cnotin** [comment] 2020-01-07 15:58
Thanks @nnposter for your quick feedback. I think you're correct and it could be a duplicate. My test target is an HP printer too.

**Comment by dmiller-nmap** [comment] 2020-01-08 04:21
Duplicate #1723

**Closed** 2020-01-08 04:22 UTC
Labels: NSE, bug
